### ISSUE TITLE
Action: Move

### ISSUE THREAD

**Issue by AllanKirk** [KevinJump/uSync8#10]
Could we have an action type for "Move", just like there is for "Delete"?
Sometimes I want to tidy up the data types by moving related items into a folder, and it would be nice if that was reflected in uSync too.

Right now I can move the data type, do an export, move the files to a clone, and do an import, but then it will not actually move the datatype.

**Comment by KevinJump** [comment]
Hi - Yeah the existing version does that - we should add it to v8 (should be quite easy...)

**Comment by KevinJump** [comment]
(Cleaning up issues) Move was implemented in v8.1.1
