### ISSUE TITLE
Absolute folder path

### ISSUE THREAD

**Issue by engfmaia** [KevinJump/uSync8#100]
We are experiencing some issues with uSync for Umbraco 8 during exportation on save. We use a absolute path to keep the usync files in a folder with the source code and host the website on a different folder.

We add some logs on the source code and saw the following problem inside the SyncHandlerBase.cs

where this line : --- if (!file.InvariantEquals(physicalFile))

compares the following:

c:...\data\ContentTypes/usynctest.config (coming from var physicalFile = syncFileService.GetAbsPath(newFile);)

and

c:...\data\ContentTypes\usynctest.config (coming from var files = syncFileService.GetFiles(folder, "*.config");)

always returning false. With that the previously created file is replace with an "Rename" action file.

Can you please give us some indications how we could fix this?

Thank you so much for your help

**Comment by KevinJump** [comment]
Hi, 
I will need to do a little testing, but i suspect this change to the fileService to ensure that all unresolved paths use `\\` in the path will probably fix it. 

I think when you are using a path outside the site it doesn't get resolved from the website url like most other does ( which gives flicks them to `\\` ) - so the change just makes sure paths we think we've already resolved also flip `/`for `\\` - so everything will compare the same.

**Comment by engfmaia** [comment]
Hi @KevinJump 

Thank you so much for your quick response. We just tested the change on the fileService and looks like everything is working like a charm.

Thank you so much for your help and for uSync :)

**Comment by KevinJump** [comment]
This is also now in the new  release 8.6.2
https://github.com/KevinJump/uSync8/releases/tag/v8.6.2
