### ISSUE TITLE
Unpublish content

### ISSUE THREAD

**Issue by Szpi** [KevinJump/uSync8#101]
**Describe the bug**
When content is previously published, unpublished flag from usync .config file doesn't work.

**To Reproduce**

1. Published some content.
2. Unpublished It.
3. Go to environment when content is published.
4. Make Full import.

or

1. Find published content.
2. Change published flag to false in usync config file for this content : 
`<Published Culture="en">false</Published>`
3. Make Full import.

**Expected behavior**
Content is unpublished.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Additional context**
We have configuration with two languages.
Usync version: v8.6.1.0

I think when full import is made on empty database it works as expected, but not 100% sure.

**Comment by KevinJump** [comment]
Hi yeah, we weren't checking the missing cultures :( 

this fix will be in the next release.

**Comment by Szpi** [comment]
Hi, Thanks for this very fast response :) and fix.

**Comment by KevinJump** [comment]
No worries, just caught the next release too, in 8.6.2 
https://github.com/KevinJump/uSync8/releases/tag/v8.6.2
