### ISSUE TITLE
Honor Backoffice/Group Publisher Config Setting

### ISSUE THREAD

**Issue by keitharowe** [KevinJump/uSync8#106]
Based on the [documentation](https://jumoo.co.uk/usync/publisher/setup/PublisherConfig.pdf) I can see that the "groups" settings is not implemented. I have a highly regulated company that has several non-admin users in the editor group that would like to publish content but do not need/nor should have full admin access. Based on my understanding, publishing is only available to the Administrators backoffice group. Any plans to have this feature honored/implemented? or am I not understanding this setting?

v8.5.0.0 + Content Edition, Snapshots, Exporter, PeopleEdition, Publisher, Licence
Umbraco version 8.5.3

**Comment by KevinJump** [comment]
Hi, I think this is a documentation issue ☹️ 

the latest versions of uSync.Publisher do observe the user Group setting (and you can pick the groups in the UI) - 

![](https://blog.jumoo.co.uk/images/2020/usergroups.png)

you can also limit who can and can't see the publish/pull buttons via the User Group permissions inside Umbraco's user section.

**Comment by keitharowe** [comment]
I am not able to get this to work. I changed the User groups at the top Usync settings to “Administrators,Editors” and also changed the specific uSync Publisher to the same. I then logged in with a user who was in the Editors group and the user does not see any of the uSync publisher options.


-Keith

**Comment by KevinJump** [comment]
Hi, 

There are also Umbraco Permissions setting that you have to add to a group. (so in your case editors won't have this)

e.g.
![image](https://user-images.githubusercontent.com/431231/81824088-fc2b0980-952c-11ea-9fb1-98faec9c03a5.png)

you can set this at the top level (as above) or at the node level (right click Permissions...). 

We are thinking about an update in the next version so when you add a group to a server we add this permission to the group in Umbraco, - but we have to be wary of people being super granular *(and setting it per node)*

**Comment by keitharowe** [comment]
Ahhh, I see!  Brilliant! Testing and working as expected.

I see your point, was this in the documentation? Just a thought, maybe have some additional helper text about setting the uSync permissions on the group.

Thank you for your assistance, much appreciated!

-Keith
