### ISSUE TITLE
Usync does not bring over Articulate images

### ISSUE THREAD

**Issue by Sensibello** [KevinJump/uSync8#109]
**Describe the bug**
When using Umbraco's Articulate blogging platform, Usync will move over all the content, meta descriptions, etc without any problems. However, Usync will not publish/move over the Image a user uploads for the blog post. 

**To Reproduce**
1.  Install Articulate on Umbraco
2.  Create a new blog post
3. Upload an image in the 'image' tab for the blog post. 
4.  Use Usync to move over the blog post to a new environment (for us, we are moving from our UAT to Production environment) 
5. See blog contents moved over via Usync, minus the image. 

**Expected behavior**
Image for blog posts via Articulate to be moved over with the content. 

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser: Chrome, Firefox

**Comment by KevinJump** [comment]
Hi, 

Can you confirm the version of uSync you have ?

I've just taken a look and articulate is uploading images inline (so within the page not the media section) - so It might be this

  Support for this was added to uSync/uSync.Complete in v8.6.1 

_( https://github.com/KevinJump/uSync8/releases/tag/v8.6.1 & https://github.com/Jumoo/uSync.Complete.Issues/releases/tag/v8.6.0 )_

**Comment by KevinJump** [comment]
_Closing as part of clean up. I think this was fixed in v8.6.1_
