### ISSUE TITLE
Export on save cause an error

### ISSUE THREAD

**Issue by stherm** [KevinJump/uSync8#11]
The functionnality "Export on Save" of Usync 8 generate an error. The document is saved, but it's not published.

Error when publichig a document - > Server error : Contact administrator, see log full details
Object reference not set to an instance of an object. 

As previously said, the document is fully save, but since the error happend on the save event, it's not published. When the "Export on Save" is deactivated, everything works fine.

**Comment by KevinJump** [comment]
Hi, 

This should be fixed in the latest beta (4) release https://github.com/KevinJump/uSync8/releases/tag/v8-beta4

(fix in commit 936752295a7b32ed47b0b789ba58c87fb8b6d435)

**Comment by stherm** [comment]
Thank you, I will test it today!

**Comment by stherm** [comment]
Everythings works great!
