### ISSUE TITLE
Cannot import template on umbraco 8

### ISSUE THREAD

**Issue by alanlee2000** [KevinJump/uSync8#111]
Hi,

I am trying to import the template using uSync on umbraco 8 and I only get error message "Failed to create template" in the dashboard as follow. Is there any advance on it? 

Thanks & Regards
Alan

![import_error_umbraco](https://user-images.githubusercontent.com/50823677/58006169-fec17180-7b19-11e9-90ba-66938ee66223.png)

**Comment by KevinJump** [comment]
Hi I think this has been resolved. 

The above error will occur if you haven't copied the view folder over (so the physical .cshtml files are missing). you need to copy over views/css/scripts/ etc as well as the uSync folder for this element to work.

**Comment by afinn-tech** [comment]
Thanks @KevinJump  , is it worth updating to 8.6 ?

**Comment by KevinJump** [comment]
I mean yes, but not because of this issue 🙂 - 

I don't think this was an bug with the version- you might get a better error message, but the underling problem is probably still the missing files in the view.

**Comment by afinn-tech** [comment]
thanks @KevinJump  now got a whole bunch of new errors :) .. on 8.6.3 at least i can see the errors
en-ie.config' because it is being used by another process 
"contentTypeHandler": Import Failed : "System.Data.SqlClient.SqlException (0x80131904): Lock request time out period exceeded.

**Comment by KevinJump** [comment]
that sounds like you have something else open locking the files (was that error when you did an export?) i would check that a file editor or console isn't locking stuff. 

in terms of the contentTypeHandler lock, that is a bit odd but again is something locking the record (e.g are you using a shared db)

**Comment by afinn-tech** [comment]
yes shared db/ and it was on import not export.
Worth trying a full import ?

**Comment by afinn-tech** [comment]
I did an export then import and all errors gone thanks @KevinJump

**Comment by KevinJump** [comment]
cool, 

I would really try to avoid shared DBs though (part of why uSync exists is to avoid them) - not least because in v8 if you have a dev share a db with a server then umbraco treats the whole thing as load balanced and thinks your dev machine is part of the server pool.

**Comment by afinn-tech** [comment]
@KevinJump  do you know why i am missing 
No Handler with "contentHandler" has been loaded ? and in the settings no handlers are shown 
event thought it scans import/export ok

**Comment by KevinJump** [comment]
I suspect your uSync8.config file is missing/corrupt. 

When you upgraded it should have updated the format of this file (the handlers go into groups now).

see . https://github.com/KevinJump/uSync8/blob/v8/dev/uSync8.BackOffice/Config/uSync8.config for what it should look like.

**Comment by afinn-tech** [comment]
![image](https://user-images.githubusercontent.com/65241024/84051508-301c1200-a9a7-11ea-814b-b8109fa011a6.png)
So they are they , just in the settings i cant see them >
i check the config and its the same as the template 
maybe it just doesnt like me :)

**Comment by afinn-tech** [comment]
![image](https://user-images.githubusercontent.com/65241024/84051826-943ed600-a9a7-11ea-8656-b99d176e9372.png)

**Comment by KevinJump** [comment]
if the config is missing, it will default to what it thinks it should do.

**Comment by KevinJump** [comment]
_closing - v8.6.x will install a better default setup when the config file is missing and will also issue warnings into the logs when bits of the config are missing,_
