### ISSUE TITLE
uSync Fails to Publish Content with Error "Step returned false"

### ISSUE THREAD

**Issue by keitharowe** [KevinJump/uSync8#112]
**Describe the bug**
When attempting to publish a single node in the Umbraco backoffice, the Send to Server - Push content to Production fails with "Something went wrong :( "Step return false"

**To Reproduce**
1. Go to Umbraco Backoffice
2. Right Click Node
3. Publish To
4. Select Server
5. Publish Content (Accepting all defaults)
6. Client "Send to Server"

**Expected behavior**
Expected to see report/summary

**Screenshots**
![Error Annotation 2020-06-11 163431](https://user-images.githubusercontent.com/14855713/84437706-7372bc80-ac03-11ea-83e8-d7c9569db48e.jpg)
![Log 1 Annotation 2020-06-11 163951](https://user-images.githubusercontent.com/14855713/84437734-7bcaf780-ac03-11ea-89f4-c7cd535a583c.jpg)
![Log 2 Annotation 2020-06-11 164037](https://user-images.githubusercontent.com/14855713/84437737-7cfc2480-ac03-11ea-96b4-e06fc2968307.jpg)
![Log 3 Detail Annotation 2020-06-11 164443](https://user-images.githubusercontent.com/14855713/84437738-7d94bb00-ac03-11ea-807e-e12358b7d41e.jpg)

**Version**
Umbraco v8.5.3
uSync v8.6.3.0 + Content Edition, Snapshots, Exporter, PeopleEdition, Publisher, Licence

**Additional context**
```
Waring in the Log files: No Handlers configured for requested set "publisher"
No Handlers configured for requested set {setName}
```
Other:

- The source server is load balanced however, the provider/host informs me that Session persistence is on
- The target is not load balanced
- I don't have file system access to the server, so I apologize in advance for the log files format
- The source server has a WAF WebKnight installed and the provider/host has added whitelist rules and is disabled; however, my gut tells me that this might be the cause.

Any help would be greatly appreciated.

**Comment by KevinJump** [comment]
HI ,

I think the "No Handlers" line  points to the uSync8.config file is missing some configurations.

on a uSync.Complete install there should be a new set of handlers added to the uSync8.config file. (we have default examples here https://github.com/Jumoo/uSync.Complete.Issues/blob/master/configs/).

so something like : 
```
 <Handlers Name="publisher">
        <Handler Alias="dataTypeHandler" Enabled="true" Actions="All" />
        <Handler Alias="languageHandler" Enabled="true" Actions="All" />
        <Handler Alias="macroHandler" Enabled="true" Actions="All" />
        <Handler Alias="mediaTypeHandler" Enabled="true" Actions="All" />
        <Handler Alias="memberTypeHandler" Enabled="true" Actions="All" />
        <Handler Alias="templateHandler" Enabled="true" Actions="All" />
        <Handler Alias="contentTypeHandler" Enabled="true" Actions="All" />
        <Handler Alias="publishedContentHandler" Enabled="true" Actions="All" />
        <!-- <Handler Alias="contentHandler" Enabled="true" Actions="All" /> -->
        <Handler Alias="contentTemplateHandler" Enabled="false" Actions="All" />
        <Handler Alias="dictionaryHandler" Enabled="true" Actions="All" />
        <Handler Alias="domainHandler" Enabled="true" Actions="All" />
        <Handler Alias="mediaHandler" Enabled="true" Actions="All" />
        <Handler Alias="memberHandler" Enabled="false" Actions="All" />
        <Handler Alias="memberGroupHandler" Enabled="false" Actions="All" />
        <Handler Alias="userHandler" Enabled="false" Actions="All" />
        <Handler Alias="userGroupHandler" Enabled="false" Actions="All" />
      </Handlers>
```

Without these settings, uSync won't how to serialize the items on disk, so nothing will happen , i think this is what you are looking at.

**Comment by keitharowe** [comment]
> Without these settings, uSync won't how to serialize the items on disk, so nothing will happen , i think this is what you are looking at.

BINGO! 
Thank you very much for your speedy help. You were right on as this corrected my problem.

**Comment by KevinJump** [comment]
we are putting a "fix" in the next release for this which will be when the file is missing or corrupt we load a better set of defaults so things still work.
