### ISSUE TITLE
Option to Use Indented JSON Formatting For Serializing Nested Content

### ISSUE THREAD

**Issue by ltctech** [KevinJump/uSync8#116]
**Is your feature request related to a problem? Please describe.**
The previous major version of uSync would serialize Nested Content to indented JSON format. This allowed one to diff changes between checked in content exports. V8 of uSync serializes Nested Content as a single line. This may be space efficient but it makes diffing hard. 

**Describe the solution you'd like**
Add a flag under uSync settings to export Nested Content as indented JSON.

**Additional context**
It appears that DataType serialization already uses Indented JSON on export.

**Comment by KevinJump** [comment]
yep, simple change, but it does change the format of the output file - so after this people will need to perform a full sync (so it's  #breakingChange )
