### ISSUE TITLE
Import DataType custom PropertyEditor fails

### ISSUE THREAD

**Issue by niklaskdk** [KevinJump/uSync8#12]
Importing of datatype which uses custom property editors fail. I get the following error message.
"Import Fail: Cannot find underling datatype for Domain picker"

1. Create a propertyEditor, I have this package.manifest file in App_Plugins
`{
	"propertyEditors": [
		{
			"alias": "DomainPicker",
			"name": "Domain picker",
			"icon": "icon-list",
			"editor": {
				"view": "~/App_Plugins/DomainPicker/view.html"
			}
		}
	],
	"javascript": [
		"~/App_Plugins/DomainPicker/controller.js"
	]
}`
2. Import the datatype in another Umbraco
3. See error

![usync-datatype-error](https://user-images.githubusercontent.com/7809265/55056792-75d11100-5067-11e9-8fbe-266fa9ca2b11.png)

**Comment by KevinJump** [comment]
Hi, 

i think that means we are failing here https://github.com/KevinJump/uSync8/blob/4619abbfc9bed3ff2f43f6477080ed615e8d25a8/uSync8.Core/Serialization/Serializers/DataTypeSerializer.cs#L140

which is where we ask umbraco for the editor type. (which in this case should be 'DomainPicker") - I will need to do some work, but just to confirm the target site does have the app_plugins/DomainPicker folder before the import is attempted ? 

Kevin

**Comment by niklaskdk** [comment]
> the target site does have the app_plugins/DomainPicker folder before the import is attempted

Yes

**Comment by KevinJump** [comment]
Hi, 

This should be is fixed in the beta 4 release
