### ISSUE TITLE
Templates missing their master

### ISSUE THREAD

**Issue by snoek8** [KevinJump/uSync8#13]
**Describe the bug**
Templates are not imported under the correct master. Using Beta 4.

**To Reproduce**
1. Create a master page template named "master"
2. Create a template under the master named "homepage"
3. Create another nested template under master and name it "Page 2"
4. Run export in uSync
5. Clear out the database and re-install the site and run the import

**Expected behavior**
The 2 nested templates should be displayed as child templates under master in the tree in the backoffice. But the homepage template is created at the root level and only the "Page 2" template gets created under master. 

**Additional context**
The import seems to run in alphabetic order so when "homepage" is created "master" does not yet exist so the import creates it as a root template. The solution would be to import the items per level as the usync config file for the nested templates does correctly indicate they are level 2 and have master as their parent.

**Comment by KevinJump** [comment]
this update - fixes this - will roll up into next release.

**Comment by KevinJump** [comment]
fixed in beta 5 release - https://github.com/KevinJump/uSync8/releases/tag/v8-beta5
