### ISSUE TITLE
Multiple DataTypes not saved if names of those started from a distinguish number, but the rest names are the same

### ISSUE THREAD

**Issue by ReVoid** [KevinJump/uSync8#133]
If multiple datatypes of the same type with a name started from a number, the only one be created by uSync

### How to reproduce:

1. Create several `DataType` of the same type. 
`Textarea` in my case
2. Name it like _"1 some name"_, _"2 some name"_ etc. 
Example in my case:
![image](https://user-images.githubusercontent.com/12345710/87295299-a7484700-c50d-11ea-8556-29b0278ca5fa.png)
3. Check what uSync saves. 
Example in my case: 
![image](https://user-images.githubusercontent.com/12345710/87295498-f5f5e100-c50d-11ea-95c4-50c96e409789.png)
(it is all that has been saved, nothing else)

### Environment
Umbraco 8.6.1
uSync 8.6.1

**Comment by KevinJump** [comment]
yeah ☹️ looks like we use the internal Umbraco `ToSafeFileName `function which strips leading numbers - we do however have a function to handle file clashes, but we currently only use it on tree based items (like content) where the internal names can actually clash. 
https://github.com/KevinJump/uSync8/blob/v8/dev/uSync8.ContentEdition/Handlers/ContentHandlerBase.cs#L58)

think we can safely move this up the bases classes so it's implemented on all items. (need to test that)

**Comment by KevinJump** [comment]
fixed for the next release, 

workaround till then would be to use `UseGuidFileNames` setting ([see docs](https://docs.jumoo.co.uk/uSync/v8/uSync/config/)) (this would require a clean export so the other files are removed)
