### ISSUE TITLE
Custom validation messages not saved into config files

### ISSUE THREAD

**Issue by poornimanayar** [KevinJump/uSync8#145]
It looks like custom validation messages for doc type properties are not saved into the config files.

**Comment by poornimanayar** [comment]
@KevinJump I am happy to pick this up as I think I know where the changes needs to go but the properties are not available in 8.1.1 of Core. I think it was added in 8.6?

**Comment by KevinJump** [comment]
Hi, 

Its really for us to maintain backwards Umbraco compatibility with this ☹️ 

I think there are two fields we need to add ?

`MandatoryMessage` & `ValidationRegExpMessage`

The properties won't exist in the model so code referencing them running pre v8.6 will throw a runtime error 😢 

I think - when a method containing the code is called its not enough for the property to be inside an version specific if statement as parsing of the method will throw the error. 

**so this will fail on pre Umbraco v8.6 installs**
```
If (UmbracoVersion.LocalVersion.Major >= 8 && UmbracoVersion.LocalVersion.Minor >= 6) {
    propNode.Add(new XElement("MandatoryMessage", property.MandatoryMessage);
}
```

In the past what I have ended up ding for something like this is putting the newer code inside it's own method and then wrapping the call to that method inside an version check if statement. (convoluted!) 

e.g this **might** work
```
If (UmbracoVersion.LocalVersion.Major >= 8 && UmbracoVersion.LocalVersion.Minor >= 6) {
    AddMessageProperties(propNode, property);
}

...
protected void AddMessageProperties(XElement propNode, PropertyType property)
{
    propNode.Add(new XElement("MandatoryMessage", property.MandatoryMessage);
}
```

So following that route, i think it would need: 
1) upgrading the solution to Umbraco 8.6 !!
2) putting the set / get of this property in its own methods
3) putting a conditional version check around the calls to those methods. 

> What would be nice (and i am not sure of the best way to do this, so i might not be worth worry about) would be to make this future proof somehow, so we could call a method if it existed for any version. e.g if there are breaking changes in Umbraco 8.7 - we don't have to put an if statement in - just a way of registering something that gets called on properties for v8.7 (so maybe an event, or an interface we implement, that takes version and means we don't touch the core methods to add these values). 

If you do anything, please start with `v8/8.7-main` branch. at the moment that is where the next version is being built as v8.7 might have breaking changes for things in it anyway.

**Comment by KevinJump** [comment]
Also - just to say this might not be trivial, so i am happy to look at it as part of the next release if you think the upgrade etc is to much !!!

**Comment by KevinJump** [comment]
Or the super hack - which will work backwards compatible doesn't require upgrades etc, not sure about performance/if its that nice !

```
var message = property.GetType().GetProperty("MandatoryMessage");
if (message != null)
{
   var value = message.GetValue(property);
   if (value is string stringMessage)
   {
      propNode.Add(new XElement("MandatoryMessage", stringMessage));
   }
}
```

**Comment by KevinJump** [comment]
added breaking change, as no matter what happens this changes the format of the resultant xml files.

**Comment by poornimanayar** [comment]
Yeah I was thinking on the terms of reflection as well. Dont know how performant it could be though.

**Comment by KevinJump** [comment]
performance wise, the big hits are always DB which are orders of magnitude greater than any code boxing/etc, so doing this probably isn't a huge issue. - I might run some tests see what it adds per property etc...

**Comment by poornimanayar** [comment]
More than good if you think its better for you to pick it up :) My offer was only because I saw you have big tasks like supporting bento etc ..

**Comment by KevinJump** [comment]
yeah, that's all sort of on hold, waiting for a v8.7 release date/beta. 

I will take a look at this, reflection is really fast by the looks of it - and unless if becomes more than a couple of properties i can live with a hack.

**Comment by KevinJump** [comment]
will package into next release (8.6.5 soon ish)
