### ISSUE TITLE
net-core review : paths.

### ISSUE THREAD

**Issue by KevinJump** [KevinJump/uSync8#155]
for .netcore paths matter a lot more, you can't get away with some of the lazy path stuff you might with .net framework. 

we need to review all the code that reads/writes to disk and make sure we are building paths consistently, using things like `Path.DirectorySeparatorChar` in the right places.

**Comment by KevinJump** [comment]
best way to confirm this will be to run Umbracon/uSync on linux and see what breaks

**Comment by markadrake** [comment]
Hi Kevin,

If you can give me explicit direction, I'm happy to provide more detail.

Today I downloaded and installed a lot of things to get `dotnet cli` installed on my macOS machine. I started a new project with Umbraco 9's latest beta. I then installed version 9 of usync as well. 

No errors or hiccups along the way. However, when it's time for usync to run it's magic in the background and create files (I suppose) I get an error about my file system being in read only mode. 

Is there a configuration step that I've missed?

Is there anything I can do from my side that would help you track down this bug?

Thank you for all your hard work on this product,

![image](https://user-images.githubusercontent.com/713355/116463994-67064b00-a839-11eb-9b0e-e67d223a4462.png)

**Comment by KevinJump** [comment]
Hi Mark, 

yeah i think i am going to have to crack open a linux build somewhere and test this 😕 

I am guessing its in how we construct paths as part of the process - everything should go through one service which has a call in their to .net code to work out if a path is relative or absolute , and i think that works diffrently to how i throught it did. 

the leading `/` on our root path may be the issue. you could try the following in the applicationsettings.json file and see if it offers any fixes. 

```
uSync" : {
        "Settings" :{
            "RootFolder" : "uSync/v9/",
        }
}
```

it might work 🤞 - but even if it does we probably need to look into the code more to do a proper fix.

**Comment by KevinJump** [comment]
If you want you can try a fix from our nightly feed : 

https://pkgs.dev.azure.com/jumoo/Public/_packaging/nightly/nuget/v3/index.json

version beta002.20210429.1

**Comment by markadrake** [comment]
Did the following to upgrade to the nightly build:

```
dotnet nuget add source https://pkgs.dev.azure.com/jumoo/Public/_packaging/nightly/nuget/v3/index.json
dotnet add package usync -v 9.0.0-beta002.20210429.1
```

And it's resolved everything I could find Kevin. You are a ninja. No more error at startup about the "read-only file system" and no longer running into errors generating files or performing manual exports. 

#H5YR. 

![image](https://user-images.githubusercontent.com/713355/116641225-48d44400-a93a-11eb-8c4b-a20e5f3e41f9.png)

**Comment by markadrake** [comment]
(You still rock.)

However. Was about to commit my usync files and transfer things over to my windows machine and noticed the following folder structure:

![image](https://user-images.githubusercontent.com/713355/116642234-55599c00-a93c-11eb-89cb-dad5a842bacd.png)

**HumbleUmbraco** is the root Umbraco 9 site.

You can see the **HumbleUmbraco/uSync/9/** folder, which is empty.

Usync generated the folder correctly but when actually writing the files they ended up in **HumbleUmbraco/`full-path-to-my-project`/uSync/v9**. A lot of extra folders in the path now. But great work Kevin and thanks so much for the attention you are giving to this.

**Comment by KevinJump** [comment]
HI, 

yeah made it a bit worse with the change - was overly eager in trimming '/' from all paths,

a new nightly `9.0.0-beta002.20210430.7` fixes this, it also does some work with paths and casing in linux installs so it should be a little bit better at the whole "not windows" thing now.

**Comment by markadrake** [comment]
Confirmed on macOS.

![image](https://user-images.githubusercontent.com/713355/116697687-7e584c00-a991-11eb-8631-2dc35356014c.png)
