### ISSUE TITLE
Issue with uSync.config and backoffice config

### ISSUE THREAD

**Issue by erikjanwestendorp** [KevinJump/uSync8#156]
**Describe the bug**
It seems that the handler configuration is displayed differently within the back office than in uSync.config

**To Reproduce**
1. Go to uSync.config
2. Change some settings in the HandlerSets section
3. Compare it with the configuration that appear in the backoffice. 

**Expected behavior**
The appearance of the configuration in the back office is the same as the uSync.config file

**Screenshots**
![image](https://user-images.githubusercontent.com/7831614/92455537-14045880-f1c2-11ea-9921-66743f92e904.png)

**Desktop (please complete the following information):**
 - Umbraco Version: 8.6.4
 - uSync Version:  v8.6.5.0 + Content Edition
 - OS: Windows 
 - Browser: Chrome

**Additional context**
Issue is also after rebuild solution, recycle app pool.

**Comment by KevinJump** [comment]
Looks like it was a typo on the html view. :( 

you do have to re-load the site if you manually change the `usync8.config` file (it doesn't restart for you) - but after that the settings will be reflected in the settings page. 

We do have a plan to make the handler settings UI better, just not there yet. 

anyway Fixed for 8.7 release (when it comes out)

**Comment by erikjanwestendorp** [comment]
@KevinJump That is quickly fixed! Tnx!!
