### ISSUE TITLE
Dictonary items 

### ISSUE THREAD

**Issue by erikjanwestendorp** [KevinJump/uSync8#157]
It would be great if there would be the possibility to deploy dictionary items. I know this possibility is there with the content edition, but we run into the following problem.

We see values ​​within a dictionary item as content, but not the items themselves. If a dictionary item is created in a dev environment, it is nice if it is created after a deployemnt (and import of course). Users then have the possibility to change the values ​​of a dictionary item, but after a new deployment and import these changes are reverted.

It would be great if there were a difference between creating dictionary items (in the regular edition) and updating the values (content edition)

**Comment by KevinJump** [comment]
Hi Eric, 

With the dictionary handler, its possible to configure it to be 'OneWay' which is to say it will create new dictionary items but not update any values of existing ones (so if a user has updated them, then they will not change).
https://docs.jumoo.co.uk/uSync/v8/ContentEdition/dictionaryHandler/

is this what you where looking for?

**Comment by erikjanwestendorp** [comment]
@KevinJump Thanks for your quick response! This is indeed what I am looking for!

**Comment by poornimanayar** [comment]
> Hi Eric,
> 
> With the dictionary handler, its possible to configure it to be 'OneWay' which is to say it will create new dictionary items but not update any values of existing ones (so if a user has updated them, then they will not change). https://docs.jumoo.co.uk/uSync/v8/ContentEdition/dictionaryHandler/
> 
> is this what you where looking for?

@KevinJump is this feature still available? The link is broken on the above reply

**Comment by KevinJump** [comment]
Yes,

There are two ways to do it now.

"Create only" works for all handlers:

https://docs.jumoo.co.uk/usync/uSync/reference/handlers#handler-settings

I think one-way still works for dictionary it's just not documented
