### ISSUE TITLE
8.7 Strange message in Change report

### ISSUE THREAD

**Issue by NikRimington** [KevinJump/uSync8#158]
Hey Kevin,

I've just done a full export from a dev site and imported into a staging environment after upgrading to v8.7

I'm seeing this in the change report:

![image](https://user-images.githubusercontent.com/13313745/92952074-45e21d00-f457-11ea-91f5-f46f1175dd7c.png)

Thanks

Nik

**Comment by KevinJump** [comment]
Hi, 

Is this content? 
What type of datatype is 'Allowed' ?

at first i thought this might be 'Allowed Child node types' or 'Allowed templates' but they are not called 'allowed' internally :(

**Comment by NikRimington** [comment]
Hey Kevin,

 This was on a doc type, so I'm assuming it's what types are allowed to be created beneath it.

Cheers

Nik

**Comment by KevinJump** [comment]
think we've fixed this #189
