### ISSUE TITLE
8.7 Member type import always has GUID changes

### ISSUE THREAD

**Issue by NikRimington** [KevinJump/uSync8#159]
Hey Kevin,

I'm seeing constant member type changes being report after upgrading to 8.7:

![image](https://user-images.githubusercontent.com/13313745/92952231-8d68a900-f457-11ea-940e-16bbc71601da.png)

It doesn't matter how many times I import I see the following changes being reported.

Thanks

Nik

**Comment by KevinJump** [comment]
Hi, 

the Definition id is the one which is used to find the data type, so randomly it thinks the datatype guid has changed. now its possible it has, but then a sync should then change the Guid of the datatype when it imports them :( 

if you search the usync folder for the before GUID value do you find anything in the datatypes folder, equally does the a datatype exist with the new guid value ? 

its possible the datatypes are actually the thing out of sync (its also possible uSync isn't updating something properly)

**Comment by NikRimington** [comment]
Interesting, I'll investigate and let you. However it reminds me of the old bug we discussed where default member properties didn't handle quite right. As I'm sure these are the same properties.

**Comment by AndyFelton** [comment]
Hi Kevin/Nik,

I'm getting the same issue and also losing the default member properties with V8.7.0.

I've checked the data type GUID that it's trying to update to (interesting the same as what Nik has so must be a default Umbraco one) and believe this is Umbraco.TrueFalse which looks to be incorrect for some of these fields.

Thanks
Andy

**Comment by KevinJump** [comment]
Hi Andy,

Yeah we have identified that we missed a fix from the 8.6.5 release - when putting 8.7.0 together. 😞 

We've put it in now and just pushed 8.7.0.1 version of uSync.Core (@NikRimington has tested this one) so this should fix it. 

```
Install-Package uSync.Core -Version 8.7.0.1
```

**Comment by KevinJump** [comment]
there is a fix for this in 8.7.1 - but we also have an issue where the hashed value is different depending on framework/platform, so there is a pending fix for 8.7.2 #142 - closing this issue. tracking in #142
