### ISSUE TITLE
Package upgrade overwrites uSync8.config

### ISSUE THREAD

**Issue by lindeberg** [KevinJump/uSync8#170]
**Describe the bug**
Title says it. I upgraded from 8.7.0.1 to 8.7.1.

**Expected behavior**
I am not sure. But I expect my configs to remain after upgrade. 
Otherwise add to documentation?

**Screenshots**
![image](https://user-images.githubusercontent.com/15940340/95178789-202f0600-07c0-11eb-968c-cd7383078eff.png)

**Desktop**
 - Umbraco Version:  8.6.4
 - uSync Version: 8.7.1
 - OS: Windows 10

**Comment by KevinJump** [comment]
When you update via nuget it will overwrite files that have not been altered between package installations (so if your config was unaltered before the update it wouldn't overwrite it)

NuGet will only override changed files if you ask it to, so via the -FileConflictAction flag ([Nuget Docs](https://docs.microsoft.com/en-us/nuget/reference/ps-reference/ps-ref-update-package)) or confirming when prompted. 

I don't think we are doing anything special here - but if we are it would be good to work out how that happend.

The changes to the config, are comments for new features that are off by default but nothing is 'added' to the config by default (so not changing it is fine - everything works as before).
