### ISSUE TITLE
Usync missing from Dashboard

### ISSUE THREAD

**Issue by jmaxwell1562** [KevinJump/uSync8#174]
I'm running Umbraco 8.6.1 

I installed Usync 8.7.0.1 using nuget in Visual Studio.  I've done this twice. Both times, Usync does not show up in the Umbraco Settings section.

**Comment by KevinJump** [comment]
Hi,

just tried on a clean install and its working for me :( 
![image](https://user-images.githubusercontent.com/431231/95511489-77df9400-09af-11eb-9f33-6ffdf9f52107.png)

are you getting anything uSync related in the logs ?
![image](https://user-images.githubusercontent.com/431231/95511562-8af26400-09af-11eb-810b-d0064672eeda.png)

**Comment by jmaxwell1562** [comment]
Yep, my logs look the same, not seeing any errors.

**Comment by KevinJump** [comment]
- does you solution have an app_plugins/uSync8 folder. 
- what happens if you increment the version number in the 'clientDependency.config' file. 

(although i am not sure - because both of these would cause browser issues, the dll that writes out those log entries is the same one that adds the uSync node in the settings tree).

**Comment by jmaxwell1562** [comment]
Yes, solution has the uSync8 folder

Incrementing the clientDependency did not help

**Comment by KevinJump** [comment]
OK, so it's guessing time as I can't recreate this.

The tree node gets added by a fairly simple/standard Tree controller (https://github.com/KevinJump/uSync8/blob/v8/8.7-main/uSync8.BackOffice/Controllers/Trees/uSyncTreeController.cs#L16)

Do you have anything custom happening at compose time in your solution, are you using another form of Dependency Injection (on v7 you use to have to do things to get trees registered when you did this).

**Comment by jmaxwell1562** [comment]
No

**Comment by KevinJump** [comment]
Any random things in the tree on the left of the settings page like '[ ]' or anything, could you post a screen shot ?

**Comment by jmaxwell1562** [comment]
OK, this is fine. I'm seeing the dashboard now. Thank you for your help.

**Comment by KevinJump** [comment]
OK.
