### ISSUE TITLE
Allow translation dictionary keys and translation to be synced separately

### ISSUE THREAD

**Issue by deMD** [KevinJump/uSync8#176]
**Is your feature request related to a problem? Please describe.**
For a client of ours we use the translation library to contain all the different labels (f.e. "view this" for video) for all languages. As this is no normal content and is shared among many pages it's not real content. However, our client wants to manage the texts themselves. A problem we currently have is that the usync does not allow to sync only dictionary keys without the translations. This would mean that for every release we need to sync back all translations from live, update with the new keys and then release because otherwise we override the translations our client made.

**Describe the solution you'd like**
The solution I'd like is for usync to split dictionary keys and translations into separate files so we can sync only the keys without the translations.

**Comment by KevinJump** [comment]
Hi, 

We have a handler setting you can pass to the dictionary Handler of OneWay, which will only create items if they do not already exist, so this would stop the values from being overwritten and only the new ones would be created .

e.g 

```xml
<Handler Alias="dictionaryHandler" Enabled="true">
 <Add Key="OneWay" Value="true" />
</Handler>
```
_[Dictionary handler docs](https://docs.jumoo.co.uk/uSync/v8/ContentEdition/dictionaryHandler/)_

(for uSync 8.7+ there is a global `CreateOnly` version of this that works for all handlers)

but it is quite easy for us to add a setting to handler, so we've added a `KeysOnly` setting for the next release that would only sync the keys.

**Comment by deMD** [comment]
Amazing :D Thanks for the update, I will add the OneWay key for now and when the update is live check out the KeysOnly setting!
