### ISSUE TITLE
The grid Background image

### ISSUE THREAD

**Issue by lori698** [KevinJump/uSync8#177]
We're using the background images on the grid set via the cog 

When I go to sync (usync complete) the background images dont appear to go across.

![backgroundImage](https://user-images.githubusercontent.com/16773535/96446551-51202980-1209-11eb-8745-07c83b58319d.png)

**Comment by KevinJump** [comment]
Hi, 

yeah, looks like we are not calculating the media dependencies in the config section :( - I've created an issue over in the uSyncComplete issues repo, so we can track the fix into a release.

**Comment by lori698** [comment]
great thanks Kevin
