### ISSUE TITLE
Ignore Approved Colour Picker

### ISSUE THREAD

**Issue by lori698** [KevinJump/uSync8#178]
Is there any way to always ignore the approved colour picker - we want to turn on automatic imports however we have x amount of sites with unique approved colours which we will never want to import.

Also needs be ignored on the grid background row| cell colours. (If possible)

**Comment by KevinJump** [comment]
Humm... its not possible via config - but we might be able to work out something to make it a thing... we will take a look.

**Comment by lori698** [comment]
Fantastic thanks

**Comment by lori698** [comment]
Wow fantastic

**Comment by KevinJump** [comment]
Hi this will be in the next release we are testing it this week, so it should be out soon

**Comment by loriRyanp** [comment]
Hi Kevin just wondering how do I go about setting this up so that approved colours dont get imported? Thanks in advance.

**Comment by KevinJump** [comment]
Hi, 

if you want the datatype to be created but the config (so the colors not synced you would add the following to your uSync8 config file

To stop all color pickers from syncing their colours :
```xml
 <Handler Alias="dataTypeHandler" Enabled="true" Actions="All">
     <Add Key="NoConfigEditors" Value="Umbraco.ColorPicker" /> 
 </Handler>
```

To stop just a specific colour picker from syncing (so all the others still would).
```xml
 <Handler Alias="dataTypeHandler" Enabled="true" Actions="All">
     <Add Key="NoConfigNames" Value="Approved Color" /> 
 </Handler>
```
