### ISSUE TITLE
Import sync pack spinning -Usync v8.7.1.0 + Content Edition, Snapshots, Exporter, PeopleEdition, Publisher, Complete

### ISSUE THREAD

**Issue by lori698** [KevinJump/uSync8#179]
On using Import Sync-Pack seems to get stuck now  - is there anywhere to see whats causing the issue? There nothing in the log viewer

![image](https://user-images.githubusercontent.com/16773535/96581049-239eb300-12d1-11eb-9ced-9a1a8d21d100.png)

**Comment by KevinJump** [comment]
Hi

Is there anything in the browser console (right click on the page 'inspect'

**Comment by lori698** [comment]
I left it run for ages (Its not that big of a change just a docType with 4 properties) and it didnt give me the report. I went back and tried again and it gave  me the report and allowed me to import. I keep an eye if I can replicate, if I can I reopen.
There is one error in the console -  typeError cb is not a function
