### ISSUE TITLE
Is there a way to transform data when altering a datatype.

### ISSUE THREAD

**Issue by Myster** [KevinJump/uSync8#180]
**Is your feature request related to a problem? Please describe.**
We use uSync to transfer datatypes, content types etc, we do not use it to sync content.
We deployed a change to a doctype where we changed a media picker to a nested content picker.
However the page that was changed now raises an exception because the json of the media picker does not match the json for the nested content picker.

**Describe the solution you'd like**
I'm not sure what a solution would be...

**Describe alternatives you've considered**

- In v7 we used code based migrations (uMigrate) where we could write a migration method to transform the json, but this doesn't seem to fit the uSync way of doing things.
 - Some kind of notification that there is going to be a problem (a lot of datatype changes won't cause a problem, and a lot will, so I don't know how uSync could know which is which)

**Additional context**
I guess if we were syncing content along with the datatype change this wouldn't be a problem, but we utilise the fact content in each environment is different. (and we don't need the paid edition of uSync)
We also like that it's fully automated and we don't need to manually sync anything, just make changes locally and commit usync config files.

**Comment by KevinJump** [comment]
Hi,

Yeah its not easy (and probably not possible once you get into the realm of custom properties) to know what datatypes are going to cause issues when you change them. This would still be an issue inside a non synced Umbraco installation, changing from media to nested isn't going to convert all of the existing content in a site when you do it.  

Currently I thing you would have to know you are about to do this and then add some form of [migration](https://cultiv.nl/blog/using-umbraco-migrations-to-deploy-changes/) to your site to update the content data. 

Or you could hook into uSync events. uSync will fire an `ImportComplete` event when its finished an import, but out-of-the-box uSync isn't performing migration like updates, it is syncing everything from disk everytime. So following this event, you would have to have your own way of knowing if you have performed the data migration before  or risk running the code after every sync.
