### ISSUE TITLE
Configuration transforms removed when upgrading via Nuget

### ISSUE THREAD

**Issue by enkelmedia** [KevinJump/uSync8#181]
**Describe the bug**
We have a setup where we have configuration-transforms for different environments, ie `/config/uSync8.Stage.config`, when upgrading via NuGet both from the solution and from disk.

**To Reproduce**
1. Create a uSync8.Stage.config-file 
2. Upgrade uSync via nuget

**Expected behavior**
Would expect the any files that is not files shipped by uSync to be untouched. I guess that there is some "remove all uSync*"-step somewhere?

**Desktop (please complete the following information):**
 - uSync Version:  8.7.2

**Comment by KevinJump** [comment]
Hi, 

there is nothing in the package or code to remove any uSync*.config files, I think this is a visual studio thing 😞 


If you nest the `uSync.stage.config` file beneath the `usync8.config` file, then during the nuget upgrade the nested files are removed. 

![image](https://user-images.githubusercontent.com/431231/97024598-e9424980-154e-11eb-8509-173dca7e0ad5.png)
(removed when nested)

If the file is not nested then during the upgrade it isn't touched. 
![image](https://user-images.githubusercontent.com/431231/97024660-fa8b5600-154e-11eb-91da-0d120b878fc5.png)
(unnested it remains)

Having a look to see if there is any documentation around this, or any flags we can set to stop it but i am not sure.

**Comment by enkelmedia** [comment]
I see! 

I looked around in the source but could not find anything that looked like it removed anything but I understand that VS might be the issue here.

I'll just remove the nesting =D

// m

**Comment by KevinJump** [comment]
If you alter the usync8.config file in anyway (put a space in it or something) then during the update-package you will be prompted to replace it, and if you say no, then it doesn't remove the nested files (my guess is nuget deletes and recreates the file and visual studio deletes the nested elements at that point).
