### ISSUE TITLE
Events are not unregistered on termination

### ISSUE THREAD

**Issue by nzdev** [KevinJump/uSync8#182]
**Describe the bug**
Static uSync and umbraco events need to be unsubscribed on termination. See https://github.com/umbraco/Umbraco-CMS/pull/8815 

**To Reproduce**
1. Terminate Umbraco

**Expected behavior**
Umbraco events unregistered on termination.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Umbraco Version: 8.8
 - uSync Version: 8.7.1
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] N/A

**Additional context**
https://github.com/umbraco/Umbraco-CMS/pull/8815

**Comment by KevinJump** [comment]
thanks, good spot we will build that into the next release.

**Comment by KevinJump** [comment]
will be part of release v8.8.0 (change info #f217f6)
