### ISSUE TITLE
Can not load Umbraco UI after installing uSync

### ISSUE THREAD

**Issue by itsaigon05** [KevinJump/uSync8#183]
**Describe the bug**
The Umbraco UI can not load UI after i installed uSync, uSync.ContentEdition and uSync.Complete via Web UI

**To Reproduce**

**Expected behavior**

**Screenshots**
[log25Oct.txt](https://github.com/KevinJump/uSync8/files/5437993/log25Oct.txt)
<img width="1420" alt="Screen Shot 2020-10-25 at 22 14 47" src="https://user-images.githubusercontent.com/45815884/97156965-07f04c80-17aa-11eb-9914-3a3dd686a90b.png">

**Desktop (please complete the following information):**
 - Umbraco Version: 8.
 - uSync Version: 8.7.2
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari]: Chrome

**Additional context**
Here is a part of log generated: 
{"@t":"2020-10-25T05:52:41.0145338Z","@mt":"{FailMessage} ({Duration}ms) [Timing {TimingId}]","@l":"Error","@x":"Umbraco.Core.Exceptions.BootFailedException: Boot failed. ---> System.Reflection.ReflectionTypeLoadException: Could not load all types from \"uSync8.ContentEdition, Version=8.7.2.0, Culture=neutral, PublicKeyToken=null\" due to LoaderExceptions, skipping:\r\n. System.TypeLoadException on uSync8.Core.Tracking.ISyncNodeTracker`1: Could not load type 'uSync8.Core.Tracking.ISyncNodeTracker`1' from assembly 'uSync8.Core, Version=8.7.1.0, Culture=neutral, PublicKeyToken=null'.\r\n. System.TypeLoadException on uSync8.Core.Tracking.ISyncNodeTracker`1: Could not load type 'uSync8.Core.Tracking.ISyncNodeTracker`1' from assembly 'uSync8.Core, Version=8.7.1.0, Culture=neutral, PublicKeyToken=null'.\r\n. System.TypeLoadException on uSync8.Core.Tracking.ISyncNodeTracker`1: Could not load type 'uSync8.Core.Tracking.ISyncNodeTracker`1' from assembly 'uSync8.Core, Version=8.7.1.0, Culture=neutral, PublicKeyToken=null'.\r\n. System.TypeLoadException on uSync8.Core.Tracking.ISyncNodeTracker`1: Could not load type 'uSync8.Core.Tracking.ISyncNodeTracker`1' from assembly 'uSync8.Core, Version=8.7.1.0, Culture=neutral, PublicKeyToken=null'.\r\n. System.TypeLoadException on uSync8.Core.Tracking.ISyncNodeTracker`1: Could not load type 'uSync8.Core.Tracking.ISyncNodeTracker`1' from assembly 'uSync8.Core, Version=8.7.1.0, Culture=neutral, PublicKeyToken=null'.\r\n. System.TypeLoadException on uSync8.Core.Serialization.ISyncNodeSerializer`1: Could not load type 'uSync8.Core.Serialization.ISyncNodeSerializer`1' from assembly 'uSync8.Core, Version=8.7.1.0, Culture=neutral, PublicKeyToken=null'.\r\n. System.TypeLoadException on uSync8.Core.Serialization.ISyncNodeSerializer`1: Could not load type 'uSync8.Core.Serialization.ISyncNodeSerializer`1' from assembly 'uSync8.Core, Version=8.7.1.0, Culture=neutral, PublicKeyToken=null'.\r\n. System.TypeLoadException on uSync8.Core.Serialization.ISyncNodeSerializer`1: Could not load type 'uSync8.Core.Serialization.ISyncNodeSerializer`1' from assembly 'uSync8.Core, Version=8.7.1.0, Culture=neutral, PublicKeyToken=null'.\r\n. System.TypeLoadException on uSync8.Core.Serialization.ISyncNodeSerializer`1: Could not load type 'uSync8.Core.Serialization.ISyncNodeSerializer`1' from assembly 'uSync8.Core, Version=8.7.1.0, Culture=neutral, PublicKeyToken=null'.\r\n. System.TypeLoadException on uSync8.Core.Serialization.ISyncNodeSerializer`1: Could not load type 'uSync8.Core.Serialization.ISyncNodeSerializer`1' from assembly 'uSync8.Core, Version=8.7.1.0, Culture=neutral, PublicKeyToken=null'.\r\n. System.TypeLoadException on uSync8.Core.Serialization.ISyncNodeSerializer`1: Could not load type 'uSync8.Core.Serialization.ISyncNodeSerializer`1' from assembly 'uSync8.Core, Version=8.7.1.0, Culture=neutral, PublicKeyToken=null'.\r\n\r\n   at Umbraco.Core.Composing.TypeFinder.GetTypesWithFormattedException(Assembly a) in D:\\a\\1\\s\\src\\Umbraco.Core\\Composing\\TypeFinder.cs:line 572\r\n   at Umbraco.Core.Composing.TypeFinder.GetClassesWithBaseType(Type baseType, IEnumerable`1 assemblies, Boolean onlyConcreteClasses, Func`2 additionalFilter) in D:\\a\\1\\s\\src\\Umbraco.Core\\Composing\\TypeFinder.cs:line 504\r\n   at Umbraco.Core.Composing.TypeLoader.<>c__DisplayClass50_0`1.<GetTypes>b__1() in D:\\a\\1\\s\\src\\Umbraco.Core\\Composing\\TypeLoader.cs:line 542\r\n   at Umbraco.Core.Composing.TypeLoader.GetTypesInternalLocked(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache) in D:\\a\\1\\s\\src\\Umbraco.Core\\Composing\\TypeLoader.cs:line 752\r\n   at Umbraco.Core.Composing.TypeLoader.GetTypesInternal(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache) in D:\\a\\1\\s\\src\\Umbraco.Core\\Composing\\TypeLoader.cs:line 656\r\n   at Umbraco.Core.Composing.TypeLoader.GetTypes[T](Boolean cache, IEnumerable`1 specificAssemblies) in D:\\a\\1\\s\\src\\Umbraco.Core\\Composing\\TypeLoader.cs:line 540\r\n   at Umbraco.Core.Runtime.CoreRuntime.ResolveComposerTypes(TypeLoader typeLoader) in D:\\a\\1\\s\\src\\Umbraco.Core\\Runtime\\CoreRuntime.cs:line 275\r\n   at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer) in D:\\a\\1\\s\\src\\Umbraco.Core\\Runtime\\CoreRuntime.cs:line 149\r\n   --- End of inner exception stack trace ---","FailMessage":"Boot failed.","Duration":675,"TimingId":"9465700","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":12576,"ProcessName":"w3wp","ThreadId":13,"AppDomainId":3,"AppDomainAppId":"LMW3SVC1893054354ROOT","MachineName":"RD0050F2038BAE","Log4NetLevel":"ERROR","HttpRequestNumber":1,"HttpRequestId":"35ba7895-37f1-43cb-83f9-f09ea482f4e9"}

**Comment by KevinJump** [comment]
:( guessing its a version thing, uSync.ContentEdition 8.7.2 should require uSync 8.7.2 - I will check the packages are correctly upto date.

**Comment by KevinJump** [comment]
yeah this is because uSync.Complete package actually contains a version of uSync and uSync.ContentEdtion - so you don't actually have to install the other two packages to use uSync.Complete - however that package currenctly have uSync 8.7.1 in it, so if you install uSync.Complete and then uSync.ContentEdition you get this error.

**ToDo:**
- [ ] We need to be more explicit about how these packages interact.
- [ ] We need to update the uSync.Complete package to latest uSync version to avoid confusion

**Comment by itsaigon05** [comment]
Thanks a lot for your comment, it's really clear for me.
