### ISSUE TITLE
Error-prone code for Umb v8.9 detected

### ISSUE THREAD

**Issue by JoseMarcenaro** [KevinJump/uSync8#187]
Hi Kevin
This is not an actual bug report - yet - but it could be "a bug waiting to happen"

Looking for some weird behaviors in our own Umbraco backoffice code after migrating to Umbraco v8.9.x == Angular 1.8 we found out that **self-closing angular directives** are not processed correctly when certain conditions are met - i.e. sibling directives.
This is by design, to prevent a certain type of code injection - more info [here](https://docs.angularjs.org/guide/migration#migrating-from-1-7-to-1-8).

When fixing all those self-closing directives in our code, I found two instances on yours. These are the offending directives with the suggested fix:
![image](https://user-images.githubusercontent.com/923289/98855048-2b69f700-243a-11eb-8d98-38b7afea5216.png)

Hope it helps. Thanks again for your great tool.

**Comment by KevinJump** [comment]
will be done in next release.
