### ISSUE TITLE
Dictionary Items not nesting properly on import

### ISSUE THREAD

**Issue by garpunkal** [KevinJump/uSync8#188]
**Describe the bug**
If you use a nested dictionary structure, such as: 

checkout
--- checkout.address1
--- checkout.address2
--- checkout.deliveryAddress1

address 1 and address 2 aren't nested under checkout after import. 
I believe this is because the parent node (checkout) isn't created yet. 

**To Reproduce**
Above

**Expected behavior**
All parent nodes should be (no <Parent> under <Info>) should be created first, so nested content has a chance to be imported under the right parent. 

**Screenshots**

**Desktop (please complete the following information):**
 - Umbraco Version: 8.9.1
 - uSync Version: 8.7.2.0
 - OS: [e.g. iOS]  Windows 10 
 - Browser [e.g. chrome, safari] Chrome (latest)

**Additional context**

**Comment by KevinJump** [comment]
Hi, 

Can you just confirm that on a second import the structure fixes itself (that would prove is was the missing parent). 

Kevin

**Comment by garpunkal** [comment]
That solves it, thanks

**Comment by KevinJump** [comment]
Hi, opening as we will still fix, it it should do it on first pass
