### ISSUE TITLE
Weird difference report being displayed with unhelpful information

### ISSUE THREAD

**Issue by NikRimington** [KevinJump/uSync8#189]
Hi Kevin,

When looking at a report of a change in a Content Type, the field that relates to Sort is displaying as follows:

![image](https://user-images.githubusercontent.com/13313745/99801200-89c76180-2b2d-11eb-9524-8f83b35d00f1.png)

As you can see this doesn't share any useful information about the difference.

Running:

*  uSync: v8.7.2.0
* Umbraco: v8.9.0

**Comment by KevinJump** [comment]
You know this has come up before, but i can never get to it :( - I will take another look and see if i can reproduce.

**Comment by NikRimington** [comment]
If I had more steps to help reproduce I would :-) I don't really understand it, but I've also not looked at how the report is generated. It is odd though

**Comment by KevinJump** [comment]
I think i've found it. - will be in next release.
