### ISSUE TITLE
Unclear when part of an import fails

### ISSUE THREAD

**Issue by NikRimington** [KevinJump/uSync8#194]
When performing an import that includes "templates" that have a missing cshtml file, the resulting report still looks like it was successful.

![image](https://user-images.githubusercontent.com/13313745/103531750-de2a6480-4e81-11eb-8fab-d235fae6e865.png)

It would be great if the template entry had a red cross against it, and the associated content type had a yellow exclamation against it to indicate that there was a problem with part of the import as it doesn't actually set the template correctly in this situation.

**Comment by KevinJump** [comment]
yep - needed some more styles. 

![image](https://user-images.githubusercontent.com/431231/104010636-b9493080-51a4-11eb-9054-c0e89da0acd4.png)
