### ISSUE TITLE
Method not found: 'Void uSync8.Core.ChangeListExtensions.AddUpdate

### ISSUE THREAD

**Issue by AaronSadlerUK** [KevinJump/uSync8#197]
Umbraco: 8.10.1
uSync: 8.8.1
uSync Content Editon: 8.8.1
uSync Core: 8.8.2

I have exported from my local, and then when I try to run the import on my staging site I get the below error:

```
Import Fail: Method not found: 'Void uSync8.Core.ChangeListExtensions.AddUpdate(System.Collections.Generic.List`1<uSync8.Core.Models.uSyncChange>, System.String, !!0, !!0, System.String)'.
```

**Comment by KevinJump** [comment]
Hi uSync.Core 8.8.2 was released a bit early. (it got delisted almost right away, so you must have just caught it. i would try downgrading core to 8.8.1 - and see if that fixes it.

**Comment by AaronSadlerUK** [comment]
Thanks for that @KevinJump 

I will give it a try later and let you know how I get on!

**Comment by AaronSadlerUK** [comment]
@KevinJump One of these must have updated it as a dependency...

![image](https://user-images.githubusercontent.com/9937803/105220186-4601d000-5b4f-11eb-8aed-0465750614ce.png)

**Comment by AaronSadlerUK** [comment]
I can also confirm that 8.8.1 of uSync.Core solved it.

I'll leave this open due to the 2 dependencies above showing the broken 8.8.2 release

**Comment by KevinJump** [comment]
closing as v8.8.3 release fixed this
