### ISSUE TITLE
UI based compare and sync (similar to Sql Server tools in Visual Studio)

### ISSUE THREAD

**Issue by BenFidge** [KevinJump/uSync8#2]
I'd love it if the uSync UI was similar to the Sql Server comparison tools built into Visual Studio:

- Side by side comparison of local, staging or production instances
- Ability to visually select which items to port between the two instances, rather than manually deleting xml files from the file-system, then doing all-or-nothing import.
- Content comparison should be more granular so individual fields can be sync'd rather than entire documents

**Comment by KevinJump** [comment]
Yep - 

The core of uSync sort of enables this but there is no connection between instances at the moment, 

I've thought about it for a while - its **just** a case of getting a nice secure connection setup and then sending the usync files over the wire for comparison 

we'll plop that onto the feature list :) 

_*top use of the word Just there_

**Comment by KevinJump** [comment]
uSync.Complete (https://jumoo.co.uk/complete) does connect servers, does all the comparison stuff and lets you push and pull between installations.
