### ISSUE TITLE
Content type compositions are not imported

### ISSUE THREAD

**Issue by Phil-Ouimet** [KevinJump/uSync8#20]
**Describe the bug**
A content type composed of multiple aggregations is imported without its components.

**To Reproduce**
1. Create base document types for navigation, SEO, etc..
2. Create a new document type that is composed of the base document types. Example: home page type.
3. Notice that usync exported files contains the the right composition structure.
4. Import all on another machine and notice that the base document types have been created, the Home page type document type has been created but its composition is empty. 

**Expected behavior**
The import would correctly assign the composition to the Home page document type.

**Comment by KevinJump** [comment]
yeah - we broke this when we built the batch item save functionality - the second pass (which is the one that puts the compositions in) doesn't get saved properly. - looking into this.

**Comment by KevinJump** [comment]
Fixed this with a new beta6 release because this broke a couple of things, so needs to be pushed.
