### ISSUE TITLE
Second Pass Doctypes fail

### ISSUE THREAD

**Issue by afinn-tech** [KevinJump/uSync8#202]
Umbraco 8.6.4
Usync 8.7.2

Any way to stop the second pass on import , it fails every time ? 
thanks

**Comment by KevinJump** [comment]
Hi, 

the second imports are required - different things are imported on the second pass (e.g links between content items/content types that might not have been there on the first pass. 

what error are you seeing ? is there anythig in the logs ? 

also if you can - upgrading to the latest version of uSync (8.8.3 - it will still work on Umbraco 8.6.4)  might help as you will get all fixes/updates (

**Comment by KevinJump** [comment]
Hi,

We are just cleaning up old, issues, i hope this was something that has either been fixed for you or not happened again. 
if this is still an issue, then feel free to drop in a comment and we will look at re-opening the issue. 

♾️
