### ISSUE TITLE
Appearance not getting synced

### ISSUE THREAD

**Issue by ane-dwarf** [KevinJump/uSync8#207]
**Describe the bug**
Setting the "Label above (full-width)" property to true does not get synced.

**To Reproduce**
1. Create new document type
2. _Add group_
3. _Add property_
4. Set "Label above (full-width)" to **true**
5. Check the config file of the newly created document type

**Expected behavior**
I would expect the value of the property to be a part of the synced content.

**Screenshots**
![image](https://user-images.githubusercontent.com/37106288/109987793-3907fd00-7d07-11eb-989b-f6923cb2dad4.png)

**About your Site (please complete the following information):**
 - Umbraco Version: 8.10.1
 - uSync Version: 8.8.1
 - uSync.ContentEdition Version: 8.8.1

**Comment by KevinJump** [comment]
Hi @paulwoodland  fixed this yesterday in a PR #206 

we just haven't had the time to wrap it up into a new release yet.
