### ISSUE TITLE
LabelOnTop not syncing in 8.8.4

### ISSUE THREAD

**Issue by paulwoodland** [KevinJump/uSync8#209]
Tested that the LabelOnTop property for property types is not syncing still in 8.8.4 as the fix was removed from the codebase.

Issue was originally fixed here:
https://github.com/KevinJump/uSync8/pull/206

But the fix was removed a couple of days later. I commented at the time on the pull request (link above) to indicate this, but not sure if it's been seen, so opening a new issue for it.

**Comment by KevinJump** [comment]
OK i will take a look, i thought we had changed the other end (so its still lower case in the xml but we now check for it) - but i probably did it wrong :(

**Comment by paulwoodland** [comment]
I think it was just the wrong end of the stick as to what the problem was - it wasn't an issue of the case difference in the XML file, it was an issue of the case difference in the .Net property name when doing reflection

**Comment by KevinJump** [comment]
yes - i see my mistake now. 🤦 - i thought it was the xml case i was changing  - my bad.  
I will put that change back in,

**Comment by paulwoodland** [comment]
Thanks :)

**Comment by KevinJump** [comment]
release 8.8.5 - is done .
