### ISSUE TITLE
Media deserialization fails because of unknown type

### ISSUE THREAD

**Issue by Phil-Ouimet** [KevinJump/uSync8#21]
**Describe the bug**
When importing media content usync content an error is reported for images. 

**To Reproduce**
1. Create an image content in media library
2. Notice on save that media file has been created under the import folder
3. Try to import the media on another workstation
4. Notice that it fails with an error mentioning that the _Media type cannot be found_

**Expected behavior**
Any type of media should be importable

**Additional context**
Looking at the serialized media format it seems that the root node of a media content is always
<Media> and that the media deserializer assumes that it will find the actual type would be _Image_ or _Folder_, etc...
I did a quick successful test to import media images replacing the root node <Media> with <Image>.
As a workaround for now since we are early in development we'll use this workaround to allow us to import medias.

**Comment by KevinJump** [comment]
Hi, please check this against the very latest beta of content edition beta5b, this had a fix for the media extract being wrong. 

https://www.nuget.org/packages/uSync.ContentEdition/8.0.0-beta5b

**Comment by KevinJump** [comment]
fixed (in beta5b - but also released now properly in beta6)
