### ISSUE TITLE
[BUG] uSync throws Object reference not set to an instance of an object. [Umbraco.UplaodFile]

### ISSUE THREAD

**Issue by DresBaumann** [KevinJump/uSync8#219]
uSync throws Object reference not set to an instance of an object. 
![image](https://user-images.githubusercontent.com/32330998/114509938-644f0780-9c36-11eb-9f10-f9b2d36e07ec.png)

when syncing Media with empty Umbraco.UploadField.

We set the field with the name UmbracoFile with the datataype UploadField to not mandatory but when syncing, it throws an error.

uSync 8
v8.8.5.0 + Content Edition (v8.8.5.0), Snapshots (v8.9.3.0), Exporter (v8.9.3.0), PeopleEdition (v8.9.3.0), Publisher (v8.9.3.0), Complete (v8.9.3.0)

**To Reproduce**

Create a Mediatype with the field Umbraco.UploadFile (not mandatory) and some other fields.
In Media create an object with this Mediatype.

Populate the other fields but not the Umbraco.UplaodFile, try to publish it to another environment.

**Expected behavior**
The Sync should work without any issues

**About your Site (please complete the following information):**
 - Umbraco Version: 8.10.1
 - uSync Version:  v8.8.5.0 + Content Edition (v8.8.5.0), Snapshots (v8.9.3.0), Exporter (v8.9.3.0), PeopleEdition (v8.9.3.0), Publisher (v8.9.3.0), Complete (v8.9.3.0)
 - Browser: Chrome

**Additional context**
A Workarround would be to populate this field everytime but this is not an option for our customer.
Do you know this Issue / or an Workaround. 

Thanks

**Comment by KevinJump** [comment]
Hi, Not been reported before but  I will take a look today.

**Comment by DresBaumann** [comment]
Thanks for having a look at it!

**Comment by KevinJump** [comment]
Hi, 
this is fixed in uSync.Complete release 8.9.4 which we have just pushed out.

https://github.com/Jumoo/uSync.Complete.Issues/releases/tag/8.9.4
