### ISSUE TITLE
v9 - sample appsettings.json

### ISSUE THREAD

**Issue by JoseMarcenaro** [KevinJump/uSync8#224]
Hi Kevin
Just tried the 9.0.0-beta1 and it works! Amazing! You rule!
I'm up and running with all my doctypes -brought from my v8 website - on a brand new Umbraco beta 9 installation.
Note: "up and running" means they are there, with all their fields and stuff. A huge step forward! 
I wish we had that when migrating from 7 to 8...

Just one question about tweaking the configuration using a json file.
Can you provide a sample? The default settings are not explicitly defined (yeah, zero configuration, I know) but I would like to disable the Flat structure and I don't know how / where to add the uSync config block.
Thanks again! Great work!

**Comment by KevinJump** [comment]
indeed. zero config is great until its not 🙂 

we do have an outline of the structure here https://docs.jumoo.co.uk/uSync/v9/settings/

for what you want (not flat) this should be the bit to do it, 

```
"uSync" : {
    "Sets" : { 
         "default" : {
             "HandlerDefaults" : {
                 "UseFlatStructure": false 
              }
         }
    }
}
```

at the moment i think you need to restart the site for uSync to pick this up, we haven't quite got all of the settings reload code in all the right places just yet.

**Comment by JoseMarcenaro** [comment]
Yes! that worked .  Thanks!
