### ISSUE TITLE
uSync version reporting as 8.7.1 inside Umbraco instance's package installer

### ISSUE THREAD

**Issue by trevor-ratliff** [KevinJump/uSync8#229]
**uSync Version Reporting as 8.7.1**
When viewing the uSync package page from the package manager inside an Umbraco instance the latest version says 8.9.1, but when you click the install package button Umbraco shows and installs the 8.7.1 package version.  

**To Reproduce**
1. open an instance of Umbraco
2. navigate to the packages page
3. find the uSync package "button" and click it
4. click the "install" button
5. observe the version reported on the install page

**Expected behavior**
I would expect this to show the latest version

**About your Site (please complete the following information):**
 - Umbraco Version: 8.6.1
 - uSync: Version: 8.7.1
 - Browser [e.g. chrome, safari]: chrome

**Additional context**
I tried emptying the cache and hard reloading the page several times in different places, I still got the wrong version when trying to install.

**Comment by KevinJump** [comment]
that is really odd, it might be an our.umbraco.org thing.

When I've just tried it, it installed 8.9.1 on both the latest version of Umbraco and v8.6.1 -
