### ISSUE TITLE
Casing inconsistency causing trouble

### ISSUE THREAD

**Issue by MortenL** [KevinJump/uSync8#23]
Hi,

In the latest version, on line 38 of uSyncDashboardController the current code expects result.data.addOnString, but result.data contains AddOnString - which is causing a good deal of errors in console.

**Comment by KevinJump** [comment]
:( sadness

**Comment by KevinJump** [comment]
Hi 

can you check the version you have installed? - the release version of the controller is expecting this in uppercase, and that is how its getting returned - you might still be running RC? (or client dependency might be caching something) 

https://github.com/KevinJump/uSync8/blob/master/uSync8.BackOffice/App_Plugins/uSync8/backoffice/uSync8/uSyncDashboardController.js#L39

**Comment by MortenL** [comment]
Think I've tried clearing everything, but I'll give it another go.

**Comment by MortenL** [comment]
Did a complete uninstall, removed cache, recycled the app pool and all that jazz - this is the output I get from /umbraco/backoffice/uSync/uSyncDashboardApi/GetAddOns

`{
  "addOnString": "Content Edition",
  "addOns": [
    {
      "name": "Content Edition",
      "version": "8.0.0",
      "view": "",
      "icon": "icon-globe",
      "alias": "Content",
      "displayName": "Content",
      "sortOrder": 10
    }
  ]
}`

**Comment by MortenL** [comment]
FIle build version is 8.0.0.129

**Comment by KevinJump** [comment]
Ahh,

I think you have the JsonCaseConverter somewhere else on your project,  i've seen this with other things-  the workaround for us is to force the case of our serialization, but there is also something you can do to make sure the conversion of cases only happens on your projects not imported ones. 

i will see what i can find

**Comment by MortenL** [comment]
That we do! Nicely spotted Sir. I'd love if you could find a way around this issue.

**Comment by KevinJump** [comment]
Hi, 

From our side we need to go through the code we have and make sure we are specifying the formatting of our classes, we are doing that by adding  
```
[JsonObject(NamingStrategyType = typeof(DefaultNamingStrategy))]
``` 
to our models. 

so that might be something you want to do in place of a global setting, or if you want to force the casing on an ApiController you can do something like this https://gist.github.com/shizik/5712399 - which lets you put it on an attribute.

**Comment by MortenL** [comment]
Thanks Kevin, I'll give that attribute shot.

**Comment by KevinJump** [comment]
Forcing case on our side will be in next release
