### ISSUE TITLE
Umb9 beta fails to build after uSync installed

### ISSUE THREAD

**Issue by craigs100** [KevinJump/uSync8#230]
**Describe the bug**
Umb9 beta fails to build after uSync 9 installed. Linux Mint.

**To Reproduce**
1. Install Umb V9 beta to the point it's back office is running.
2. Install uSync 9 via Nuget
3. Attempt to build solution

**Expected behaviour**
A successful build

**Actual behaviour**
IDE Error message:   Microsoft.Common.CurrentVersion.targets(3136, 5): [MSB3552] Resource file "**/*.resx" cannot be found.

**About your Site (please complete the following information):**
 - Umbraco Version: 9 Beta
 - Site empty, i.e. installed uSync on an empty Umbraco install
 - uSync: 9
 - Browser: Brave
 - IDE: Rider 2021.1.2

**Additional context**
- OS: Linux Mint 20.1 Cinnamon x64
- DB: Microsoft SQL Server for Linux

**Comment by KevinJump** [comment]
Hi, 

We don't do any *.resx stuff :( 

there are issues with folder paths for uSync on linux so you could try the nightly build https://github.com/KevinJump/uSync8/issues/227

but i am not sure that will fix an issue with the build step. :( 

have you tired a dotnet build within the website folder to see if that is working ?

**Comment by KevinJump** [comment]
Hi,

We are just cleaning up old, issues, i hope this was something that has either been fixed for you or not happened again. 
if this is still an issue, then feel free to drop in a comment and we will look at re-opening the issue. 

♾️
