### ISSUE TITLE
v9 - DisabledHandlers setting is ignored?

### ISSUE THREAD

**Issue by JoseMarcenaro** [KevinJump/uSync8#231]
I'm trying to disable the "contentHandler" and "mediaHandler" to emulate the v8 behavior (without uSync.Content)
Based on this documentation https://docs.jumoo.co.uk/uSync/v9/settings/ I've added those handlers aliases in the DisbledHandlers array, but it looks like they are not properly read by the Configuration getter

![image](https://user-images.githubusercontent.com/923289/116929838-57ba3f80-ac35-11eb-9ae8-c60d9e114a96.png)

Note that the other setting (HandlerDefaults.UseFlatStructure) is properly read and used.

Am I doing something wrong?
Thanks in advance

**Comment by JoseMarcenaro** [comment]
I've found it!
It looks like .Net core appSettings loader is not so great at deserializing lists - in fact, that wasn't working at all some time ago.

The way to make it work is to type the property as an array:

![image](https://user-images.githubusercontent.com/923289/116933403-e4ff9300-ac39-11eb-95ca-1a0f4dda55e1.png)

And that reads the two strings into the DisabledHandlers array.
@KevinJump let me know if you want me to send a PR for this or you just fix it. Thx.

**Comment by KevinJump** [comment]
thanks - fixed it - we are going to try and find easier way to turn content/on  off.  maybe something that turns the groups on/off might do it.

**Comment by chris-evansnz** [comment]
thanks @JoseMarcenaro and @KevinJump I was looking for this exact config to turn off content and media handlers - am currently using beta001

Is beta002 released or will we need to run a nightly build to get this feature? where do we find the nightlies?

**Comment by KevinJump** [comment]
Hi, 

we didn't really have a set timeline for beta002 - other than matching what ever Umbraco's release schedule is - we might release something pre-codegarden (but i expect Umbraco will too) 

but the nightlies are on this feed: 
```
dotnet nuget add source https://pkgs.dev.azure.com/jumoo/Public/_packaging/nightly/nuget/v3/index.json
```

for handler disabling you might also want to checkout the changes to `ExportOnSave `setting in the nightly 
https://github.com/KevinJump/uSync8/issues/232

this means you can 'just' turn off content/media saving by setting the `ExportOnSave `setting to 'Settings'  and while the handlers will still be there is you want to export from the back office saving/editing content will not write anything to disk.

**Comment by chris-evansnz** [comment]
Thanks for the info! 👍
