### ISSUE TITLE
Console error on loading uSyncController.js

### ISSUE THREAD

**Issue by daljitkaur9** [KevinJump/uSync8#235]
Hi, 
I upgraded the usync version to the latest, i.e. 8.9.1, and the dashboard fails to load due to console error:
Uncaught SyntaxError: Unexpected token ? : notificationsService.error('Error', error.data.ExceptionMessage ?? error.data.exceptionMessage);
This line occurs thrice.

For now i have modified it, by using ternary operator on my local.
Can you please verify if it has anything to do with my js version incompatibility.

**Comment by daljitkaur9** [comment]
Okay guys !! I got it.
I am using chrome version 74. 
So its mainly browser issue, May be latest version changes are not old version compatible. 
It is working fine in latest version of chrome.

**Comment by KevinJump** [comment]
as we are now on chrome v91 - i might close this.
