### ISSUE TITLE
Media from Umbraco 7.5.4 not compatible with uSync 8.0.0

### ISSUE THREAD

**Issue by Haugst3d** [KevinJump/uSync8#24]
I'm migrating from Umbraco 7.5.4 to 8.0.2. And is using uSync for the media and content. At first I was simply doing it wrong, placing media at incorrect locations etc. But I now believe/hope I am no longer the problem :)

I have already downloaded the source for uSync 8, included the projects as project references instead of the ones from the NuGet package and stepped my way through the content import process.

The import fails in ContentSerializerBase.cs when calling IsValid(XElement node). The node needs a key, alias and info element, and my nodes have neither. My config files look like this:

`<?xml version="1.0" encoding="utf-8"?>
<Image guid="6e7b4a60-1018-445a-84ae-e09d1a530732" id="5829" nodeName="an-logo_footer.png" isDoc="" updated="2018-12-07T14:32:55.9130000Z" parentGUID="6bab069e-4251-4714-a879-2fb09518a019" nodeTypeAlias="Image" path="-1,5816,5829">
  <alt></alt>
  <umbracoBytes><![CDATA[5016]]></umbracoBytes>
  <umbracoExtension><![CDATA[png]]></umbracoExtension>
  <umbracoFile><![CDATA[{src: '/media/3560/an-logo_footer.png', crops: [
  {
    "alias": "testimonial",
    "width": 65,
    "height": 65
  },
  {
    "alias": "Huge Image Banner",
    "width": 577,
    "height": 590
  },
  {
    "alias": "Page Header",
    "width": 1600,
    "height": 260
  }
]}]]></umbracoFile>
  <umbracoHeight><![CDATA[49]]></umbracoHeight>
  <umbracoWidth><![CDATA[150]]></umbracoWidth>
</Image>`

The GetKey method returns empty guid as string, GetAlias() returns empty string and the Info element is null (because it doesnt exist)

Is there a special way to import older media items, or is this a bug?

**Comment by KevinJump** [comment]
The files are not compatable as the data structures underneath in umbraco have changed a little bit, you can do manual conversion of files, but we waiting to see what the Umbraco Migration tool does before doing anything like this with uSync
