### ISSUE TITLE
The ISyncMapper interface doesn't facilitate selectively mapping property editors....

### ISSUE THREAD

**Issue by tompipe** [KevinJump/uSync8#241]
Due to some wackiness involving an external API, I am in a situation whereby I thought a custom ISyncMapper would be the solution to update some saved values, as the content moves through environments. However, the property editor is the awesome DataList editor from Contentment, which of course, has various combinations of configuration.

As far as I can tell, the ISyncMapper export/import process only receives the value and the editorAlias, in this case its a long, representing the ID of an item on the external API, and the string Umbraco.Community.Contentment.DataList. 

I was hoping to be able to determine the config of each editor, as the export processes, and if the Contentment editor's DataListSource is the type for the custom API item picker, then, and only then, process the value for export (similarily when importing at the destination). Not possible without the PropertyType and its config, and that can't be fetched having only the editorAlias and the property value.

I can see within the usync source, that the ContentSerializerBase GetExportValue which calls the mappers, has the full PropertyType, but only passes through the editorAlias to the mappers. I guess another interface/method would be useful to allow this kind of detailed selective mapping.

@KevinJump if you have any suggestions on a workaround/another approach, that would be helpful, I'm thinking the best option is probably the ExportingItem events right?

Cheers

**Comment by KevinJump** [comment]
Hi,

thinking out loud at possible things we could do. 

yeah so i haven't looked at the contentment stuff in depth - my first thought it we could add a second pass to the mappers, where we append something to the editor Alias name. (e.g the property alias).

e.g. Umbraco.Community.Contentment.DataList_myList" 

This would have the benefit of not needing a new interface, and not breaking any existing code (that would look for mappers that are just editorAllias).  However this is very implimentation specific then, you would have to have the aliases in your code for the match to work. 🤔 

Or A new Interface  :
Ideally We don't want to go back to the datatype for each property - because that would be an extra DB call for every property in a content item, and might slow us down a bit. So if we where to look at passing something new - then it would probibly have to include the contentType Alias, and the property alias, so you could do the lookup inside your value mapper ?

**Comment by KevinJump** [comment]
https://github.com/KevinJump/uSync8/commit/023de78f30bcf30f5b444bdeba33ab786b3cb48a

**Comment by tompipe** [comment]
Hey @KevinJump thanks so much for the update, it's exactly what was needed, I've made a custom build of usync, and added only the content edition nupkg to the solution, and have now been able to conditionally amend the export value using the new ISyncMapperExtended interface :smiley: :beers:

However, when importing, the GetImportValue method isn't being hit. On further analysis, it seems that because this particular doctype and hence PropertyType is being used within a BlockEditor, the BlockListMapper is handling the GetExportValue, but doesn't seem to handle the GetImportValue call, rather the default implementation in the SyncValueMapperBase is used, and returns the unmodified value - I'm guessing only the block's Json value.

I guess something similar to the GridMapper is needed, i.e working through the block's JSON value, and then calling the appropriate mapper for each property. Unless you have any other ideas?

Cheers

**Comment by KevinJump** [comment]
yeah :( - the default mappers don't really  do the import because they are mainly there to make sure the date format in child items is always the right one .

The mappers can be chained, so you could write your own block mapper that impliments GetImportValue down, and add it to the solution without having a custom build. (we've just release the interface stuff in release v8.9.2)

but i will look at writing the GetImportValue method in to the mappers for the next release.

**Comment by tompipe** [comment]
Hey @KevinJump, thanks for the quick reply. 8.9.2 must have crossed over with me adding the custom build, was hoping it would be released soon, ha ha.

As for your suggestion to chain a mapper, spot on. I've done the following based on the built in mappers, and it's now firing the GetImportValue on my other custom mapper, sending in the correct property value. Thanks so much for your help

```C#
    public class CustomBlockListMapper : BlockListMapper, ISyncMapperExtended
    {
        private const string DocTypeKeyAlias = "contentTypeKey";
        private readonly string[] _contentBlocks = new []
        {
            "contentData",
            "settingsData"
        };

        public CustomBlockListMapper(IEntityService entityService, IContentTypeService contentTypeService, IDataTypeService dataTypeService) : base(entityService, contentTypeService, dataTypeService)
        {
        }

        public string GetExportValue(object value, SyncPropertyMapInfo propertyMapInfo) => base.GetExportValue(value, propertyMapInfo.PropertyType.PropertyEditorAlias);
        public IEnumerable<uSyncDependency> GetDependencies(object value, SyncPropertyMapInfo propertyMapInfo, DependencyFlags flags) => base.GetDependencies(value, propertyMapInfo.PropertyType.PropertyEditorAlias, flags);

        public string GetImportValue(string value, SyncPropertyMapInfo propertyMapInfo)
        {
            if (value == null)
                return string.Empty;
            
            var jsonValue = GetJsonValue(value);
            if (jsonValue == null)
                return value;

            foreach (var contentBlock in _contentBlocks)
            {
                if (!jsonValue.ContainsKey(contentBlock))
                    return JsonConvert.SerializeObject(jsonValue, Formatting.Indented);

                var source = jsonValue.Value<JArray>(contentBlock);
                if (source == null)
                    continue;

                foreach (var json in source.Cast<JObject>())
                {
                    var docTypeByKey = GetDocTypeByKey(json, DocTypeKeyAlias);
                    if (docTypeByKey != null)
                        GetImportProperties(json, docTypeByKey);
                }

                return JsonConvert.SerializeObject(jsonValue, Formatting.Indented);
            }

            return value;
        }

        protected JObject GetImportProperties(JObject item, IContentType docType)
        {
            foreach (var compositionPropertyType in docType.CompositionPropertyTypes)
            {
                if (!item.ContainsKey(compositionPropertyType.Alias)) 
                    continue;

                var jToken = item[compositionPropertyType.Alias];
                if (jToken == null) 
                    continue;

                var importValue = SyncValueMapperFactory.GetImportValue(jToken.ToString(), new SyncPropertyMapInfo
                {
                    PropertyType = compositionPropertyType,
                    ContentTypeAlias = docType.Alias
                });
                item[compositionPropertyType.Alias] = importValue.ToString().GetJsonTokenValue();
            }
            return item;
        }
    }
