### ISSUE TITLE
TypeLoadException: Could not load type 'Umbraco.Cms.Core.Events.INotification'

### ISSUE THREAD

**Issue by DavidArmitage** [KevinJump/uSync8#245]
When I install the beta
PM> install-package uSync -version 9.0.0-beta001

My Umbraco 9 solution re-builds fine without errors.
When I run I get the following error.

TypeLoadException: Could not load type 'Umbraco.Cms.Core.Events.INotification' from assembly 'Umbraco.Core, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null'.

I did also notice that when I did a re-build it was complaining a json file was missing

https://www.awesomescreenshot.com/video/4161856?key=07a6a9374d6bd73de9af978bceb95b45

![image](https://user-images.githubusercontent.com/45119620/122351963-dd414700-cf78-11eb-8d40-541d284959fb.png)

![image](https://user-images.githubusercontent.com/45119620/122351614-7e7bcd80-cf78-11eb-8a5b-79312b0bffe5.png)

**Comment by KevinJump** [comment]
fixing in later builds as namespaces changed in beta umbracos - also the json file thing we have renamed the file as .json's dont get copied around by the pre-build tasks.
