### ISSUE TITLE
Possible typo (dashboard.html url) (NetCore)

### ISSUE THREAD

**Issue by nikcio** [KevinJump/uSync8#246]
**Describe the bug**
I was trying out using Umbraco 9 in a Docker container with [Caddy](https://caddyserver.com/) as the webserver and I was in this environment unable to load the dashboard in the Umbraco back office. (404 Not found error)

It turned out to be because Umbraco was trying to load: 

`/App_Plugins/uSync/backoffice/uSync/dashboard.html` 

instead of:

`/App_Plugins/usync/backoffice/usync/dashboard.html` 

which is the actual path.
I couldn't find anywhere the path to the dashboard file was specified so figured it might be a typo somewhere else. (This doesn't affect uSync when running IIS Express from visual studio.)

**System information**
 - Umbraco Version: 9.0.0-beta003
 - uSync Version: 9.0.0-beta003

**Comment by KevinJump** [comment]
thanks, i need to have a full shakedown of case sensitivity, but in this case its the tree alias which umbraco uses to work out the path, so we have lowercased that alias (figuring we will just try to everything lowercase and that should be the best way to us spotting things.
