### ISSUE TITLE
CamelCase from v8 to KebabCase in v9.. import/export cycle produces duplicates?

### ISSUE THREAD

**Issue by mistyn8** [KevinJump/uSync8#248]
uSync 9.0.0-beta003
**Describe the bug**
Migrating v8 datatype to v9-beta400
copied the v8 config into the v9 usync folder..
Noticed that v8 was CamelCase vs KebabCase in v9

So ended up with `AccentColor.config` vs say `approved-color.config` (from a core datatype)
Import processed fine and I ended up with my Accent Color datatype.

However, clean export later on then produces an `accent-color.config`, leaving the `AccentColor.config` too...

Easy enough to manually tidy up, just flagging for finessing migrations.

Excellent package as ever.. and loving the packageManifest.fm

**Comment by KevinJump** [comment]
thanks,. will take a look, internally there are ToSafeFileName methods we use from umbraco. they might have changed - hopefully some options will let us revert back to keep the v8 ones.

**Comment by KevinJump** [comment]
Unfortunatly this is an inconsitancy in uSync 8 :( - some things use SafeAlias, others SafeFileName. 

in a perfect world. i would say lets use safe Filename everywhere, but i suspect this will break more things than it fixes. 
so we might retro fix this so the safe alias things still use safe alias to generate the name in v9 . we will break people running betas but better than breaking people running releases

- DataTypes - SafeAlias
- DocTypes - SafeFileName
- MediaTypes - SafeFileName
- MemberTypes - SafeFileName
- Macros - SafeAlias
- RelationTypes - SafeAlias
- Languages - SafeFileName
- Template - SafeFileName
- Content - SafeFileName
- Media - SafeFileName

**Comment by KevinJump** [comment]
fixed for next release.
