### ISSUE TITLE
Dictionary imports in wrong order (should do parent first), cannot fix when using OneWay

### ISSUE THREAD

**Issue by jvtroyen** [KevinJump/uSync8#251]
**Describe the bug**
When performing a uSync import of Dictionary items, items are (or appear to be) processed in alfabetical order.

Items that start with a or b (before '**c**onfig') end up in the root of the dictionary, instead of in their proper place in the tree structure.

If you do a second import, it fixes itself, because the parent now already exists.
**HOWEVER**, if you use the OneWay setting to only create new items, it skips the existing items and cannot automatically fix the situation.

**To Reproduce**
In our case, the dictionary items are named as follows:

Dictionary
  - feature_1
     - feature_1.aaaa
     - feature_1.bbb
     - feature_1.whatever
  - feature_2
     - ...

If we import on another environment, they are processed in this order:

- feature_1.aaaa.config
- feature_1.bbb.config
- feature_1.config <-- this is the parent
- feature_1.whatever.config

The first 2 items are imported and put in the root of the dictionary as the parent is not found.
The 3rd item is the parent.
The 4th item is properly imported and put under it's parent.

**Expected behavior**
I expect the parents to be imported first.
In our specific case, it would suffice to sort on the name of the file without the .config extension to achieve this, but this will not cover other ppl's naming conventions.

Perhaps the best solution would be to read all files in memory and build the tree structure, then process the files in that order.

**About your Site (please complete the following information):**
 - Umbraco Version: 8.13
 - uSync Version: 8.8.1.0
 - Browser: n/a

**Additional context**

**Comment by jvtroyen** [comment]
Come to think of it, doing a second pass for all the items who couldn't find their parent in the first pass would solve it also, no complex sorting of any kind required.

**Comment by jvtroyen** [comment]
I updated to the latest version (8.9.5) and in doing so discovered the setting "FailOnMissingParent".
It does not seem to apply to dictionary items however. My first 2 items still end up in the root of the Dictionary, even though their parent is missing.

I will dive in the code to see if this is easily remedied.

**Comment by KevinJump** [comment]
The dictionary handler *should* import them in level order - in that it will read all the file,s but it uses the LevelHandlerBase which then sorts them by the 'level' attribute - so again in theory the parent items get imported before the children .

![image](https://user-images.githubusercontent.com/431231/127308213-5a674dc1-2a05-4195-86a5-f3803afe0a91.png)

However there might be caching or timing issues 😕 (so will do some sanity checking to ensure we are not getting cached results from any services)

**Comment by jvtroyen** [comment]
That's good to know. I will verify logging on my end to see how it behaves.

**Comment by jvtroyen** [comment]
I managed to get Verbose logging. It's loading as I suspected.
I verified that the parent (Test) has level 3 and the others have level 4.

I'll look in the code as well, to see where the sorting should be happening.

![image](https://user-images.githubusercontent.com/6861380/127314859-843f6dd9-98c9-4177-9d15-69ccb6f6a746.png)

**Comment by KevinJump** [comment]
It is worth noting - that logging doesn't always come out in the file in the order in which it is logged 🤯  - to be 100% sure i might add a logging line that actually logs the order in one go.

**Comment by KevinJump** [comment]
(your logging appears to be missing the importing [level x] line ? 

![image](https://user-images.githubusercontent.com/431231/127315580-98470351-0387-493b-9632-f4f69a46c958.png)

_but that might be because with no changes that line doesn't get logged ?_

**Comment by KevinJump** [comment]
Hi, 

noticed there is prob a bug. 

if you have FlatStructure = false, then the sorting isn't done by the handler. (because the folers will do it)
however the dictionary handler doesn't save the files in a folder stucture 

so i think i need to fix the `GetItemPath` call in the handler to put the structure in place for non flat files. and that might be your issue

**Comment by jvtroyen** [comment]
I hid Debug lines, just so I could get the Verbose lines on one screen.

Anyway, I think I'm on to something here: when NOT using flat structure, you let the directory-structure be the guide for the levels (in the SyncHandlerLevelBase.ImportFolder).
However, dictionary items are always exported flat instead of hierarchical, so they are imported as a flat list, no calculations.

**Comment by jvtroyen** [comment]
D'oh! :-)

**Comment by KevinJump** [comment]
that should fix that. 🤞

**Comment by jvtroyen** [comment]
If you take my comment into account (reverse line 183), it works perfectly.
Thanks!
