### ISSUE TITLE
Setting global json to newtonsoft uSync 9-rc001 backoffice api calls fail.

### ISSUE THREAD

**Issue by mistyn8** [KevinJump/uSync8#252]
In order to work around .netCore incorrectly serializing `Dictionary<string, object>` I've had to change the global json implementation over to newtonsoft (in order to use dtge allowedDoctypes)
https://github.com/umbraco/Umbraco-CMS/issues/10644
```
services.AddControllers().AddNewtonsoftJson();
```
However, that seems to cause the issue with deserialisation in the uSync 9-rc001 backoffice API calls.. `GetAddOns` I think is the first flagged.

![image](https://user-images.githubusercontent.com/12418214/126619832-e51b18e8-f212-4676-bd5e-a6699960ddf9.png)

![image](https://user-images.githubusercontent.com/12418214/126620093-042b6f50-81fc-4a48-8d67-b47beec5ba5b.png)

**Comment by KevinJump** [comment]
SAD FACE ! 

I was hoping the days of Newtonsoft's CamelCase/DefaultCase where behind us - 

I think we can resolve this with Attributes on the relevant classes, just need to make sure we don't miss any.

**Comment by mistyn8** [comment]
Sorry...

**Comment by KevinJump** [comment]
You can get this in the latest nightly build. (feed https://pkgs.dev.azure.com/jumoo/Public/_packaging/nightly/nuget/v3/index.json)

9.0.0-rc002.20210722.1

I am not sure if we will 'offically' support this however - as i don't know what else it might do - especially to internal Umbraco properties/content. (most of uSync is XML but if the internal properties are json we do read/write them).

**Comment by mistyn8** [comment]
I'm also seeing that if I set...
`"ExportOnSave": true,` in the appsetting.json file.. then it's ignored... and exportOnSave ends up as false?
could that be related?

**Comment by mistyn8** [comment]
Infact copying from the docs.. 
```
"Settings" :{
            "RootFolder" : "/uSync/v9/",
            "DefaultSet" : "default", 
            "ImportAtStartup" : "",
            "ExportAtStartup" : false,
            "ExportOnSave" : true,
            "ReportDebug" : false,
            "AddOnPing" : true,
            "CacheFolderKeys" : true,
            "ShowVersionCheckWarning": false,
            "SignalRoot" : "",
            "EnableHistory" : true,
         },
```
Only setting that ends up as true is EnableHistory? (according to the backoffice) I noticed as saved a dataype with updated settings and then reimport overwrote it.

**Comment by mistyn8** [comment]
@KevinJump  thanks for the quick fix, though it doesn't seem to have worked for me, still having the same issues.

**Comment by KevinJump** [comment]
Hi,

I would clear all the caches, (browser etc) as it might be caching results. 

just to confirm we added this line to test it . 

```
services.AddControllers().AddNewtonsoftJson();
```

**Comment by mistyn8** [comment]
Will check on the cache.. but am normally running in chrome incognito to avoid extensions hijacking things. :-)

I have this in Startup.cs
```
public void ConfigureServices(IServiceCollection services)
        {
            /// todo: revisit once HQ have resolved https://github.com/umbraco/Umbraco-CMS/issues/10644
            /// uSYnc doesn't like it if this is in place. https://github.com/KevinJump/uSync8/issues/252
            services.AddControllers().AddNewtonsoftJson();

            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo { Title = "TSD Umbraco APIs", Version = "v1" });
            });
#pragma warning disable IDE0022 // Use expression body for methods
            services.AddUmbraco(_env, _config)
                .AddBackOffice()
                .AddWebsite()
                .AddComposers()
                .Build();
#pragma warning restore IDE0022 // Use expression body for methods            
        }
```

**Comment by mistyn8** [comment]
Presumably something cache related as it's working now. Sorry for any inconvenience. Thank you kindly.

**Comment by mistyn8** [comment]
@KevinJump  sorry to keep adding to a closed ticket.. but if I delete a docType the process never completes, and uSync doesn't generate its new config file. refreshing the page and Umbraco thinks the doctype is deleted, but uSYnc want to reimport as no change to configs.
I'm guessing this is the unsupported nature of using NewtonSoft :-)

I think I'm going to look into an angular interceptor to only change the apicall I need to get dtge and allowed editors working.
