### ISSUE TITLE
Docs settings some defaults missing, and ExportOnSave default should be all?

### ISSUE THREAD

**Issue by mistyn8** [KevinJump/uSync8#253]
https://docs.jumoo.co.uk/uSync/v9/settings/
```
"Settings" :{
            "RootFolder" : "/uSync/v9/",
            "DefaultSet" : "default", 
            "ImportAtStartup" : "",
            "ExportAtStartup" : false,
            "ExportOnSave" : true,
            "ReportDebug" : false,
            "AddOnPing" : true,
            "CacheFolderKeys" : true,
            "ShowVersionCheckWarning": false,
            "SignalRoot" : "",
            "EnableHistory" : true,
         },
```

Think this should be as below

```
"Settings" :{
            "RootFolder" : "/uSync/v9/",
            "DefaultSet" : "default", 
            "ImportAtStartup" : "",
            "ExportAtStartup" : false,
            "ExportOnSave" : "All",
            "ReportDebug" : false,
            "AddOnPing" : true,
            "RebuildCacheOnCompletion" : false,
            "FailOnMissingParent" : false 
            "CacheFolderKeys" : true,
            "ShowVersionCheckWarning": false,
            "SignalRoot" : "",
            "EnableHistory" : true,
         },
```

https://docs.jumoo.co.uk/uSync/v9/settings/settings/
and then ExportOnSave (can be group name ("settings", "content") or 'all' so everything is done, blank or 'none' == off) rather than true/false in the uSync:Settings list?

Assume "all"  is case insensitive too ;-)
https://github.com/KevinJump/uSync8/blob/0c765666d6f633f3618310133d503d53e929d0eb/uSync.BackOffice/Configuration/uSyncSettings.cs#L31

**Comment by mistyn8** [comment]
Also noticed that umbraco appsetting.json gets intellisence..
![image](https://user-images.githubusercontent.com/12418214/126627428-6c9713d2-1e0c-46fc-ba45-78a3a6762d9a.png)

is that a feature request for uSync Settings?

**Comment by mistyn8** [comment]
One more
https://docs.jumoo.co.uk/uSync/v9/settings/

GuidNames should show default as false?

https://github.com/KevinJump/uSync8/blob/0c765666d6f633f3618310133d503d53e929d0eb/uSync.BackOffice/Configuration/uSyncHandlerSettings.cs#L18

**Comment by KevinJump** [comment]
Thanks i think we took the docs from an earlier version before we tweaked them - I will do a sanity check of them  

the intellisense comes from a schema file inside the umbraco package, but i have been looking to see if there are any ways we can inject a reference to a uSync schema file - its probibly doable via a custom build step 🤷 still looking into it.

**Comment by Matthew-Wise** [comment]
Could just have uSync sit outside of Umbraco instead? Also the Settings UI still refects that these settings are true / false

**Comment by KevinJump** [comment]
> Could just have uSync sit outside of Umbraco instead?

i don't think so :( - Umbraco essentially has a local version of the schema for the whole applicationsettings.json file.  They've done this because there isn't another way to have partial sachems in .net core. - 

we don't want to move uSync config out of the appsettings.json as that is the new settings model and it brings all sorts of advantages such as merging based on environment and environmental variables and key vaults etc. 

we just need to tidy up our end of this a bit - its on the list for this week.
