### ISSUE TITLE
Umbraco 9 - settings see our docs link

### ISSUE THREAD

**Issue by Matthew-Wise** [KevinJump/uSync8#255]
The  link "see our docs" currently opens in the same tab, making this open in a new tab feels like a better experience to me, as I am going to want to remain in the CMS most of the time

**To Reproduce**
Go to the uSync dashboard
Settings
click on see our docs
Page opens in the current tab.

**Expected behavior**
Pages opens in a new tab

**Screenshots**
![image](https://user-images.githubusercontent.com/6782865/126969372-138264ec-9950-4263-8c9e-ef8d16600e71.png)

**About your Site (please complete the following information):**
 - Umbraco Version: 9 RC
 - uSync Version: 9 beta
 - Browser [e.g. chrome, safari] chrome

**Additional context**

**Comment by KevinJump** [comment]
yep - totally agree

**Comment by KevinJump** [comment]
fixed in rc002.
