### ISSUE TITLE
Is there a way to disable menu options based on backoffice config?

### ISSUE THREAD

**Issue by keithlfs** [KevinJump/uSync8#257]
I would like to remove the possibility of content editors / developers from importing content via this menu. I would like to allow only the updating of content types / settings. Is there a way to disable the first and last option?

![image](https://user-images.githubusercontent.com/72756217/127296555-a3e241a5-27f0-4242-82b6-740af6c9cb09.png)

I have set the following options in the backoffice config but they are not reflected here, should it be?

```
<HandlerConfig Name="uSync: ContentHandler" Enabled="false" Actions="Import">
<HandlerConfig Name="uSync: MediaHandler" Enabled="false" Actions="Import">
```

**Comment by KevinJump** [comment]
Hi there are a couple of other handlers that are also in the 'Content/Media' group.

these are the "content/media" handlers

```
<Handler Alias="contentTemplateHandler" Enabled="false" Actions="All" />
<Handler Alias="dictionaryHandler" Enabled="false" Actions="All" />
<Handler Alias="mediaTypeHandler" Enabled="true" Actions="All" />
<Handler Alias="domainHandler" Enabled="false" Actions="All" />
<Handler Alias="contentHandler" Enabled="false" Actions="All" />
<Handler Alias="mediaHandler" Enabled="false" Actions="All" />
<Handler Alias="relationTypeHandler" Enabled="false" Actions="All" />
```

if you consider dictionary items (or any of the others not to be Content/Media you can change the group they belong to 
in the config. 

e.g - make dictionary a "settings" handler
```
<Handler Alias="dictionaryHandler" Enabled="false" Actions="All" Group="Settings" />
```
