### ISSUE TITLE
Sync Publisher User Groups Not Working as Expected

### ISSUE THREAD

**Issue by krotkiske** [KevinJump/uSync8#262]
I have publishing permissions set to two user groups in umrbaco...

Editors 
Administrators

Having a user with just the editor permission - they cannot sync.
Having a user with just administrator permission - can sync.

Net result: I must make everyone an administrator in order for them to publish. this is not a viable option as we need to restrict administrator access.

Version: uSync.Publisher v8.8.0.0

Please advise.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**About your Site (please complete the following information):**
 - Umbraco Version:
 - uSync Version:

**Additional context**

**Comment by KevinJump** [comment]
Hi, 

The Umbraco groups will also need to have uSync Permissions assigned .(only admin gets these by default on an install). 

e.g if you go to the editor group in the user section, there should be three permissions in the list of Default permissions for the user. 

the relevant ones need to be ticked for the menu items to appear for people in that group. 

![image](https://user-images.githubusercontent.com/431231/128224859-9e95f16f-942d-4edc-a9aa-9f45618a090b.png)

> note for self: We either need to document this better or add these permissions by default to the editor group too.

**Comment by krotkiske** [comment]
Thanks. Sorry for the confusion, my error.


Kevin Rotkiske
***@***.***
