### ISSUE TITLE
uSync 9 rc on Docker hosted Umbraco - Js Files not found because of case sensitive paths

### ISSUE THREAD

**Issue by ThobiasMichel** [KevinJump/uSync8#267]
**Describe the bug**
When Umbraco 9 is running on a unix hosted Docker container, some path's are not working. This is related to the case sensitive on unix. On windows its working, but for unix is this another path.

**To Reproduce**
1. Open usync dashboard on a unix hosted umbraco
2. See error

Error is 404 on files like /App_Plugins/usync/backoffice/usync/usync.dashboard.controller.js. 

The "usync" folders are fetched from "uSync" or "usync". 

**Expected behavior**
Dashboard is working.

I copied the usync folders to have both variants, to get this working.

**About your Site (please complete the following information):**
 - Umbraco Version: 9 rc3
 - uSync Version: 9 rc3

**Additional context**

**Comment by KevinJump** [comment]
I haven't had an opertity to test this completely but for rc3 i did just go through all the js files and places where we refrence the files and try to ensure they all keep the same case.

so the plugin folder is now `App_Plugins/uSync` and then everything should be lower case from there.

**Comment by ThobiasMichel** [comment]
I will test the next days. Keep you updated.

**Comment by KevinJump** [comment]
Hi, 

done some docker testing today, and you will need to run a nightly build for things to to work. (see #277 Linux post). 

but everything from`version  9.0.0-rc003.20210910.3` on wards should at least have all the paths correct . 

_(i noticed using docker that caching was an issue, so had to remove any existing local files from app_plugins before a rebuild the image, and make sure the Umbraco cache wasn't serving up old files - hopefully thats not an issue for most, as they will not be reinstalling multiple very similar versions like i was while testing)_
