### ISSUE TITLE
v9: does not respect Json property naming policy

### ISSUE THREAD

**Issue by PhyxionNL** [KevinJump/uSync8#274]
**Describe the bug**
In Firefox:
TypeError: result.data.addOnString is undefined
    dashboardController usync.dashboard.controller.js:41
    Angular 30
    safeApply umbraco.services.min.js:1
    loadJs umbraco.services.min.js:1
 Possibly unhandled rejection: {}

In Chromium:
TypeError: Cannot read properties of undefined (reading 'length')
    at usync.dashboard.controller.js?d=1:41
    at angular.js:18013
    at XMLHttpRequest.y.onload (angular.js:13573) 'Possibly unhandled rejection: {}'

**To Reproduce**
Happens on pretty much every page, such as the dashboard:
/umbraco/#/settings/usync/dashboard

**About your Site (please complete the following information):**
 - Umbraco Version: 9 rc2
 - uSync Version: 9 rc2

**Other information**
I use built-in Json provider with property naming policy to null (```services.AddControllers().AddJsonOptions(options => options.JsonSerializerOptions.PropertyNamingPolicy = null)```). This causes the above problems with uSync 9.
Latest build from Azure has the same issue.

**Comment by KevinJump** [comment]
fixed for next release _(there might be a Umbraco rc003 soon - so we will release with that)._
