### ISSUE TITLE
Content type property not imported when having custom validation with value ^.{0,150}$

### ISSUE THREAD

**Issue by AlexandreLocas** [KevinJump/uSync8#278]
Hi, content type property is not imported when having custom validation with value ^.{0,150}$

1. Add a new property (textbox) using a custom validation using regex : ^.{0,150}$
2. Sync with another environnement
3. Property is ignored and not added to content type

uSync v8.4.0.0 + Content Edition
Umbraco version 8.13.1

Thank you

**Comment by KevinJump** [comment]
Hi, 

This is fixed in uSync 8.6.5+ or above (see #145) and there should be no reason why you can't upgrade all the way to uSync/ContentEdition v8.10.1 (works with all Umbraco v8 versions)
