### ISSUE TITLE
Add ability to exclude properties in content/media via config.

### ISSUE THREAD

**Issue by KevinJump** [KevinJump/uSync8#289]
Currently you can use code to not serialize an property by name. - but it would be good to do this via config. 

e.g 

```json

{
    "uSync" : {
        "Sets": {
            "Default" :{
                "Handlers" : {
                    "ContentHandler" : {
                         "Settings": {
                             "DoNotSerialize" : "mySpecialProperty,myOtherProperty" 
                         }
                    }
                }
            }
        }
    }
}
```

The `DoNotSerialize` property will need to be a comma seperated list of property aliases you don't want to include.

**Comment by KevinJump** [comment]
will put in 9.1 release.

**Comment by dataworking** [comment]
@KevinJump Does uSync publisher also use this base serialiser, so that properties can be excluded from syncing with DoNotSerialize?

**Comment by KevinJump** [comment]
Hi,

Publisher does do the same, but it has its own section . in "uSync:Publisher:Handlers".

_Note there is a double "handlers" group in this on purpose, because uSync:Publisher:Handlers is the equvialant of "usync:sets:default"_ 

e.g.

```json
{
    "uSync" : {
        "Publisher": {
            "Handlers" :{
                "Handlers" : {
                    "ContentHandler" : {
                         "Settings": {
                             "DoNotSerialize" : "mySpecialProperty,myOtherProperty" 
                         }
                    }
                }
            }
        }
    }
}
```
