### ISSUE TITLE
No UI for uSync on Umbraco 8.0.2

### ISSUE THREAD

**Issue by lcichanowicz** [KevinJump/uSync8#29]
Clean install of 8.0.2.  Install uSync, via backoffice.  Where is the UI for uSync?

![image](https://user-images.githubusercontent.com/4871064/59209654-cd1c5300-8b79-11e9-9455-3acc1d482b52.png)

![image](https://user-images.githubusercontent.com/4871064/59209668-d73e5180-8b79-11e9-8b1f-6888560dacc9.png)

**Comment by KevinJump** [comment]
it should appear on the left :( - does a restart do anything ? 

![image](https://user-images.githubusercontent.com/431231/59212372-200dfe80-8baa-11e9-94ba-568e0027c498.png)

**Comment by lcichanowicz** [comment]
Why didn't I think of that?  Thanks, @KevinJump.  Now, I notice that the uSync 8 node does not get the "selected" indication.

![image](https://user-images.githubusercontent.com/4871064/59214950-18d4f980-8b86-11e9-9d1f-d7f4b2b2ca76.png)

**Comment by KevinJump** [comment]
yeah, that took a while to find, but I've workout how the log viewer and languages do it now - will be in next release
