### ISSUE TITLE
Add support for Contentment Content blocks

### ISSUE THREAD

**Issue by KevinJump** [KevinJump/uSync8#290]
Add support for [Contentment](https://github.com/leekelleher/umbraco-contentment) Content blocks 

For genral syncing these blocks will work without uSync speicific handlers but the handlers add two things: 

- support for the data format on any nested properties changing between servers
- dependency calculation on the nested properties so media, etc gets included when uSync.Publisher pushes / pulls any content blocks.

**Comment by KevinJump** [comment]
Done in ea46f26e9540ca2683bfdacbeadc22c3115c023d

**Comment by leekelleher** [comment]
No way! 😻 Thank you!

This has been on my to-do (ideas) list for a while!
https://github.com/leekelleher/umbraco-contentment/blob/2.2.0/.github/IDEAS.md?plain=1#L58-L59
