### ISSUE TITLE
Importing in Umbraco v8 doesn't work

### ISSUE THREAD

**Issue by kristoflagae** [KevinJump/uSync8#297]
When I do a uSync import (no content) in Umbraco (8.16), all my document types are getting generated with the necessary groups, but I don't see any properties. Although the import reports the changes, none of them seems to be created. 

The data types are created correctly.
I use the full version of modelsbuilder (no use of PureLive).
What could possibly be wrong?

Also trying it with a default Umbraco installation didn't work.

![image](https://user-images.githubusercontent.com/18071933/137219914-ba39dd3e-2515-41cf-ac47-2ac165c3535f.png)

![image](https://user-images.githubusercontent.com/18071933/137219946-08ad5163-25d5-41d6-9197-038cb7145351.png)

![image](https://user-images.githubusercontent.com/18071933/137219983-3eb2a835-0f58-4daa-a9ae-29d1cfc1396d.png)

**Comment by KevinJump** [comment]
Hi, can you confirm the usync version ?

**Comment by KevinJump** [comment]
Hi, no worries i think its something we introduced when adding support for tabs in 8.17. 

fixed in 8.10.4 release. https://github.com/KevinJump/uSync/releases/tag/v8.10.4

**Comment by kristoflagae** [comment]
Hi, thx for the quick reply!

I used uSync version 8.10.3 with Umbraco 8.16
Using the newly uSync 8.10.4 indeed fixed the problem.
