### ISSUE TITLE
Style issue on dashboard

### ISSUE THREAD

**Issue by matthewcare** [KevinJump/uSync8#299]
Hi Kevin,

Not a massive issue, more a nice to have. I can open a PR if you want, but it seems like a lot of effort for a one liner

Could you update
https://github.com/KevinJump/uSync/blob/v9/main/uSync.Site/App_Plugins/uSync/usync.css#L418
to 
`grid-template-columns: repeat(auto-fit, minmax(342px, 1fr));`

On smaller screens it will mean this
![image](https://user-images.githubusercontent.com/1469061/137393307-28987fa6-9bb9-4ea8-aa6a-028cff41630a.png)

becomes this
![image](https://user-images.githubusercontent.com/1469061/137393375-2927def7-dca7-47a8-8a54-e21f177f30c2.png)

Importantly though, it means these line up

![image](https://user-images.githubusercontent.com/1469061/137393429-0d09031b-7a76-4857-9e4e-818eef2fad41.png)

**Comment by KevinJump** [comment]
Problem is it does this, on complete (or when you have forms or vendr). 

![image](https://user-images.githubusercontent.com/431231/137394159-d3c283a3-f257-4cce-89c0-67c49ca938ce.png)

not the end of the world, i think i need to fiddle with the min value a bit, to make it nicer.

**Comment by matthewcare** [comment]
Really? I get this with more items

![image](https://user-images.githubusercontent.com/1469061/137394497-e6811925-1e0c-4efd-9f6b-890a947c0112.png)

**Comment by KevinJump** [comment]
depends on how wide you go. to be honest, i think min just need to go to 400px then it doesn't look to squished

**Comment by matthewcare** [comment]
If you could have it line up with the report block, that would be great. I noticed it doesn't line up, and now I can't not see it!
