### ISSUE TITLE
disable content tracking in usync 9

### ISSUE THREAD

**Issue by shearer3000** [KevinJump/uSync8#302]
hello - more a quick question than a bug report, but in usync 9.0.2 how do you disable content tracking changes?
I looked on https://docs.jumoo.co.uk/uSync/v9/settings/settings/ but can't see a relevant setting.
thanks for the help,
Andrew

**Comment by KevinJump** [comment]
Hi 

yeah we are in the middle (very close to done) of updating the docs. 

new docs on how to do it here. 

http://usync.docs.jumoo.co.uk/docs/uSync/guides/content
