### ISSUE TITLE
Method missing

### ISSUE THREAD

**Issue by monkii-dev** [KevinJump/uSync8#31]
**Describe the bug**
After updating umbraco to v7.15.0 usync throws a '[MissingMethodException: Method not found: 'Umbraco.Core.Models.EntityBase.IUmbracoEntity Umbraco.Core.Services.IEntityService.GetByKey(System.Guid, Boolean)'.]'

**To Reproduce**
Update Umbraco to v7.15.0.
Run the site.

I have checked the Umbraco code and the IEntityService.GetByKey(System.Guid, Boolean) method is there. The site was working with 7.14.0.

**Comment by KevinJump** [comment]
Hi,

there was a breaking change in Umbraco 7.15 which changed the calls in the Entity Service :( 

https://github.com/umbraco/Umbraco-CMS/issues/5822

We have put a workaround into the latest version of uSync so if you **upgrade to uSync 4.0.14** this will go away.
