### ISSUE TITLE
Question: configuration

### ISSUE THREAD

**Issue by bielu** [KevinJump/uSync8#311]
Hi @KevinJump,
I have pretty stupid question, but there we go.
In usync for v8 I could do something like that:
`      <Handler Alias="contentHandler" Enabled="true">
          <Add Key="Include" Value="/Tagging" />
          <Add Key="Exclude" Value="/Tagging/ContentType/,/Tagging/Expertise/,/Tagging/LocationsJurisdictions/,/Tagging/Position/,/Tagging/Department/,/Tagging/Categories/,/Tagging/Tags/" />
          <Add Key="RulesOnExport" Value="true" />
        </Handler>`
how can i setup same thing in v9 :)

**Comment by KevinJump** [comment]
In theory (and i have to admit i haven't tested this extensively on v9. 

http://usync.docs.jumoo.co.uk/docs/reference/handlers#example

```json
"uSync" :{
    "Sets": {
        "Default": {
            "Handlers": {
                "ContentHandler" : {
                    "Settings" : {
                        "ImportTrashed": false,
                        "Exclude": "Home/Testing"
                    }
                }
            }
        }
    }
}
```


handler settings for v9 are here http://usync.docs.jumoo.co.uk/docs/reference/handlers#handler-specific-settings

**Comment by bielu** [comment]
thanks, will give a try

**Comment by bielu** [comment]
@KevinJump I can confirm it does work, but I have other question is there way to not include childrens?
As example i want import listing page, but not new pages under. 

said too early, If I added multiple values it doesnt work 😢

**Comment by KevinJump** [comment]
Not in config, 😞 

but you can write a notification handler to handle the `uSyncImportingItemNotification`, and then you can use the information passed to that method to halt the import (its called at the same point as the checks on the above)

e.g this **might** work. (haven't ran this code) 
```cs
public class uSyncNotificationEventsHandler :
     INotificationHandler<uSyncImportingItemNotification> 
{
        public void Handle(uSyncImportingItemNotification notification)
        {
            // my path to block children on
            var blockChildren = "/Homepage/Listings";

            // read the path from the xml 
            var path = notification.Item.Element("Info")?.Element("Path")?.Value;

            // if the path starts with what i want to block but is longer - assume its a child.
            if (path != null && path.InvariantStartsWith(blockChildren) && path.Length > blockChildren.Length)
                notification.Cancel = true;
        }
}
```

***n.b** you need to register this handler in a a composer see umbraco docs https://our.umbraco.com/documentation/reference/Notifications/*
