### ISSUE TITLE
Need a better way of disabling Content in V9

### ISSUE THREAD

**Issue by callumbwhyte** [KevinJump/uSync8#319]
**Is your feature request related to a problem? Please describe.**
Prior to V9 Content Edition was separate and therefore off by default, but now it's enabled OOTB. This doesn't fit our workflow so we'd like to be able to turn it off.

The [docs](https://usync.jumoo.co.uk/docs/uSync/guides/content/) suggest turning this off by setting `ExportOnSave` and `UIEnabledGroups` to "Settings". This works nicely, except when you have other groups you want enabled (e.g. Vendr uSync).

**Describe the solution you'd like**
If these properties could take multiple values, as an array or comma separated string, that would probably be suitable.

Additionally, having config options for what to exclude might work better in cases where there are multiple groups.

**Comment by KevinJump** [comment]
Hi, 

Sorry missed this 😞 

you should be able to set ExportOnSave and UIEnabledGroups to a comma delimited list of groups "e.g Settings,Vendr" - something we fixed for 9.0.4 i think 

https://github.com/KevinJump/uSync/commit/d32f250cdd26da1db4269610ef4fc9d22da8b444
