### ISSUE TITLE
Full Sync PUSH rather than pull

### ISSUE THREAD

**Issue by marklonquist** [KevinJump/uSync8#321]
Currently it's only possible to perform a full sync between two environments with.a PULL method (eg. from prod PULL from staging).

We would like to be able to instead do a PUSH from our staging environment, as we want to completely isolate the production environment (eg not let content editors access it).

Also, we would like to be able to schedule this so it runs, say, every night at a certain time - we could use hangfire for this but is it even possible right now?

**Comment by KevinJump** [comment]
Hi, 

you can push or pull a full sync from the server page . this should allow you to do a full sync both ways. 

![image](https://user-images.githubusercontent.com/431231/145974874-10f4d168-5561-474f-95b9-16ad2d1d896a.png)

Its the server config that details what an editor can do, and this can be setup so they can only do push if thats all you want. 

![image](https://user-images.githubusercontent.com/431231/145975052-2a7797d6-ba2e-45c3-a909-6e9dee06fa01.png)

---

at the moment the sync process actually involves multiple requests going between the source and target servers (its done like this so we don't get requests timeouts when syncing large a amount of items)

As such its not possible to schedule the sync at the moment - it is something we are looking into.

**Comment by KevinJump** [comment]
Hi,

We are just cleaning up old, issues, i hope this was something that has either been fixed for you or not happened again. 
if this is still an issue, then feel free to drop in a comment and we will look at re-opening the issue. 

♾️

n.b i think push pull of settings was updated in c8.11.x uSync.Complete.
