### ISSUE TITLE
Using the uSyncService events to change importing data does nothing to the importing data.

### ISSUE THREAD

**Issue by daanbakker1995** [KevinJump/uSync8#322]
**Describe the bug**
I am using the uSync 8 Exporter (v8.11.5). And I'm trying to change data that's getting imported. To achieve this I'm using the uSyncService event: ImportingItem. Then changing the items value. This however seems to do nothing to the item while importing. While debugging in Visual studio, I do get the element in my method. But when I change the data it does nothing to the imported item. 

Maybe I'm missing something or doing something wrong. But I can't find any documentation about how to use these events.

**To Reproduce**
My code is as followed:

```
    public class UsyncComponent : IComponent
    {
        private readonly string[] _targets = new string[] { "info@info.com","user@info.com" };

        public void Initialize()
        {
            uSyncService.ImportingItem += USyncService_ImportingItem;
        }

        public void Terminate()
        {
            uSyncService.ImportingItem -= USyncService_ImportingItem;
        }

        public void USyncService_ImportingItem(uSyncItemEventArgs<XElement> e)
        {
            if (e.Item != null)
            {
                var xml = e.Item.ToString();
                foreach (var str in _targets)
                {
                    if (xml.Contains(str))
                    {
                        xml = xml.Replace(str, "test@test.com");
                        e.Item = XElement.Parse(xml);
                        if(e.Change.Equals(uSync8.Core.ChangeType.NoChange)) e.Change = uSync8.Core.ChangeType.Update;
                    }
                }
            }
        }
    }
```

**Expected behavior**
To change the item with the data set in the `USyncService_ImportingItem` method.

**About your Site (please complete the following information):**
 - Umbraco Version:  Umbraco version 8.13.0
 - uSync Version: Usync v8.10.6 + Exporter (v8.11.5)
 - Browser: Chrome

**Comment by KevinJump** [comment]
Hi Dan, 

Just to confirm i think this is still an issue ? or is there a workaround, was just about to start looking at the next release and this was on my list .

**Comment by daanbakker1995** [comment]
Hi Kevin,

I think it's still an issue. I found a workaround. I used the event to find which imported items contain the text I want to be replaced. Then used different Umbraco services(like the IContentService) to change the content, after the import is finished.

**Comment by KevinJump** [comment]
i need to test it, but sort of hoping this is a simple fix. as everything is passed by reference if we set the node to the value in the event args i *think* that will trickel back up to the calling item.

**Comment by KevinJump** [comment]
bit more complex :(
