### ISSUE TITLE
[Question] v9.0.4 "EnableHistory": true.. is this only for Umbraco8 and not 9?

### ISSUE THREAD

**Issue by mistyn8** [KevinJump/uSync8#324]
Hopefully, a picture paints a thousand words.. history enabled, but no history content app in umb 9.1.2 + uSync 9.0.4
![image](https://user-images.githubusercontent.com/12418214/148534164-2afba1f9-1fb1-478f-be6d-e81fe9a9b217.png)

**Comment by KevinJump** [comment]
Yeah the history app isn't part of uSync 9.x (yet) - will have to get it ported over.

**Comment by KevinJump** [comment]
removed setting (for now) in v9.1
