### ISSUE TITLE
Clean Export option unreachable when "UIEnabledGroups": "Settings"

### ISSUE THREAD

**Issue by mistyn8** [KevinJump/uSync8#327]
Is it possible to move the cleanExport, like we can the dicitionaryHandler when not wanting content synching (and hiding the All settings back-office option)

Or perhaps all groups could have a clean export option (related to their scope)?

**Comment by KevinJump** [comment]
hi, yeah will take a look, we should be able to add it when the UIEnabledGroups setting is there - just need to make sure it doesn't confuse people as a clean removes everything at the moment.

**Comment by KevinJump** [comment]
doh! got the numbers transposed. this PR doesn't fix this issue.
