### ISSUE TITLE
Umbraco 8 : Usync warnings on startup

### ISSUE THREAD

**Issue by hamzatki** [KevinJump/uSync8#330]
Umbraco 8 logs contains these warnings for each of the default usync handlers e.g. 

No Handler with "contentHandler" has been loaded
No Handler with "contentTemplateHandler" has been loaded.
No Handler with "dictionaryHandler" has been loaded
No Handler with "domainHandler" has been loaded
No Handler with "mediaHandler" has been loaded

I am running umbraco v8.14.2 with uSync 9.06

I have this settings in usync.config file

 
    <HandlerSets default="default">
      <Handlers Name="default">
        <Handler Alias="dataTypeHandler" Enabled="true" />
        <Handler Alias="macroHandler" Enabled="true" />
        <Handler Alias="mediaTypeHandler" Enabled="true" />
        <Handler Alias="templateHandler" Enabled="true" />
        <Handler Alias="contentTypeHandler" Enabled="true" />
      </Handlers>
    </HandlerSets>

Please I would like to know why these warnings are in the logs and how can I fix it.

**Comment by mistyn8** [comment]
It is for information when the "all" is the default set.. (eg these handlers from the default set have be excluded by config)
https://github.com/KevinJump/uSync/blob/v9/main/uSync.BackOffice/SyncHandlers/SyncHandlerFactory.cs#L178-L182

It looks like you might just want "Settings" as your default set? and then those logs wouldn't show.

**Comment by KevinJump** [comment]
This log has been changed to debug for later versions - it isn't really something we need to show people unless they are troubleshooting.
