### ISSUE TITLE
Usync stalls when change to parameter name is only case.

### ISSUE THREAD

**Issue by mistyn8** [KevinJump/uSync8#331]
u9.1.2 usync9.0.4

![image](https://user-images.githubusercontent.com/12418214/150314086-f4223979-e602-46ed-b966-0170c19dd992.png)

Seems to be causing ContentType import to stall.

**Comment by KevinJump** [comment]
Hi is there any error in the log when you attempt the import ?

**Comment by mistyn8** [comment]
not that I can see (or any angular errors in the console) the site just becomes unresponsive and sits with the contentType icon progressbar stalled.
A recycle is required to resume.

Just tried to reproduce, but seems not to be happening now. (I did fix by manually changing the prop name in the backoffice so have prob changed my local db now?) reverting to the previous usync.config file reported the same detected changes but it then processed ok

Gremlins 👹

**Comment by KevinJump** [comment]
Closing, lets hope it was a one off. will re-open if we see it more.
