### ISSUE TITLE
uSync 9 - export on save overwriting content with same name

### ISSUE THREAD

**Issue by paulwoodland** [KevinJump/uSync8#335]
**Describe the bug and how to reproduce**
If you have multiple documents in your tree with the same name (even though they are in different locations in the tree, so this is fine) and you have export on save turned on in uSync, when you save changes to the document it correctly saves the right document, but then also overwrites all of the uSync files for the documents with the same name with files like this:
<?xml version="1.0" encoding="utf-8"?>
<Empty Key="KEY OF ORIGINAL DOCUMENT BEING SAVED" Alias="ALIAS OF ORIGINAL DOCUMENT" Change="Rename" Level="X" />

It affects media as well as content nodes.

**Expected behavior**
Only the one uSync file should be overwritten - the one being updated at the time. The files for documents of the same name should not be overwritten with the incorrect Empty files.

**About your Site (please complete the following information):**
 - Umbraco Version: v9.2.0
 - uSync Version: v9.0.6
 - Browser [e.g. chrome, safari]: Chrome

**Additional context**
I have been trying to track this down in the code, and have tracked it to line 1178 of SyncHandlerRoot.cs, where it calls DoItemsMatch and it returns true for all of the documents with the same name as the original one.

It does this because it calls GetItemAlias(), and this returns the alias of the document, so always matches for documents with the same name. From what I could see, it looks like in v8, the equivalent method seems to return the key of the document rather than the alias, so it wouldn't have this problem. Should v9 do the same for content and for media?

Hope it's clear, let me know if I've not explained anything properly.

**Comment by KevinJump** [comment]
Hi 

Yeah your right - I think we're missng an override, the TreeHandlerBase should override DoItemsMatch to then do a lookup based on the alias/path/key, so all tree based things match on something else. 

We will get this fixed asap. 

Kevin

**Comment by paulwoodland** [comment]
Many thanks for getting it looked at so quickly :) Would have submitted a PR, but wasn't sure where best to override it!
