### ISSUE TITLE
Path length error on node that is not included

### ISSUE THREAD

**Issue by lordscarlet** [KevinJump/uSync8#336]
**Describe the bug**
Even with a node excluded, receive the error `The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters`

**To Reproduce**
1. Have a node that is too long
2. Use the `include` setting to include a path that does not contain the node
3. Export content

**Expected behavior**
Since the node is not included, do not worry about the length of the path

**About your Site (please complete the following information):**
 - Umbraco Version: 8.16.0
 - uSync Version: 8.9.7

**Comment by KevinJump** [comment]
Thanks, we will take a look, guessing we are checking some path thing too soon 🤔
