### ISSUE TITLE
Error throwing when we try to save & publish, export or import the content/node

### ISSUE THREAD

**Issue by dKumarmj** [KevinJump/uSync8#363]
**Error on Content Save & Publish / Export**
Error throwing when we try to save & publish, export or import the content/node having the long name

**To Reproduce**
1. Create content with the long node name
2. Try to save & publish / Go to the settings section
3. Scroll down to Usync
4. Try to export

**Error in detail**

 - Request : /umbraco/backoffice/usync/usyncdashboardapi/ExportHandler
 - Status : 500 Internal Server Error
 - Error on Export/Import : _Unexpected character encountered while parsing value: <. Path '', line 0, position 0._
 
 - Error on Save & publish
![Capture](https://user-images.githubusercontent.com/58820887/156206471-10e18ba9-f49f-4b1c-9dd2-8f349ab0f93c.JPG)

**Version Using**
 - Umbraco Version: 9.2.0
 - Hosted in Azure (Web App)
 - uSync Version: 9.0.6

**Comment by KevinJump** [comment]
Hi,

If you have really long node names the advice at the moment is to switch to using telling uSync to use Guid File Names for the names of the items:

you can do this globally: 

```json
    "uSync": {
        "Sets": {
            "Default": {
                    "GuidNames": true
            }
       }
    }
```

or just for uSync.Exporter 

```json
    "uSync": {
        "Sets": {
            "Exporter": {
                    "GuidNames": true
            }
       }
    }
```

**Comment by dKumarmj** [comment]
Thanks, @KevinJump  for the quick response, if I change to GUID, is there any issues at the time of importing the existing content?

**Comment by KevinJump** [comment]
Hi,

There is no issue in terms of importing the content of the folders , all that changes is the filename (so the actual data being imported is the same) .

We do recommend if you switch to GuidFilenames that you perform a clean export, as the existing items on disk in your uSync folder will still have the old names and will start to get duplicates files as the guid versions of the files are saved.

**Comment by dKumarmj** [comment]
Thanks @KevinJump , make sense, please let me know how we can add this configuration in the Azure WebApp configuration?

**Comment by KevinJump** [comment]
Hi, 

you can put these settings in your applications appsettings.json file so when you site is deployed it will always have these settings,

however if you want to specifically set them on azure then that is done in the WebApps's configuration section: 

![image](https://user-images.githubusercontent.com/431231/156539658-9c171939-27b4-4c0f-b514-814895dc5d34.png)

as per the Microsoft documentation you replace any `:` with double __ (e.g the setting is `uSync:Sets:Default:GuidNames` becomes `uSync__Sets__Default__GuidNames`

when you add it the value is `true`

![image](https://user-images.githubusercontent.com/431231/156539921-22e05bf7-db2a-4d26-9f4f-fb9b9728141d.png)
