### ISSUE TITLE
Don't overwrite relations when importing relation types

### ISSUE THREAD

**Issue by callumbwhyte** [KevinJump/uSync8#364]
We have enabled relation type syncing in uSync, but now every time we deploy all relations that apply to a uSync'd type get erased.

I tried to set relation types to one-way, see below, but had no luck:

```
<Handler Alias="relationTypeHandler" Enabled="true">
  <Add Key="CreateOnly" Value="true" />
</Handler>
```

We are using uSync v8.11.0 with Umbraco v8.18.0

Not sure if I'm missing something or if this is a bug...!

**Comment by KevinJump** [comment]
Hi , 

just to confirm is this the relation type or the relations that are going missing (the handler does both, but i think relations bit is off by default). 

but I will have a look see what there is...

**Comment by callumbwhyte** [comment]
Hey @KevinJump,

Thanks for the speedy reply.

This is relation types - we have the following definition:

```
<?xml version="1.0" encoding="utf-8"?>
<RelationType Key="e8e0f1b4-6841-404f-a580-de9e9dc45fd3" Alias="relateMemberToSellerProfile" Level="0">
  <Info>
    <Name>Relate Member To Seller Profile</Name>
    <ParentType>39eb0f98-b348-42a1-8662-e7eb18487560</ParentType>
    <ChildType>c66ba18e-eaf3-4cff-8a22-41b16d66a972</ChildType>
    <Bidirectional>true</Bidirectional>
  </Info>
  <Relations />
</RelationType>
```

And the following config in uSync.config:

```
<Handler Alias="relationTypeHandler" Enabled="true">
  <Add Key="CreateOnly" Value="true" />
</Handler>
```

That's the only thing referencing relations so couldn't see a way to turn this off.

Cheers,
Callum

**Comment by callumbwhyte** [comment]
I don't think I properly read your message...

We are syncing relation types. Every time we sync it wipes out the **relations** for that type.

**Comment by KevinJump** [comment]
Hi, 

I think you need to turn the 'IncludeRelations' to off (its on by default, i thought it was off )

```
<Add Key="IncludeRelations" Value="false" />
```

**Comment by KevinJump** [comment]
guessing the relations don't exist on the source so are wiped on target :( - 

I think we will change this default for next v9 ? /  and in v10.

**Comment by callumbwhyte** [comment]
That'll do it! I couldn't find anything in the docs about this _(in fact relation types aren't mentioned at all!)_, so thanks very much for the pointers. 👍

Would be great to see this off by default in whatever the soonest release you fancy making a breaking change is :-)

**Comment by KevinJump** [comment]
indeed - the docs are a bit light on the relation handler, we added it later and need to go back.... put a basic warning in the config part of the docs now, but it will need more written about it i think.

**Comment by callumbwhyte** [comment]
H5YR, thanks a lot Kevin!
