### ISSUE TITLE
User Groups

### ISSUE THREAD

**Issue by NikRimington** [KevinJump/uSync8#366]
Hey Kevin,

Is it possible to use uSync to export and import user groups?
It would be great if we could import/export user groups (excluding the groups members) between environments so when we are setting up specific access rules we can test them full and then deploy them efficiently.

**Comment by KevinJump** [comment]
HI Nik, 

Yeah that functionality is part of uSync.Complete - uSync.PeopleEdition can exports user groups (and users, and member groups and members and you can turn off the ones you don't want :wink: ) it is not unfortunately part of the free uSync package.
