### ISSUE TITLE
Media push to remote doesn't detect locally deleted folders

### ISSUE THREAD

**Issue by PhyxionNL** [KevinJump/uSync8#367]
**Describe the bug**
Pushing media to remote doesn't detect locally deleted folders. It doesn't matter if the folder is empty or not, it's not detected in both cases.

**To Reproduce**
1. Go to .../umbraco/#/media.
2. Click on 'Media', the big top node. Then ... > Do something else > Push to...
3. Select a target > remote destination. All checkboxes below are checked.
4. "No changes detected".

**Expected behavior**
If a media folder is locally deleted, and still exists on remote, it should be deleted.

**About your Site (please complete the following information):**
 - Umbraco Version: 9.3
 - uSync Version: 9.2.0

**Comment by KevinJump** [comment]
Hi, 

yeah - just looking at this we don't currently put a root clean command in  😔 - so it works at all levels but the top level. 

Will take a look and see what's possible

**Comment by PhyxionNL** [comment]
Thanks. I found out it also happens with Document Types and Data Types (under Settings), if you select these nodes to push to remote, deleted items aren't detected either. Probably the other sub categories there are also affected, but I've not tried.

E: Feel free to move this to uSync Complete Issues. I thought this was that repo 👀

**Comment by KevinJump** [comment]
Yeah - some of them we don't support delete on (because we don't want people to trash everything by accident).

_there are two parts to this uSync needs an update too, so i will leave the issue open here, when we do complete, i might make another one_

**Comment by PhyxionNL** [comment]
> Yeah - some of them we don't support delete on (because we don't want people to trash everything by accident).

I had to manually delete many items now several times, so it would be useful if this scneario was supported 😄 Maybe move it to trash then so it can be restored if it was ever needed :)

**Comment by KevinJump** [comment]
yeah there is no trash for doctypes, data types if you delete them they are gone, and if you do it by accedent then all the content / properties would be gone to. 

We might turn it on with a config setting, something like "WeWontEmailKevinIfWeLooseAllOurContent"  😉 (it is possible - its just  actively off in the code at the moment)

_edit: put this in for the next uSync.Complete release it will have the slightly catcher title of `AllowDeletingOfOrphanedItemsForAllTypes`_
