### ISSUE TITLE
Updating uSync doesn't seem to update the version number shown in the uSync section

### ISSUE THREAD

**Issue by NikRimington** [KevinJump/uSync8#37]
**Describe the bug**
uSync was originally installed as version 8.1.0 in Umbraco 8.1 
Over time things have been updated to Umbraco 8.1.2 and uSync 8.1.1
However in the uSync section in the back office, uSync still says that version 8.1.0 is installed. Checking DLL's etc 8.1.1 is definitely the version installed.

**Expected behavior**
I'd expect uSync to tell you that version 8.1.1 is installed not version 8.1.0

**Screenshots**
![image](https://user-images.githubusercontent.com/13313745/63091094-3727ee80-bf55-11e9-9344-4441a7ad083c.png)

![image](https://user-images.githubusercontent.com/13313745/63091112-44dd7400-bf55-11e9-8d8f-6f32f80f0dd5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22] : Latest 

Applies to local version of site, as well as 3 environments on Azure.

**Comment by KevinJump** [comment]
thanks - yeah this is a string value we forgot to update 😞 

this is fixed in the upcoming 8.2 release as its now something we take from the dll version 
36af3edbb5795fe84332b7da1bd347f077435f1b
