### ISSUE TITLE
SyncHub 404 Error & "Cannot read properties of null" During Import

### ISSUE THREAD

**Issue by SquaredSee** [KevinJump/uSync8#389]
**Describe the bug**
When using uSync to import content to our site, the import seems to get stuck on "Post import actions". Looking into the console, I see that reloading the page causes the error messages up to "Failed to start hub". When I attempt to import the content, the final error "Cannot read properties of null" happens.

We have deployed this same build on two different environments, with our Development environment working as expected (no errors in the console) and our Production environment with this error. This leads me to believe it is an environment issue, but I am not sure what would be causing this. Any insight into how uSync works and what might be causing this would be appreciated.

**Screenshot**
![screenshot](https://user-images.githubusercontent.com/22715939/167012921-d9bb9e74-563c-4f90-aefd-09871f432c62.png)

**About your Site (please complete the following information):**
 - Umbraco Version: 9.4.3
 - uSync Version: 9.4.0
 - Browser: Chrome

**Comment by TQ-Benji** [comment]
Getting same error on Umbraco 9.5.4

response from /SyncHub?id=... is "No Connection with that ID"

**Comment by KevinJump** [comment]
Hi, 

Client errors for the Hub won't actually cause any issues with the sync, - as they are informational, (so the script should in theory ignore them and carry on). there were some fixes around errors in v10/11 builds to remove the errors. 

On a side note, as Umbraco 9 is end of life and no longer supported (see [Umbraco LTS](https://umbraco.com/products/knowledge-center/long-term-support-and-end-of-life/) ) - This means we also no longer support uSync v9 and will not be fixing any issues. 

Upgrades from v9 to v10+ are reasonably painless (and really recommended, v9 is no longer even security fix supported)

If we see these issues on v10+ then we would look at them.
