### ISSUE TITLE
DocType import error

### ISSUE THREAD

**Issue by yavorsky-vl** [KevinJump/uSync8#39]
**Describe the bug**
When importing one of the documents, I get an error:
Import Fail: Object reference not set to an instance of an object.
Шt looks like one of the operations exceeds the timeout.
I have caught look in database:
**Directly Blocked Transactions:**
**Blocking SQL   Statement**
SELECT [umbracoDocument].[nodeId] AS [NodeId],   [umbracoDocument].[published] AS [Published], [umbracoDocument].[edited] AS   [Edited] , [umbracoContent].[contentTypeId] AS [ContentDto__ContentTypeId],   [umbracoContent].[nodeId] AS [ContentDto__NodeId] , [umbracoNode].[id] AS   [ContentDto__NodeDto__NodeId], [umbracoNode].[uniqueId] AS   [ContentDto__NodeDto__UniqueId], [umbracoNode].[parentId] AS   [ContentDto__NodeDto__ParentId], [umbracoNode].[level] AS   [ContentDto__NodeDto__Level], [umbracoNode].[path] AS [ContentDto__NodeDto__Path],   [umbracoNode].[sortOrder] AS [ContentDto__NodeDto__SortOrder],   [umbracoNode].[trashed] AS [ContentDto__NodeDto__Trashed],   [umbracoNode].[nodeUser] AS [ContentDto__NodeDto__UserId],   [umbracoNode].[text] AS [ContentDto__NodeDto__Text],   [umbracoNode].[nodeObjectType] AS [ContentDto__NodeDto__NodeObjectType],   [umbracoNode].[createDate] AS [ContentDto__NodeDto__CreateDate] ,   [umbracoDocumentVersion].[id] AS [DocumentVersionDto__Id],   [umbracoDocumentVersion].[templateId] AS [DocumentVersionDto__TemplateId],   [umbracoDocumentVersion].[published] AS [DocumentVersionDto__Published] ,   [umbracoContentVersion].[id] AS [DocumentVersionDto__ContentVersionDto__Id],   [umbracoContentVersion].[text] AS   [DocumentVersionDto__ContentVersionDto__Text],   [umbracoContentVersion].[versionDate] AS   [DocumentVersionDto__ContentVersionDto__VersionDate],   [umbracoContentVersion].[nodeId] AS   [DocumentVersionDto__ContentVersionDto__NodeId],   [umbracoContentVersion].[userId] AS [DocumentVersionDto__ContentVersionDto__UserId],   [umbracoContentVersion].[current] AS   [DocumentVersionDto__ContentVersionDto__Current] , [pdv].[id] AS   [PublishedVersionDto__Id], [pdv].[templateId] AS   [PublishedVersionDto__TemplateId], [pdv].[published] AS   [PublishedVersionDto__Published] , [pcv].[id] AS   [PublishedVersionDto__ContentVersionDto__Id], [pcv].[text] AS   [PublishedVersionDto__ContentVersionDto__Text], [pcv].[versionDate] AS   [PublishedVersionDto__ContentVersionDto__VersionDate], [pcv].[nodeId] AS   [PublishedVersionDto__ContentVersionDto__NodeId], [pcv].[userId] AS   [PublishedVersionDto__ContentVersionDto__UserId], [pcv].[current] AS   [PublishedVersionDto__ContentVersionDto__Current] ,   COALESCE([ccv].[name],[umbracoNode].[text]) AS variantName FROM   [umbracoDocument] INNER JOIN [umbracoContent] ON [umbracoDocument].[nodeId] =   [umbracoContent].[nodeId] INNER JOIN [umbracoNode] ON   [umbracoContent].[nodeId] = [umbracoNode].[id] INNER JOIN   [umbracoContentVersion] ON ([umbracoDocument].[nodeId] =   [umbracoContentVersion].[nodeId]) INNER JOIN [umbracoDocumentVersion] ON   ([umbracoContentVersion].[id] = [umbracoDocumentVersion].[id]) LEFT JOIN   [umbracoContentVersion] [pcv] INNER JOIN [umbracoDocumentVersion] [pdv] ON   (([pcv].[id] = [pdv].[id]) AND [pdv].[published] = @0) ON ([umbracoDocument].[nodeId]   = [pcv].[nodeId]) LEFT JOIN [umbracoContentVersionCultureVariation] [ccv]   INNER JOIN [umbracoLanguage] [lang] ON (([ccv].[languageId] = [lang].[id])   AND ([lang].[languageISOCode] = @1)) ON ([umbracoContentVersion].[id] =   [ccv].[versionId]) WHERE (([umbracoNode].[nodeObjectType] = @2)) AND   ([umbracoContentVersion].[current] = @3) AND   ([umbracoContent].[contentTypeId] IN (@4)) ORDER BY   [ContentDto__NodeDto__Path] , [ContentDto__NodeDto__NodeId]     OFFSET @5 ROWS FETCH NEXT @6 ROWS ONL
**Blocked SQL Statement**
UPDATE umbracoLock SET value = (CASE WHEN (value=1) THEN -1 ELSE   1 END) WHERE id=@

**Comment by KevinJump** [comment]
Hi,

We are just cleaning up old, issues, i hope this was something that has either been fixed for you or not happened again. 
if this is still an issue, then feel free to drop in a comment and we will look at re-opening the issue. 

♾️
