### ISSUE TITLE
dictionary labels whitespace

### ISSUE THREAD

**Issue by YabberWalkie** [KevinJump/uSync8#392]
I'm working on a website with alot of labels, as we have 3 environments we use uSync's dictionary items to import/export them.
I'm running into a issue where some labels only contain a whitespace, " "

Exporting & then trying to import these labels will import them as empty and not a whitespace. When import it will also override any label that did have the correct whitespace value. 

As these labels have no default value they then show up in my website with the label name.

Screenshot of the usync dictionary file, and then when i import

![image](https://user-images.githubusercontent.com/5858777/171663390-ef7496a4-d1e4-4cfb-acf6-0882f791b981.png)

![171663358-8bdc397a-9adc-48b6-81c4-9c988980d3f7](https://user-images.githubusercontent.com/5858777/175266783-d1976f22-5c19-474e-b627-ae66bf0b93b7.png)

 - Umbraco Version: 8.18.3
 - uSync Version: 8.11.0

**Comment by KevinJump** [comment]
Housecleaning - This was merged in v8.11.1 -
