### ISSUE TITLE
uSync subfolder still called v9 on the v10 version

### ISSUE THREAD

**Issue by jemayn** [KevinJump/uSync8#397]
Hey Kevin,

Playing around with a new project on Umbraco 10 and uSync v10 - I noticed that the folder within the uSync folder is still called v9:
![image](https://user-images.githubusercontent.com/79840720/175280957-a5e73c40-bb44-4862-85be-6fd2d5ce1fab.png)

This was on a fresh install and boot of uSync for the first time 🙂

PS. The readme file on the v10/dev branch also says v9 here: https://github.com/KevinJump/uSync#umbraco-on-netcore-aka-umbraco-9

**Comment by KevinJump** [comment]
yeah - we have decided to keep it v9 (for now)  - Not sure if we should have, but there are no changes in file format between v9 and v10 , so we where going for seemless. 

but to be honest i am wondering now. - We might have to see if there is a way if we can tell the diffrence between upgraded and fresh installs.

**Comment by jemayn** [comment]
Oh ok, just seemed a bit weird 😁

Maybe if no migration records exist in the keyValue table? (Guessing you have some startup migrations)

Anyways just wanted to let you know, I will close this issue again then.
