### ISSUE TITLE
Issue syncing with compositions

### ISSUE THREAD

**Issue by Attackmonkey** [KevinJump/uSync8#399]
**Describe the bug**
When the FIRST property on a panel is a composition, the properties underneath are moved onto a separate panel of the same name on import using 8.10.5. Haven't tried this on a site with tabs, as I don't currently maintain any sites that are using it!

**To Reproduce**
Create a composition property, e.g. "Heading". and add it to a pane on your DocType, e.g. in the "Content" panel. Add some properties into the content panel underneath, ensuring that their sort order is high enough that they are underneath the composition field.

Export the uSync files to your other site and run. On either add or update, the first composition property will be in a panel called "Content" all by itself, and the other properties will appear on a duplicate panel called "Content". If the first property on the panel is NOT a composition, it works as expected and everything is on the same panel.

**Expected behaviour**
All properties should be on the same panel called "Content".

**About your Site (please complete the following information):**
 - Umbraco Version: 8.17.1
 - uSync Version: 8.10.5
 - Browser: latest Chrome on Windows

**Comment by KevinJump** [comment]
Hi, 

I think you might need to upgrade uSync. 

release [8.10.6 has a fix in for tabs groups and ordering,](https://github.com/KevinJump/uSync/releases/tag/v8.10.6) so that might well fix this, 

i would go to the latest [v8.11.0](https://github.com/KevinJump/uSync/releases/tag/v8.11.0) as a matter of course because that has all the fixes we know about in it. (and is also the version we will support going forward)

**Comment by Attackmonkey** [comment]
Have upgraded to the latest version, and the issue still seems to be present. Re-exporting everything and the re-syncing resulted in the duplicate panels again I'm afraid!

**Comment by KevinJump** [comment]
Ok, I'll take a look based on your steps above.

**Comment by Attackmonkey** [comment]
Let me know if you need any additional info!

**Comment by Attackmonkey** [comment]
Actually, I deleted all the uSync files on the target server and THEN re-ran uSync and it seems to be OK now.

**Comment by KevinJump** [comment]
👍
