### ISSUE TITLE
v8 - Not initialising all handlers

### ISSUE THREAD

**Issue by AndyBoot** [KevinJump/uSync8#405]
Hey,

We've inherited a Umbraco v8.13 site with uSync v8.9.1.0 which is having an issue initialising all the handlers and has become a little bit of a blocker for deployments to other environments.

So for context, I have enabled all the handlers as per the below uSync.config file:
```
    <HandlerSets Default="default">
      <Handlers Name="default">
        <Handler Alias="dataTypeHandler" Enabled="true" Actions="All" />
        <Handler Alias="languageHandler" Enabled="true" Actions="All" />
        <Handler Alias="macroHandler" Enabled="true" Actions="All" />
        <Handler Alias="mediaTypeHandler" Enabled="true" Actions="All" />
        <Handler Alias="memberTypeHandler" Enabled="true" Actions="All" />
        <Handler Alias="templateHandler" Enabled="true" Actions="All" />
        <Handler Alias="contentTypeHandler" Enabled="true" Actions="All" />
        <Handler Alias="contentHandler" Enabled="true" Actions="All" />
        <Handler Alias="contentTemplateHandler" Enabled="true" Actions="All" />
        <Handler Alias="dictionaryHandler" Enabled="true" Actions="All" />
        <Handler Alias="domainHandler" Enabled="true" Actions="All" />
        <Handler Alias="mediaHandler" Enabled="true" Actions="All" />
        <Handler Alias="relationTypeHandler" Enabled="true" Actions="All" />
      </Handlers>
    </HandlerSets>
```

However all I'm ever able to see are these:
![image](https://user-images.githubusercontent.com/82056925/178753962-9225826f-4c68-4a12-9bba-13c984ccaa44.png)

As you can see I'm only getting 7 of the 13 handlers. The missing ones appear to be:

- macroHandler
- contentHandler
- contentTemplateHandler
- dictionaryHandler
- mediaHandler
- relationTypeHandler

I've even gone to the extreme of upgrading Umbraco and uSync to their latest releases relative to v8 and still the same results.

I'm at a loss as to what could be causing this! Could the original developer(s) of the site have modified something within the project to cause this preventing uSync from being able to access the missing handlers? Any clues would be gratefully appreciative.

If you require any more information, let me know.

Please enable me to "uSync all the things" once again 😉

Many Thanks,
Andy.

**Comment by KevinJump** [comment]
I think you probably don't have uSync.ContentEdition installed ? In v8 uSync and uSync.ContentEdition are separate packages (in v9+ its all one package) if you want sync the content (and macros, dictionary) then you need uSync.ContentEdition package too.

**Comment by AndyBoot** [comment]
Why is it always the simplest things 😅

Sorry for logging this as a bug, as I know uSync works out of the box perfectly well, but couldn't for the life of me determine what was causing it. Your reply was one of those lightbulb moments. And you know, I've only had to install ContentEdition once in my life (maybe 2 years ago) and that was for a VS template to build future v8 sites on top of and it's not been a consideration since.

Keep up the great work Kevin. Thank you for your help!

All the best,
Andy
