### ISSUE TITLE
Parent-child Document Type relationships broken on Import

### ISSUE THREAD

**Issue by JoseMarcenaro** [KevinJump/uSync8#407]
**Describe the bug**
On a clean Umbraco v8.18.4 install with uSync v8.11.1, exporting and then reimporting a child document type brokens the relationship: child type is imported outside the parent type - at the same level. 

**To Reproduce**
1. Create a clean Umbraco v8.18.4 website, add uSync v8.11.1 with the default configuration
2. Create a "BaseDocType" at the root DocumentTypes node
3. Create a "ChildDocType" inside the previous node, add a couple of properties (i.e. "Title", textstring)
4. Edit the `childdoctype.config` file, change any small detail (i.e. change the Alias from 'title' to 'title2')
5. Perform an uSync Import

The ChildDocType document type is imported at the same level of BaseDocType, not inside.  
An uSync report (or export) shows that the <Parent.. > element is lost (the <Composition...> is kept)

**Expected behavior**
To keep the same parent-child relationship

**Screenshots**
Created documents:
![image](https://user-images.githubusercontent.com/923289/180662557-0b76025d-5709-4c5c-8c93-ef6d45213cc8.png)

After import:
![image](https://user-images.githubusercontent.com/923289/180662565-a7b62d01-5287-4bc5-8285-91e7da8ee088.png)

**About your Site (please complete the following information):**
 - Umbraco Version: 8.18.4
 - uSync Version: 8.11.1
 - Browser Chrome

**Additional context**
Using uSync default configuration

**Comment by JoseMarcenaro** [comment]
Notes:
* I'm almost sure this didn't happen in Umbraco v8.17 with uSync 8.10.4 - it started breaking after the upgrade to Umbraco v8.18 and uSync v8.11
* The problem does not seem to happen in Umbraco v9/v10 with uSync 9.x

**Comment by KevinJump** [comment]
Thansk, will be in next v8.x release.

**Comment by JoseMarcenaro** [comment]
Hi @KevinJump .  Any chance we can get a new release for v8, so we can get this patch on the official Nuget channel?

Thanks for your continuous support to this amazing plugin.

**Comment by KevinJump** [comment]
Yes - 8.11.2 is out - has this (and one other really minor ui fix) in it.
