### ISSUE TITLE
Usync Import Users not importing user group permissions but able to export

### ISSUE THREAD

**Issue by anil60265** [KevinJump/uSync8#412]
Hi,
In Umbraco 9 and 10, when click on Import/Full Import, under Users section in USync, the permissions set for user group are not getting imported.
But clicking on Export button is exporting properly.
Could you please check into it.

**Comment by KevinJump** [comment]
Hi,

Yeah taken a look and & we've seen the bit we have missed, it will be in the next update.

K

**Comment by anil60265** [comment]
Thank you for looking it. Waiting for the update!!

**Comment by crankedapps** [comment]
Any update on this?

**Comment by crankedapps** [comment]
> Hi,
> 
> Yeah taken a look and & we've seen the bit we have missed, it will be in the next update.
> 
> K

Any update on this?

**Comment by KevinJump** [comment]
sorry just updating this - was fixed in uSync.Complete releases v11.0.1 and v10.4
