### ISSUE TITLE
uSync 10 converting JSON numbers and booleans to strings on export

### ISSUE THREAD

**Issue by dan-hammond** [KevinJump/uSync8#413]
**Describe the bug**
uSync 10 is not exporting JSON content properties correctly. It seems that bools and numbers are being converted to strings, which is then causing problems when re-imported.

**To Reproduce**
I made a minimal test project here:
https://github.com/dan-hammond/usync-10-export-bug-repro

1. Install Umbraco and log in
2. Create a document type which uses the "TestPropertyEditor"
3. Create and save a piece of content using this editor
4. Run a uSync content export
5. Observe that boolean and number JSON properties have been stringified in the uSync export XML

**Expected behavior**
I would expect booleans and numbers to export as their source types, so they can re-import correctly.

**Screenshots**
![diff](https://user-images.githubusercontent.com/11477232/186688563-4b803173-5462-48f9-83fa-3ae97bd49db2.png)
On the left is the relevant part of my test property editor, on the right is the uSync generated XML.

**About your Site (please complete the following information):**
 - Umbraco Version: 10.1.0
 - uSync Version: 10.1.0
 - Browser [e.g. chrome, safari]: n/a

**Additional context**
This problem also occurs in uSync 10.0, but does not occur in Umbraco/uSync 9.

**Comment by KevinJump** [comment]
Yeah - looks like we did that when we where fixing how nested json inside block elements, work.

**Comment by KevinJump** [comment]
Will be in 10.2.x (to coincide with Umbraco 10.2)

EDIT: Updated release link (to the right one!)

nightly build available :https://dev.azure.com/jumoo/Public/_artifacts/feed/nightly/NuGet/uSync/overview/10.2.0-build.20220825.1

**Comment by dan-hammond** [comment]
You're a star, thank you so much.
