### ISSUE TITLE
Import Content data binding error

### ISSUE THREAD

**Issue by crankedapps** [KevinJump/uSync8#414]
**Describe the bug**
When I do a Full Import of Content, I am presented with a bunch of failed data bindings on the page.  So you will see a page full of {{result.name}} and so on.

**To Reproduce**
1. Go to uSync settings dashboard in Backoffice
2. Click on Full Import of Settings (success)
3. Click on Full Import of Content (successfully imported, but data bindings on page fails)

**Expected behavior**
I expect the variables wrapped in {{ curly braces }} to be populated.

**Screenshots**
uSync v10.0.1
![image](https://user-images.githubusercontent.com/31190074/187274827-0257b059-4dd4-42cb-8ed3-24e1d69d49f8.png)
uSync v10.1.0
![image](https://user-images.githubusercontent.com/31190074/187276027-c5e46af1-f3e5-4f7a-b8f2-fd3b4ad3a359.png)

**About your Site (please complete the following information):**
 - Umbraco Version: 10.0.1
 - uSync Version: 10.0.0 & 10.1.0 (tried both versions, same results)
 - Browser [e.g. chrome, safari]: Chrome Version 104.0.5112.102 (Official Build) (64-bit)

**Comment by KevinJump** [comment]
Hi, 

If you have upgraded a site from Umbraco 9/ uSync 9 can you confirm that all the files in the app_plugins/uSync folder have been removed ? 

I think this is is the effect you get when there are files in app_plugins/uSync from the older version

**Comment by crankedapps** [comment]
Yes, this fixed my issue.  Thank you for the prompt reply! ♥

**Comment by KevinJump** [comment]
And we've added in some build actions so for future versions we will just silently try and delete the folder. 
https://github.com/KevinJump/uSync/commit/eb107761a86e283df42b5e299e2ff7d4ab74e637
