### ISSUE TITLE
v11: Add 'Back' the Apply button.

### ISSUE THREAD

**Issue by KevinJump** [KevinJump/uSync8#443]
Hidden in the code there is an 'Apply' button that allows you to import individual items into uSync from a report. 

its hidden/off because actually it can be quite dangerous if you import something without its dependencies (e.g. a doctype before the data types, then things might not work.

but we could add it in and have some warnings around things because well that might help a ~@marcemarc~ a few people 

![image](https://user-images.githubusercontent.com/431231/202844885-25c3eec7-3b6f-4a85-a951-cb43a5de642b.png)

**Comment by marcemarc** [comment]
would it be a configurable unhidden feature by convention - if you create an advanceduSyncSuperUserAdmin User Group, would members of that see the option - so out of the box it's not there, but could be a more 'per user' thing

**Comment by KevinJump** [comment]
It got missed from the notes but this is actually in v11.0.1
