### ISSUE TITLE
uSync doesn't synchronize published content

### ISSUE THREAD

**Issue by SandraGecko** [KevinJump/uSync8#45]
I have two Umbraco8 sites. One for development and second for testing. I have installed uSync, uSync.Core, uSync.ContentEdition and uSync.Backoffice.Core to the both of them. I set the settings Export on startup, import on startup, export on save on both of them. I have published content on the first one with text and images. First I started the first one and I went to usync and exported everything. Then I copied the View, Media and the Usync folder, the only ones I have to copy, and I copied them to the test site's folder. Then I imported them in the Testing site. The problem is next. In the Content Tab in the BackOffice, published Content Pages' names are faded out and they are proper document types but they are empty without text and images.

What can be the problem?

**Comment by KevinJump** [comment]
Hi,

just to confirm, you should turn export on startup **OFF** to achive what you want. or as the site starts up it will export over the usyncfolder you have copied and corrupt your import. 

I would suggest you turn import at startup off too while you debug. try the following:

1. Do a full export on the first site.
2. Copy the uSync folder to the second site.
3. Run a report on the second site, to see that it is picking up the items you have copied
4. Run an import on the second site
5. check to see what you now have.

**Comment by KevinJump** [comment]
Hi as this post is also on the forum i am closing this issue, because at the moment this is more likely support than fixing an issue with the package.
