### ISSUE TITLE
Media Picker 3 Start Node

### ISSUE THREAD

**Issue by agrath** [KevinJump/uSync8#458]
**Describe the bug**
On MediaPicker3, a start node is not being mapped correctly resulting in 404s when trying to use the picker on the destination site

**To Reproduce**
1. Create a document type with a media picker, using media picker 3
2. Create a folder in media
3. Set start node on the media picker
4. In usync I see this in the data type .config file `"StartNodeId": "umb://media/a41d829651a244c6903adecb9a054a93",` 
5. Sync the files onto a new target site, where that media item doesn't exist
6. Create a media folder with the same name as dev (of course this will have a different id)
7. Run usync import again, the media picker doesn't change to link to the new media folder with the same name
8. Trying to use the media picker results in 404s that look like this:
9. /umbraco/backoffice/umbracoapi/entity/GetById?id=umb%3A%2F%2Fmedia%2Fa41d829651a244c6903adecb9a054a93&type=media => 404 [this 404s because there's no media item on this site with that id]

**Expected behavior**
The media picker on the destination site should have a value of the media guid for the target site, if I manually reselect the start node then it works again but after a deploy/sync the media id is changed back to the one from the dev site which doesn't match on the destination site

**Screenshots**
n/a

**About your Site (please complete the following information):**
 - Umbraco Version: 10.3.2
 - uSync Version: 10.2
 - Browser [e.g. chrome, safari] Chrome

**Additional context**
Using uSync not uSync.Complete, I don't expect the media folder to be created however I'd have thought it needs to be mapped by name back to the target site guid when import occcurs
I have created a destination folder with the same name

**Comment by KevinJump** [comment]
yep - we need to get a a mediaPicker3 version of the [MediaPickerConfigSerializer](https://github.com/KevinJump/uSync/blob/v11/dev/uSync.Community.DataTypeSerializers/CoreTypes/MediaPickerConfigSerializer.cs) in the Community.DataSerializers package.
