### ISSUE TITLE
v10 en-US language is not removed on a clean install when running usync for the first time

### ISSUE THREAD

**Issue by NikRimington** [KevinJump/uSync8#460]
Using a clean installation of Umbraco v10.3.2 and adding uSync along with some existing definition files for languages, the usync process does not remove the automatically created en-US language and replace it with en-GB.

I have 2 uSync files in my language folder:

en-us.config
```xml
<?xml version="1.0" encoding="utf-8"?>
<Empty Key="e1397557-da8b-4236-b0fc-cdb774ecc374" Alias="en-US" Change="Delete" />
```

and en-gb.config
```xml
<?xml version="1.0" encoding="utf-8"?>
<Language Key="00000809-0000-0000-0000-000000000000" Alias="en-GB" Level="0">
  <IsoCode>en-GB</IsoCode>
  <IsMandatory>false</IsMandatory>
  <IsDefault>false</IsDefault>
</Language>
```

The aim of the files is to remove the default language of en-US and replace it with en-GB. However, after a fresh install and first run, en-US still exists and isn't removed.

**Comment by KevinJump** [comment]
Hi, 

I think the delete fails if there isn't a default language  - 

with the files above on a clean install i get. 

![image](https://user-images.githubusercontent.com/431231/211777420-0ef6a3ef-a59b-45c4-9c22-08519667d68d.png)

but if i change the en-gb one. 

```xml
<?xml version="1.0" encoding="utf-8"?>
<Language Key="00000809-0000-0000-0000-000000000000" Alias="en-GB" Level="0">
  <IsoCode>en-GB</IsoCode>
  <IsMandatory>false</IsMandatory>
  <IsDefault>true</IsDefault>
</Language>
```

then on a fresh install it works.
