### ISSUE TITLE
Content file names not syncing properly

### ISSUE THREAD

**Issue by EricOropezaelwood** [KevinJump/uSync8#473]
**Describe the bug**
When renaming or deleting a Content page or Template we are unable to get those changes to sync correctly to another environment

**To Reproduce**

1. In one env, Go to Content
2. Click on a section and edit the name and save the change
3. Open uSync under Settings
4. Click "Export"
5. In other env, Open uSync under Settings
6. Click "Import"
7. uSync is not aware of the name change so importing does not know to change or delete the altered file

**Expected behavior**
We expect to be able to change or delete a file name under Content, export the change and see the name change in the other environment where we run the Import

**About your Site (please complete the following information):**
 - Umbraco Version: 11.0.0
 - uSync Version: 11.0.0
 - Browser: chrome

**Additional context**
Out setup is 3 different environments in Azure. All the environments mount the same file share. So Exporting and Importing is connected to the single file share

**Comment by KevinJump** [comment]
Hi, 

If your sites are sharing their folder does that mean they are all pointing to the same server (so have the same connection string) ? - If so then any update to one will be automatically replicated onto the other two by Umbraco - but this means all three will just be acting as one site load balanced.

**Comment by EricOropezaelwood** [comment]
Hey there,

So we have the setup as laid out here: https://docs.umbraco.com/umbraco-cms/fundamentals/setup/server-setup/load-balancing. Then there is Umbraco running on their own Web Apps in each environment and with only the uSync folder mounted to a single file share. Each app has it's own database as well

**Comment by EricOropezaelwood** [comment]
we removed these settings from our appsettings.json and it seemed to fix it:

`
"uSync": {
  "Settings": {
    "ImportOnFirstBoot": false,
    "ExportOnSave": "None"
  }
}
`
