### ISSUE TITLE
Very Slow import

### ISSUE THREAD

**Issue by avialonn** [KevinJump/uSync8#474]
Hi Guys,
I have an umbraco 10.3.2 with 25K nodes. 
Any small change inn development can take min of 3 hours to import. 
Ive tried using Debug mode but cant see anything suspicious.
I have to say that if I change it directly on the prod it takes time.
We are on azure with very good resources. 
Any input will be much appreciated!
AA

**Comment by KevinJump** [comment]
Hi, 

Yeah if you make certain changes to doctypes (property changes) on a site with lots of content then Umbraco fires internal events that trigger updates to all the content items (lots of SQL in that) - unfortunately isn't something we can stop in uSync.

But you might want to check if you have anything listening for ContentSaved/ContentPublished events, and see if there is any optimisations / ignoring you can do in them, as often that is where we see the bottlenecks on large updates.
