### ISSUE TITLE
Usync with non-umbraco data

### ISSUE THREAD

**Issue by krebil** [KevinJump/uSync8#479]
It's not clear to me from reading the docs, if this is easily achievable.

Is there a straightforward way create a handler for custom data that lives in it's own table?
In my usecase it's not an umbraco entity.

**Comment by KevinJump** [comment]
Hi, 

yes it is possible, (although as you say not very documented!). 

_*Vendr usync does this and has non-entity types. (https://github.com/vendrhub/vendr-usync/tree/v2/dev/src/Vendr.uSync)_ 

- You need to implement a handler (that implements `ISyncHandler` )
- and a serializer (`ISyncSerializer`)

Handlers are what handle events (like Saved and deleted if you fire them) and reading things to and from disk (so getting the XML entities).

Serializers handle streaming the content to and from XML (`XElement`). 

The "simplest" way should be to inherit the `SyncHandlerRoot` and implement the abstract methods. 
https://github.com/KevinJump/uSync/blob/v11/dev/uSync.BackOffice/SyncHandlers/SyncHandlerRoot.cs

and for serializers if you do the same with `SyncSerializerRoot`. 
https://github.com/KevinJump/uSync/blob/v11/dev/uSync.Core/Serialization/SyncSerializerRoot.cs

Implimenting the required methods in these two should mean you don't need to write a lot of boilerplate, reading etc. 

_these root classes **don't** require your object to be inherit `IUmbracoEntity`_

**Comment by krebil** [comment]
Nice, thanks a lot!
