### ISSUE TITLE
Feature: Wildcard / RegEx the DoNoSerialize property.

### ISSUE THREAD

**Issue by KevinJump** [KevinJump/uSync8#483]
At the moment you can tell uSync not to serialize any property in a content / media element by used the "DoNoSerialize" property

e.g in the `appsettings.json` file :

```json
"uSync": {
    "Sets" : {
        "Default" : {
            "HandlerDefaults" :{
                "Settings": {
                     "DoNotSerialize" : "serverName"
                }
            }
        }
    }
}
```

but this mean you have to exactly match the property name you want to exclude. 
you might want to exclude a range of properties or have a naming convention for local only properties. so it would be better if this property could use wildcards (e.g `*_local`) or regEx expressions when checking properties.

**Comment by mayhammf** [comment]
Thanks @KevinJump. This would make things much easier.

**Comment by KevinJump** [comment]
in v10.6 and v11.2
