### ISSUE TITLE
Compare remote UI not displaying 

### ISSUE THREAD

**Issue by mayhammf** [KevinJump/uSync8#489]
**Describe the bug**
Right click on the  content section headline and click compare remote, nothing happens in the UI and an JS error is thrown

**To Reproduce**
1. Go to Content section
2. Right click on Content (the section headline)
3. Click "Compare remote" in the content panel
4. Nothing happens, and JS error is thrown "Cannot read properties of null (reading 'then') at Object.openCompareContent"

**Expected behavior**
The compare remote UI is displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/5937658/229040891-784d262e-d286-4afa-ba91-91527725dfa7.png)
<img width="528" alt="image" src="https://user-images.githubusercontent.com/5937658/229041040-ef62466e-9038-4232-a739-16aba02d328f.png">

**About your Site (please complete the following information):**
 - Umbraco Version: 10.4.1
 - uSync Version:  (current latest for Umb10)
	- uSync: 10.3.4
	- uSync.Complete: 10.4.1
	- uSync.Forms: 10.0.1
 - Browser Chrome 

**Additional context**
N/A

**Comment by KevinJump** [comment]
Yeah - that menu item shouldn't appear on the 'Content' node (or it should redirect to the "Remote" dashboard tab). 

The compare on the menu is expecting a content node to compare too. 

We will fix and remove this option from the top level node.

**Comment by KevinJump** [comment]
Fixed - for next release of uSync.Complete (v10/v11)
https://github.com/Jumoo/uSync.Complete.Issues/issues/198
