### ISSUE TITLE
Content dashboard shows "Media"

### ISSUE THREAD

**Issue by LennardF1989** [KevinJump/uSync8#492]
Admitedly a very VERY minor issue, but I noticed that the dashboard to pull back content shows "Media" in the breadcrumb (v11.0.2) instead of "Content".

![image](https://user-images.githubusercontent.com/869973/229472336-1e06592d-8dbc-4067-8e76-14ccf0c97a2c.png)

**Comment by KevinJump** [comment]
Thanks, is now fixed for the next release
