### ISSUE TITLE
Download exportet files fail

### ISSUE THREAD

**Issue by a-t-k** [KevinJump/uSync8#501]
**Describe the bug**
When i do klick on "download" button, after i did "export to file" feature, backoffice throw a exception:

**ExceptionMessage:** "~/../../CmsContent/Items/"
**ExceptionType:** "System.IO.DirectoryNotFoundException, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
**StackTrace:** 
"   at uSync.BackOffice.uSyncService.CompressFolder(String folder)\r\n   at uSync.BackOffice.Controllers.uSyncDashboardApiController.DownloadExport()\r\n   at lambda_method22526(Closure, Object, Object[])\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)"

**To Reproduce**
1. Set "Root folder" in appsettings.json to "~/../../<yourfolder>/<yourfolder>/
2. make sure the folder exists.
3. Go to Setting -> uSync feature in backoffice 
4. Click on "Everything -> Export -> Export to file.
5. Weit til export is done and donwload buttot come to view.
6. Click in the button "download"

**Expected behavior**
user get "Downloadfile"

**Screenshots**
no need

**About your Site (please complete the following information):**
 - Umbraco Version: 11.3.0
 - uSync Version: v11.1.0
 - Browser [chrome]

**Additional context**
no

**Comment by KevinJump** [comment]
Nightly build with fix available : ~https://dev.azure.com/jumoo/Public/_artifacts/feed/nightly/NuGet/uSync/overview/11.1.0-build.20230329.5~ 

update with the right link ! 

https://dev.azure.com/jumoo/Public/_artifacts/feed/nightly/NuGet/uSync/overview/11.2.1-build.20230513.1
