### ISSUE TITLE
[Umbraco 8.18.8 / uSync 8.11.0] Published content pulled in with draft dependencies 

### ISSUE THREAD

**Issue by LennardF1989** [KevinJump/uSync8#503]
**Describe the bug**
Hard to summarize in a title, but this one has been a massive headache and this morning it struck me what might be going on. Lets just go to the reproduction to make clear what is happening.

**To Reproduce**
1. Create a doctype with a media picker and a textstring
2. Create a root node with this doctype and assign image "A" to the media picker, set the textstring to "A", publish the page.
3. Spin up a second instance with the same doctype.
4. Pull in the content of the other instance (don't go through with it, just wait for the report). It will mention image A will be created. The page will contain the contents of your textstring.
5. Go back to the first instance, now assign image "B" and set the textstring to "B". Save the page, but don't publish it!
6. Go back to the second instance, pull in the content and wait for the report. It will mention image B will created, but the textstring is still set to "A".

Alternative path:
- Add two media pickers
- Assign the first image "A". Save and publish.
- Assign the other image "B". Save (not publish).
- Pull in content on other instance. Both Image "A" and "B" will be created, but content-wise you will only see the first media picker assigned.

The same also happens for dependencies in a grid. So it looks like it's an overarching issue for dependencies.

**Expected behavior**
Either:
- Draft content is synced in full, and thus I expect Image B and Textstring B.
- Published content is synced in full, and thus I expect Image A and Textstring A.

Right now, it's unclear what should be the intended situation, but it's broken. Somewhere in the process published and draft content is mixed.

Not sure if this is a known bug and fixed in later versions.

![A](https://github.com/KevinJump/uSync/assets/869973/7324de6e-6be6-48cc-9932-79198392ccdb)
![B](https://github.com/KevinJump/uSync/assets/869973/92e72ee9-aa39-4c56-bb65-fa26f0f26bd9)

**Comment by KevinJump** [comment]
Yeah - its should all be published (so In your case it should be Image A, text A 

The content is being pulled from publish, but quick look and the dependency check is being done against edited values (so draft). 

Progress. 

- [x] Fixed in v11 (will be in v11.2.0)
- [x] Fixed in v10 (will be in v10.6)
- [x] Fixed in v8 (will be in v8.11.13)

**Comment by KevinJump** [comment]
fixed for next release(s)

**Comment by LennardF1989** [comment]
Awesome! So just to be clear, the commits you just did only adjust an enum, but the logic that also needed fixing is in the closed-source CompleteEdition?

**Comment by KevinJump** [comment]
Yes - there was also a fix required in uSync.Complete for each version and that has also been done. 

it will be wrapped into the next release for each version - but we don't have a date for that just now _(we usually see if there are any Umbraco releases due out - so we can check them at the same time, but their isn't one for v8 atm)_

there is a nightly build of v8 if you want to try this version out 
https://dev.azure.com/jumoo/Public/_artifacts/feed/nightly/NuGet/uSync.Complete/overview/8.11.13-build.20230516.1
