### ISSUE TITLE
USync seems to not be working in version 12.0.1

### ISSUE THREAD

**Issue by nikcio** [KevinJump/uSync8#509]
**Describe the bug**
Hey, I have an integration test project where I test my Umbraco package. It runs with uSync with Firstboot to setup the content but when updating Umbraco to v12 and uSync from v11.2.1 to v12.0.1 uSync seems to stop working. I have a branch where you can test it out if you like. The setup is all in memory so it's easy to spin up 😄 

**To Reproduce**
1. Go to https://github.com/nikcio/Nikcio.UHeadless/pull/188
2. Pull the branch
3. Open `src/NikcioUHeadless.sln`
4. Start `Nikcio.UHeadless.IntegrationTests.TestProject`
5. The content should be imported on startup with the first boot but isn't.
6. If you go and manually import everything no content is imported.

**Screenshots**
In uSync v11.2.1 & Umbraco v12
![image](https://github.com/KevinJump/uSync/assets/24605285/28281781-bdfb-48e5-9402-f5718355ff85)

In uSync v12.0.1 & Umbraco v12
On boot.
![image](https://github.com/KevinJump/uSync/assets/24605285/f8a8d7f9-e36e-439e-bd4a-7b33a2c91020)

Import
![image](https://github.com/KevinJump/uSync/assets/24605285/1134887e-2499-42c3-8863-0e7623a71b95)
After the import even if you refresh the content tab there's nothing

**About your Site (please complete the following information):**
 - Umbraco Version: 12.0.0
 - uSync Version: 12.0.1
 - Browser Chrome

**Comment by nikcio** [comment]
Btw sorry it's a bit broad I didn't have the time to troubleshoot myself yet😅

**Comment by KevinJump** [comment]
DOH! 12.0.1 was meant to fix that but I missed the first boot bit.

(At least I know what I did).

Thanks - I will use your repo to get it working locally and I suppose we go to 12.0.2

**Comment by KevinJump** [comment]
12.0.2 - passes the tests now. (and appears to actually work on firstboot)

https://www.nuget.org/packages/uSync/12.0.2

Silly mistake 🤦 , I have a larger bit of code lines up, but not pushing it until after holidays now.
