### ISSUE TITLE
Language names aren't being replicated

### ISSUE THREAD

**Issue by anthony-3chillies** [KevinJump/uSync8#512]
**Describe the bug**
I've been through and have renamed our languages to group them by their country. 
However language names aren't being output in the XML and therefore also not being imported.

**To Reproduce**
1. Create Language in settings - English (Canada)
2. Set Language name to - Canada (English)
3. Export settings in uSync 
4. Check XML and the updated name isn't tracked.

**Expected behavior**
Language names to appear in XML and be reflected on import.

**About your Site (please complete the following information):**
 - Umbraco Version: 11.4.2
 - uSync Version: 11.2.1

**Comment by KevinJump** [comment]
HI, 

thanks for the report, we will look into this .

**Comment by KevinJump** [comment]
Turns out we missed this, will get it into the next releases ASAP.

**Comment by KevinJump** [comment]
released in v10.6.2 and v12.1.0
