### ISSUE TITLE
uSync Fails to import long umbraco.checkboxlist

### ISSUE THREAD

**Issue by craigs100** [KevinJump/uSync8#533]
**Describe the bug**
Umb 11.2.2, uSync V11.2.1, uSyncforms 10.0.1.0

On import, uSync gives the following error for every page with this particular umbraco.checkboxlist property editor which has 91 checkboxes.  The live web site appears to have no problem with it and appears to export ok. But when importing it into local dev, it fails with this:-

String or binary data would be truncated in table 'SE11_2023.dbo.umbracoPropertyData', column 'varcharValue'. Truncated value: '[
  "Bath",
  "BBQ Grill",
  "BBQ Utensils",
  "Bed linen",
  "Carbon monoxide alarm",
  "Cleaning p'.
The statement has been terminated.

**To Reproduce**
Build an Umbraco site with the versions and packages described above. Add a 91 (12 would probably do!) item umbraco.checkbox property editor to a page and check at least 10 items.
Export everything with uSync.
Build another blank site and import the exported content

**Expected behavior**
Clean import

**Screenshots**
![image](https://github.com/KevinJump/uSync/assets/1143883/e94809a7-596f-4a66-bc4d-b8d1ed3e2ed2)

**About your Site (please complete the following information):**
 - Umbraco Version: 11.2.2
 - uSync Version: 11.2.1
 - Browser [e.g. chrome, safari] Brave

**Additional context**
DB is MSSQL 2019

**Comment by KevinJump** [comment]
Hi, 

Is it possible that the live site has had its tables modified ? 

looking at the umbraco core the varvarchar property is a varchar column of length 512. (on MsSQL) so guessing that with 92 items the truncation is happening here ? 

the error is coming direct from the umbraco API when this happens - so just guessing there might have been a fix put in at somepoint in the past on the db for the live site. when you pull it down into a new db that isn't there and it throws the error ?

**Comment by craigs100** [comment]
Interesting. The site is an upgraded site but it hasn't had any other DB changes apart from those under the control of the Umbraco upgrade process.

The web site is fine showing all the checkbox results, so it must be holding the data ok. An example would be the amenities section here: https://stewartsestates.co.uk/holidays/list/beautiful-2br-converted-cow-shed-sleeps-4-bramble-farm-stable/?type=holidays It holds all 91 options in the dataType but only outputs the ones the editor selects. And as you can see they select quite a few.  So, are we saying the truncation is occurring when uSync calls the Umbraco API, so it would be an Umbraco issue? If it is, I'll go and bother them instead ;)

**Comment by KevinJump** [comment]
I would first confirm this on a clean install - so we can remove and confusion to the cause.

But to confirm 
- it is the Limit on the column being 512, 
- I am almost certain that at some point in the past that has been altered on your website. 
- The solution is probably to alter it on your local site (or use SQLite as that defines these values as TEXT)
    _- You could add a migration to the code to do this, so when devs pull it down it happens for them_

In terms of replicating the issue with nothing installed - I've done that below. 

- v10.6.1 
- no addtional packages installed 
- MSSQL Local DB 

Method: 
- Create  a checkbox list with enough items to make the text in the checkboxes go over 512 characters . 
- create a doctype with the checkboxes on 
- create a content item, select all the checkboxes, save 

```
Microsoft.Data.SqlClient.SqlException (0x80131904): String or binary data would be truncated in table 'C:\SOURCE\TESTING\UMBRACO\10\CHECKBOXTESTING\UMBRACO\DATA\UMBRACO.MDF.dbo.umbracoPropertyData', column 'varcharValue'. Truncated value: '["Checkbox Item Number 1","Checkbox Item Number 2","Checkbox Item Number 3","Checkbox Item Number 4"'.
The statement has been terminated.
```

![image](https://github.com/KevinJump/uSync/assets/431231/5e597b64-6b9b-43d8-8ced-3b458a0abc77)

**Comment by KevinJump** [comment]
Bonus. 

The issue already exists : https://github.com/umbraco/Umbraco-CMS/issues/12284

**Comment by craigs100** [comment]
On a fresh Umbraco install I can confirm that the checkboxes import ok with the site backed by SQLite but still fails with a fresh SQLServer 2019 DB
