### ISSUE TITLE
uSync Complete 12.2.0 cannot Pull Settings

### ISSUE THREAD

**Issue by jrunestone** [KevinJump/uSync8#559]
**Describe the bug**
After updating to uSync Complete 12.2.0 I'm getting the following error when I choose "Pull settings" on my configured server:

`Request error: The URL returned a 404 (not found):`
`/App_Plugins/uSyncPublisher/publishers/Realtime/configPull.html`

Downgrading uSync Complete to 12.1.0 makes it work again.

**To Reproduce**
Click "Pull Settings" on your configured server:

![image](https://github.com/KevinJump/uSync/assets/2293001/a8c6c749-0e82-4974-8855-0aeaa78649ae)

![image](https://github.com/KevinJump/uSync/assets/2293001/44b99d1e-243d-43e1-b68a-ab45afc54755)

**Expected behavior**

**Screenshots**

**About your Site (please complete the following information):**
 - Umbraco Version: 12.2.0
 - uSync Version: 12.2.0 Complete
 - Browser [e.g. chrome, safari]: chrome

**Additional context**

**Comment by KevinJump** [comment]
Hi,

Wonder if It might be a browser/umbraco caching issue this? It works for me on v12.2 - and i don't think we've actually changes the files behind that section in a while. 🤔 

are you on Linux or windows (wondering out loud if its a casing issue?)

**Comment by skttl** [comment]
I just had a collegue (using a Mac) running into this too. Could very well be a casing issue.
![image](https://github.com/KevinJump/uSync/assets/3726467/80fa2865-c2bc-479e-b780-bd48ab1057f2)

Umbraco 12.2.0 - uSync Complete 12.2.1 - Browser Chrome on Mac

**Comment by KevinJump** [comment]
Git blame is a lovely thing 

![image](https://github.com/KevinJump/uSync/assets/431231/4df913e9-ee16-4580-a2de-319cd01d1cfb)

It was me. 😞 

v12.2.1.1 - released with this fix in it. 

https://www.nuget.org/packages/uSync.Complete/12.2.1.1

**Comment by jrunestone** [comment]
Great thanks for finding and fixing it!
