### ISSUE TITLE
Sync Content WITHOUT syncing media

### ISSUE THREAD

**Issue by jessicaw-iology** [KevinJump/uSync8#561]
Syncing media takes FOREVER. There are many times when I need to sync content but don't need to sync media. However there is no clear option to sync content without syncing media. Please figure out how to make these separate functionalities. The time being wasted here is incredible. I am using Umbraco 10.

**Comment by KevinJump** [comment]
https://docs.jumoo.co.uk/usync/10.x/reference/handlers#disable-individual-handlers

specifically to disable media : 

```json
"uSync" : {
    "Sets" :{
        "Default" : {
            "DisabledHandlers" : ["MediaHandler"]
        }
    }
}
```

**Comment by jessicaw-iology** [comment]
Thanks but my suggestion wasn't to be able to disable media, but to be able to sometimes sync media and other times not.

**Comment by KevinJump** [comment]
Yeah - on the basic uSync it has been split into settings & content for simplicity, 

You can define extra sets, that would have only content / media in them - which you could then pick from the set dropdown that would appear. (see https://github.com/KevinJump/uSync/issues/384) - _requires a bit of code to setup the config_

--- 
With uSync.Complete and publisher there is a UI that allows you to select media, or not when you are pushing / pulling between servers. 

![image](https://github.com/KevinJump/uSync/assets/431231/7ae1f61e-3133-4bb8-8b60-00ba2a8e75c3)
