### ISSUE TITLE
Chaning Datatype to one configured in app_plugins may not work.

### ISSUE THREAD

**Issue by KevinJump** [KevinJump/uSync8#562]
If you have a datatype of type x (e.g nested content) and you want to change it to a custom type - that has been defined in a package.manifest file. then this change may not happen. 

I am not qutie sure why. but the list of data editors in umbraco does not (always) load custom property editors when they are defined in app_plugins. 

when we then attempt to set the editor alias based on the know datatypes - the new type isn't found.

**Comment by KevinJump** [comment]
The propertyEditors collection does contain the type - but this is a lesser list (it doesn't contain disabled or obsoleted datatypes) - so we are doing a fallback, check the DataEditors if its blank check the PropertyEditors, if that's blank then well its missing.

**Comment by NikRimington** [comment]
@KevinJump was this fix filtered back to the v10 version by any chance? I've noticed what I believe to be this same issue in a v10.7 site where we have multiple custom property editors but they are being converted to "label" instead of the custom type which is defined in app_plugins package manifests.

**Comment by KevinJump** [comment]
Hi, 

No - but it has now, 

nightly with it in https://dev.azure.com/jumoo/Public/_artifacts/feed/nightly/NuGet/uSync/overview/10.7.2-build.20231128.1

I will have a look at the change history, and work out if we are ready for a point release.

**Comment by NikRimington** [comment]
You are a super star, thank you!
