### ISSUE TITLE
Import settings - Contenttype - The incoming request has too many parameters

### ISSUE THREAD

**Issue by thomashdk** [KevinJump/uSync8#565]
When Importing the settings - Contenttype I get this error:

`Error: The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.
`
Config file as text file
[9dce5865-c26a-45ad-b1b5-2fc3b24c6d7d.txt](https://github.com/KevinJump/uSync/files/13289978/9dce5865-c26a-45ad-b1b5-2fc3b24c6d7d.txt)

**Screenshots**
![image](https://github.com/KevinJump/uSync/assets/6445636/35a80669-e3eb-4f58-99f8-0f5bdfbadf4f)

**About your Site (please complete the following information):**
 - Umbraco Version: 11.5.0
 - uSync Version: 11.2.1

I have a couple of solutions running on same code base on same server. Some of the are importing just fine.

My config:

`"uSync": {
    "Sets": {
      "Default": {
        "DisabledHandlers": [ "contentHandler", "mediaHandler", "domainHandler", "languageHandler"],
        "HandlerDefaults": {
          "GuidNames": true
        },
        "Handlers": {
          "DictionaryHandler": {
            "Group": "Settings"
          }
        }
      }
    },
    "Settings": {
      "AddOnPing": false,
      "ImportAtStartup": "None",
      "ImportOnFirstBoot": false,
      "UIEnabledGroups": "Settings",
      "ExportOnSave": "Settings"
    }
  }`

**Comment by thomashdk** [comment]
Anyone that know how to ge around this ?

**Comment by KevinJump** [comment]
Hi, 

I think this is probilbly buried in Umbraco somewhere - my best guess is when you are changing a document type that is used on over 2100 pages ? 

(is there any more information in the    

uSync requests don't have many parmaters, all the code goes into a 'ImportHandler' request, and then the code loops through each individual item, **but** when a content type is changes, umbraco events fire, and Umbraco performs some code internally to update things like content pages that use the content type - so at that point lots of things might be getting updated. 

I would see if there is anything in the logs. 

Having a quick look i thinbk this is the same as these Umbraco issues: 

- https://github.com/umbraco/Umbraco-CMS/pull/12569
- https://github.com/umbraco/Umbraco-CMS/issues/8648

Not sure if its being fixed, but the threads of these issues might shed some light on it.
