### ISSUE TITLE
Dictionary items empty after language change

### ISSUE THREAD

**Issue by rbottema** [KevinJump/uSync8#568]
**Describe the bug**
After replacing existing languages in Umbraco with new languages, importing this on another environment causes all dictionary items to be empty.

**To Reproduce**
1. Set up Umbraco with languages `en-US` and `nl-NL`
2. Create and fill dictionary items, ensure it's exported to uSync
3. Deploy to an environment and uSync import, ensure everything is there
4. Change Umbraco to add languages `en` and `nl`, and remove `en-US` and `nl-NL`.
5. Re-save (and re-fill) all dictionary items, ensure it's exported to uSync
6. Deploy to the same environment as previous and uSync import

**Expected behavior**
All dictionary items are updated and filled with the new values.

**Actual behavior**
All dictionary items are empty.

**About your Site (please complete the following information):**
 - Umbraco Version: 12.2.0
 - uSync Version: 12.2.0
 - Browser: Chrome

**Additional context**
uSync import/report shows no changes after the initial run, even though all dictionary items are empty. Deleting all dictionary items and running another uSync import does result in expected behavior.

**Comment by KevinJump** [comment]
OK hands up the person who changed the default for Dictionary items to be create only 🤦  🤚 

I will be fixed in the next release, you can fix this now, by setting the 'OneWay' behaviour to false by default.

```json
"uSync": {
    "Sets": {
      "Default": {
        "HandlerDefaults" :{
          "Settings": {
            "OneWay": "false"
          }
        }
      }
    }
  }
```
