### ISSUE TITLE
Choose what gets imported on first boot

### ISSUE THREAD

**Issue by deanleigh** [KevinJump/uSync8#569]
In UmBootstrap I have been importing all DocTypes and Content on first boot as the site is great for learning by example.
However, some people would like to use it as a starter kit and would prefer not to have the content, just a clean UmBootstrap.
Is there a way to exclude content on first Boot?
If there is can it be exposed to the dotnet new template config?

**Comment by KevinJump** [comment]
Indeed, there is.  

"FirstBootGroup"

```json
{
    "uSync": {
        "Settings": {
            "ImportOnFirstBoot": true,
            "FirstBootGroup": "Settings"
        }
    }
}
```

https://docs.jumoo.co.uk/usync/uSync/reference/Fundementals/firstboot/#firstboot-process

**Comment by KevinJump** [comment]
sorrry to add part two - I haven't looked at templates in a log time, i am not sure if you can change the appsettingsjson.config on boot (but i would guess you can)

**Comment by deanleigh** [comment]
> Indeed, there is.
> 
> "FirstBootGroup"
> 
> ```json
> {
>     "uSync": {
>         "Settings": {
>             "ImportOnFirstBoot": true,
>             "FirstBootGroup": "Settings"
>         }
>     }
> }
> ```
> 
> https://docs.jumoo.co.uk/usync/uSync/reference/Fundementals/firstboot/#firstboot-process

Perfect!
Thank you so much.

**Comment by deanleigh** [comment]
> sorrry to add part two - I haven't looked at templates in a log time, i am not sure if you can change the appsettingsjson.config on boot (but i would guess you can)

I think you can, I'll investigate further and let you know

**Comment by deanleigh** [comment]
Hi Kevin,
good news, we should be able to set o set the dotnet new package to configure the Usync settings in the cli - yay
However, on testing before we try in the template your suggestion works as expected except it does not seem to bring over perms e.g. Home Page loses its 'allow at root' perm.
I am basically trying to offer people using UmBootstrap the choice to run it with or without content
This is the code I currently have added:
"uSync": {
  "Settings": {
    "ImportAtStartup": "DocumentTypes",
    "ImportOnFirstBoot": true,
    "FirstBootGroup": "Settings"
  }
}
