### ISSUE TITLE
10.7.x introduces import bug for tokens formatted with curly brackets

### ISSUE THREAD

**Issue by sussexrick** [KevinJump/uSync8#573]
**Describe the bug**
We have properties where we enter a token that is replaced at runtime. The token is the entire content of the field. The token is `{{name}}`.

On Umbraco 10.6.1 and uSync 10.6.1 this worked fine. We upgraded to Umbraco 10.8.2 and uSync 10.7.1 and the `{{name}}` token started getting imported as the string `null`. We've downgraded to uSync 10.6.2 and it's importing correctly.

**To Reproduce**

1. Set up a project using Umbraco 10.8.1 and uSync Complete 10.7.1.
2. Create a document type with a property using the block list property editor. 
3. Create a block type with a textstring property in the content. 
4. Create a page based on the document type, and add a block with `{{name}}` in the text field.
5. Export the content and re-import it. The property content will be `null` instead of `{{name}}`.

**Comment by KevinJump** [comment]
Hi, 

Sorry this was fixed in v12/v13 and we forget to pull it back down to v10. 

fixed in v10.7.3 - https://www.nuget.org/packages/uSync/10.7.3
