### ISSUE TITLE
Inaccurate change report for data types

### ISSUE THREAD

**Issue by NikRimington** [KevinJump/uSync8#59]
Not sure if this is a bug or what exactly is going on, but on a few Umbraco v8 sites with uSync 8 installed (couple of different versions but 8.2.3 is included)

Data Types have been reporting that all of them have changed, however when examining them there are no actual changes that can be found. 

For example, this is directly after an import:

![image](https://user-images.githubusercontent.com/13313745/66750372-31328900-ee84-11e9-9fb6-664034d2c75a.png)

![image](https://user-images.githubusercontent.com/13313745/66750460-722a9d80-ee84-11e9-91ce-63f3117a2040.png)

![image](https://user-images.githubusercontent.com/13313745/66750486-7c4c9c00-ee84-11e9-8835-f95966e5a6f5.png)

It appears that it is trying up date sort orders, but no idea why.

These examples are from a v8.1.5 site.

It's a bit misleading seeing lots of changes that aren't "real" when doing a deployment, not sure what is causing it.

**Comment by KevinJump** [comment]
yeah - I think it's to do with whitespace within the value fields within the XML, I need to have a look and do some cleaning up either before the values are written out (preferred) or on compare.

**Comment by KevinJump** [comment]
In next release **8.2.4**
