### ISSUE TITLE
Import Everything fails for some files with Error: Value cannot be null

### ISSUE THREAD

**Issue by ghost** [KevinJump/uSync8#590]
First of all - thank you for such an amazing open souce  product 😊

**Describe the bug**
I am having issue with importing some specific document types into Umbraco. Im running Umbraco `v13.1.1` and uSync `v13/main`. When I cleanup everything (database and filesystem) and I run Import everything I get an error saying `Value cannot be null. (Parameter 'source')`.

<img width="248" alt="errorParameterNull" src="https://github.com/KevinJump/uSync/assets/80673797/54f9136a-4b2a-4d42-b334-6a296b88a563">

If I try many many times, it sometimes succeeds. I couldn't figure out the order, but eventually the import succeeds. I was trying combining Import Everything, Full import, first Settings and then Content.....

I hooked up the debugger in the source of uSync. It turns out that the error always occurs when calling Second Pass import
<img width="314" alt="secondpass fail" src="https://github.com/KevinJump/uSync/assets/80673797/2a0a28d2-1ae7-433a-bbd2-5f9895a7e08b">

The issue seems to be in line `\uSync.BackOffice\SyncHandlers\SyncHandlerRoot.cs@541`
<img width="521" alt="SyncHandlerRoot ImportElement" src="https://github.com/KevinJump/uSync/assets/80673797/26bd76af-5784-4178-a791-8736cfbfd85a">
Here `action.Details` doesn't get anything assigned, because `attempt.Details` is an empty list. This the causes an exception in method `PerformSecondPassImports` `\uSync.BackOffice\SyncHandlers\SyncHandlerRoot.cs@584` which doesn't check for null.
<img width="707" alt="productdescriptionconfigurationroot" src="https://github.com/KevinJump/uSync/assets/80673797/db566719-ed33-472a-92de-3b76e0d96d9a">

Having a look at the importing item shows that this happens for items, that don't have any content, because they are meant to be some kind of root items only for defining their children types. 

Here is the sample file that fails:
```
<?xml version="1.0" encoding="utf-8"?>
<ContentType Key="97e349a0-18aa-4d0a-af12-a5a961469ff5" Alias="productDescriptionConfigurationRoot" Level="5">
  <Info>
    <Name>Product Description - Configuration Root</Name>
    <Icon>icon-info color-black</Icon>
    <Thumbnail>folder.png</Thumbnail>
    <Description></Description>
    <AllowAtRoot>False</AllowAtRoot>
    <IsListView>True</IsListView>
    <Variations>Culture</Variations>
    <IsElement>false</IsElement>
    <HistoryCleanup>
      <PreventCleanup>False</PreventCleanup>
      <KeepAllVersionsNewerThanDays></KeepAllVersionsNewerThanDays>
      <KeepLatestVersionPerDayForDays></KeepLatestVersionPerDayForDays>
    </HistoryCleanup>
    <Folder>Feature/ProductDescription/Configuration</Folder>
    <Compositions />
    <DefaultTemplate></DefaultTemplate>
    <AllowedTemplates />
  </Info>
  <Structure>
    <ContentType Key="3a5bf69d-08cb-4252-8c66-b68fa1c7ddc5" SortOrder="0">productDescriptionConfiguration</ContentType>
  </Structure>
  <GenericProperties />
  <Tabs />
</ContentType>
```

Did we somehow break the files on the way or should all files have some properties defined or what am I doing wrong?

**Expected behavior**
I would expect that import would not fail for items with no properties

**About your Site (please complete the following information):**
 - Umbraco Version: **13.1.1**
 - uSync Version: manual build from branch **v13/main** (latest commit ae5a631)
 - Browser: **Chrome**

**Comment by KevinJump** [comment]
Hi, 

If possible can you send me a copy of the uSync folder? (email kevin@jumoo.co.uk) and i will take a look, 

Kevin

**Comment by KevinJump** [comment]
Hi, 

thanks for the files, which let us confirm that the fix we have just done is good for this issue 👍 .

v13.1.1 - is out and addresses this one.

https://www.nuget.org/packages/uSync/13.1.1

**Comment by ghost** [comment]
Wooo, that was fast!

Thank you very much!
