### ISSUE TITLE
Issue with Import from file

### ISSUE THREAD

**Issue by alexsolek** [KevinJump/uSync8#594]
**Describe the bug**
When using the import from file option, and after uploading a zip file, the Report and the Import buttons both result in a Report.

**To Reproduce**
1. Go to the Settings area in Umbraco CMS
2. Go to uSync
3. Click on Import from File
4. Upload a exported zip file and click upload
5. You will be presented with three options "Close", "Report", and "Import". Pressing Report or Import results in the same behaviour (a report)

**Expected behavior**
When pressing Report I should get a uSync report. When pressing Import, I should see uSync completing the import.

**Screenshots**
![image (9)](https://github.com/KevinJump/uSync/assets/109297814/4ac9684f-adad-4438-b725-9f29328562d1)

**About your Site (please complete the following information):**
 - Umbraco Version: 12.2.0
 - uSync Version: 12.2.0
 - Browser [e.g. chrome, safari] Chrome

**Comment by KevinJump** [comment]
Annoyingly small fix, will be in next v13/12/10
