### ISSUE TITLE
[BETA FEEDBACK] Pascal case names for DataTypes

### ISSUE THREAD

**Issue by JoseMarcenaro** [KevinJump/uSync8#596]
**Nightly build 14.0.0-build.20240307.8** 

Hi Kevin, I noticed the file naming convention for DataTypes changed from lowercase-with-hyphens to PascalCase.  Is this by design, or we should expect it to revert to the previous versions convention?

Thanks a lot! It's amazing to have it working already.

**Comment by JoseMarcenaro** [comment]
**Aditional info**

* I started from scratch (new database, no uSync)
* this time I installed `14.0.0-beta001` instead of the latest nightly build
* After building and launching Umbraco (*before* using the uSync dashboard) I got all the DataTypes files generated with lowercase-with-hyphens (as in previous versions)
* Saving an existing data type kept the lowercase file naming
* But using the *Export* button generated duplicate files for all data types, with the PascalCase naming convention.

Thanks in advance.

**Comment by KevinJump** [comment]
Hi, 

Did you have any previous files in the install? 

my files are generated pascal, from a clean install, but that is actually how they are generated on previous versions (e.g. a v9 folder has `ApprovedColour.config` 

there is a camel / pascal naming thing for the properties inside a doctype, but we do convert that on import, so from old it will in theory work (but we don't support dropping a v9 folder into the beta yet.

**Comment by JoseMarcenaro** [comment]
Hi,
I did not have any previous files in the install, no uSync folder was present.
With uSync 14.0.0-beta001, just installing the package and running Umbrago generated the **lowercase** FileTypes files.
And then pressing the `Export` button generated duplicated files in PascalCase  (whenever the name is not the same because of the hyphens)

I can follow up in the code and try to find/fix the issue - if it is appropriate at this early stage. Please let me know. Thanks.

**Comment by KevinJump** [comment]
Hi, If you think you can find the issue in the code that would help lots.

**Comment by JoseMarcenaro** [comment]
Hi @KevinJump  - I can no longer reproduce the issue.

* I built a site from scratch, then run it with a reference to your source code in v14/dev (fork), and the DataTypes files where generated correctly (PascalCase)
* Did the same (on a new site) using the v14.0.0-beta001 nuget package, with the same results.

So something must have gone wrong in my previous attempts.  Closing the issue.

**Comment by JoseMarcenaro** [comment]
@KevinJump I found out when this inconsistent behavior happens:

**When UseFlatStructure = false**
*  The initial files generation (when installing uSync and running Umbraco) uses lowercase-with-hyphens. And folders are honored. This is consistent with what v9 does (when UseFlatStructure = false).
* Saving an existing data type behaves the same way.
* But **the Export button ignores the UseFlatStructure** flag: names are PascalCase, folders are not honored, duplicated files appear all over the place.

I'm opening a separate ticket for this:  #599
