### ISSUE TITLE
Configuration fails to import with warning "startIndex cannot be larger than length of string. (Parameter 'startIndex')"

### ISSUE THREAD

**Issue by stephen-sherman** [KevinJump/uSync8#603]
**Describe the bug**

After deploying an Umbraco 12.0.1/uSync 12.0.2 => Umbraco 13.1.1/uSync 13.1.1 upgrade to a test environment, I noticed that uSync was failing to import on start up and when manually triggered, with a number of similar warnings in the Umbraco logs:

> System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string. (Parameter 'startIndex') at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length) at uSync.BackOffice.SyncHandlers.SyncHandlerRoot`2.ImportElement(XElement node, String filename, HandlerSettings settings, uSyncImportOptions options)

This issue was not apparent in the local development environment (Windows), only in the test environment (Azure Linux Web App).

The only pattern I could detect in the items that were failing was that all of them had aliases of fewer than 10 characters. For example, **buttonListBlock**.config would import successfully, while **button**.config would not.

The uSync configuration has not been altered with the upgrade, and the solution is not using the new "Roots" feature. 

Downgrading uSync to version 13.0.1 appears to have worked around the issue.

Could there be some alias or file name manipulation going on in version 13.1.1 that is sensitive to file name length, folder structure, or hosting environment?

**Screenshots**

![import-error](https://github.com/KevinJump/uSync/assets/21112942/94be93ee-6c97-4df3-9a93-2b938a3ce5d7)

**About your Site (please complete the following information):**

 - Umbraco Version: 13.1.1
 - uSync Version: 13.1.1
 - Browser: Google Chrome 122.0.6261.113

**Additional context**

- Error occurred in remote Azure Linux Web App environment, but not in local Windows environment.

**Comment by KevinJump** [comment]
Hi, 

If possible, can you upgrade to uSync 13.1.2 

I am having a look at the code, we did tidy up some things around reporting file paths in 13.1.2 and we made this change 
https://github.com/KevinJump/uSync/commit/ab5a306ba91591cbb54946b905d851c33d32d395

and i am wondering if that fixed it. 

Kevin

**Comment by KevinJump** [comment]
Ho Sorry update, 

we've also just fixed another linux issue https://github.com/KevinJump/uSync/releases/tag/v13.1.3

so if you go to v13.1.3 that might fix both this and the other issue you where going to probibly run into at somepoint too.
