### ISSUE TITLE
uSync Not Exporting Forms with uSyncForms installed

### ISSUE THREAD

**Issue by craigs100** [KevinJump/uSync8#608]
Umb V13.2.2, UF V13.0.2, uSync V13.1.2, uSync Forms V13.0.0

With the above versions installed, uSync's Everything Export function does not export Forms.  To get forms back you have to export from the uSync Forms section and copy the uSync/V9/Forms folder on it's own. It is not included in Everything "Export to file" even after a clean Export.

Also noted it not importing prevalues of type Umbraco Document:-
`Error converting value "Category List" to type 'System.Guid'. Path '[0].fieldSets[2].containers[0].fields[0].prevalueSourceId'.`

Also noted when having FTP's the V9 folder up, form import fails with this strange anomaly of missing first letters.....

![image](https://github.com/KevinJump/uSync/assets/1143883/df8db003-041b-45e8-9b60-781777628e7c)

**Comment by KevinJump** [comment]
Fixed in 13.2 of uSync.Forms

**Comment by craigs100** [comment]
Tested, all good, thanks :)
