### ISSUE TITLE
Importing a default language fails if there is only one language

### ISSUE THREAD

**Issue by karlmacklin** [KevinJump/uSync8#609]
**Describe the bug**

If you have only one language and try to import a new language which is set to default, the import fails. You can somewhat avoid this by manually creating the language first, but this is problematic for setups where you rely on automation, so it isn't really a workaround.

**To Reproduce**

1. Create a new local Umbraco project using Umbraco.Cms version 13.2.2 and uSync 13.1.3.
2. Start Umbraco and create a new Language (other than english) under settings, setting it to the default language in the process. By now you should have two uSync language files, one updating the initial English one and your new default language.
3. Stop Umbraco
4. Delete your database (SQLite files for local dev for example)
5. Start Umbraco
6. Go to Settings > uSync and import Settings

**Expected behavior**

I expect the import to succeed, creating all relevant languages as a first step and afterwards altering which is the default one.

**Actual behavior**

Import fails, since it can't make english non-default as it is the only language in the system.

**Screenshot**

<img width="1119" alt="image" src="https://github.com/KevinJump/uSync/assets/353806/ac24262c-6fb2-4210-a1ac-21f99038ffb7">

**Comment by Luuk1983** [comment]
I can confirm that this works fine in uSync 13.0.1, but stopped working in 13.1.x+. Worst is that the content tree remains empty in my case with uSync 13.1.x. Not sure if it's related to this problem, but there is something really wrong with with 13.1.x in my case.

I set up a blank Umbraco 13.2.2 project in combination with a few uSync versions and uSync files from a project I'm having issues with. The uSync config is completely default (so I put no uSync config in the appSettings at all).

Dutch language file:
```
<?xml version="1.0" encoding="utf-8"?>
<Language Key="00000413-0000-0000-0000-000000000000" Alias="nl-NL" Level="0">
  <Name>Dutch (Netherlands)</Name>
  <IsoCode>nl-NL</IsoCode>
  <IsMandatory>false</IsMandatory>
  <IsDefault>true</IsDefault>
</Language>
```

English language file:
```
<?xml version="1.0" encoding="utf-8"?>
<Language Key="00000409-0000-0000-0000-000000000000" Alias="en-US" Level="0">
  <Name>English (United States)</Name>
  <IsoCode>en-US</IsoCode>
  <IsMandatory>false</IsMandatory>
  <IsDefault>false</IsDefault>
</Language>
```

### uSync 13.0.1:
![image](https://github.com/KevinJump/uSync/assets/9865589/a14d5513-9d42-4900-85aa-d3861e0eb949)

Content tree:
![image](https://github.com/KevinJump/uSync/assets/9865589/80eac444-17ee-4021-aa07-677683e4666e)

### uSync 13.1.0:
![image](https://github.com/KevinJump/uSync/assets/9865589/85acce91-be9b-45ae-91e0-3f286d823c45)
Full error: 
Cannot save the default language (en-US) as non-default. Make another language the default language instead.

Content tree:
![image](https://github.com/KevinJump/uSync/assets/9865589/92794ba7-b134-441c-8489-ba75b64e25af)
The weird thing is that the import says all content is imported correctly, but it simply does not show...
