### ISSUE TITLE
uSync Chauffeur for Umbraco 8

### ISSUE THREAD

**Issue by Box-Of-Hats** [KevinJump/uSync8#61]
Are there any plans to bring a command line solution for Usync and Umbraco 8?

I've read about chauffeur for Umbraco 7 and it sounds like something that would be very beneficial to have in 8

**Comment by KevinJump** [comment]
yes! - we wrote a deliverable for Chauffeur for Umbraco 7 and we've looked at it for v8. 

last time i checked chauffeur wasn't working for Umbraco 8.1 so it might be we will look at that, or roll a simpler uSync only command line (and their is a powershell umbraco project floating around somewhere). 

I'll put this on our to do list.

**Comment by Box-Of-Hats** [comment]
Cheers Kevin!
I'm a big command line advocate so this would be a huge boost to both my workflow and our dev pipelines

**Comment by KevinJump** [comment]
With version 8.5 we've released a beta of uSync.Command (which puts a usync.exe into the bin) - this isn't chauffuer, but is very close to how that works (i couldn't chauffeur working on later Umbraco builds). 

https://docs.jumoo.co.uk/uSync/command-line/

**Comment by Box-Of-Hats** [comment]
This looks great, Kevin. Thanks! :)
