### ISSUE TITLE
[BUG] Unable to apply an individual change

### ISSUE THREAD

**Issue by NikRimington** [KevinJump/uSync8#622]
**What package are you feeding back on** 
13.2.0

**Describe your feedback**
Apply Button on an individual change is not working.

**To Reproduce**
* Setup a site with a root directory and a modification directory - active site should be flagged as a child site and the root should not be locked. 
* Modify a data type, e.g. block list.
* Run a report and see the change being flagged as a "combined" item
* Attempt to "Apply" the individual change

**Expected behaviour**
I'd expect the changes to be imported.

**Screenshots**
![image](https://github.com/KevinJump/uSync/assets/13313745/5498fd6e-0fc2-4b67-834f-d301b6b22d58)

**Comment by KevinJump** [comment]
Ahh yes i know why that is 😞   *the file never actuall exists, it's all smoke and mirrors, and memory!*

I will take a look, i think we might have to add some of the magic to the button for roots.
