### ISSUE TITLE
[BUG] Child files created even when there are no changes

### ISSUE THREAD

**Issue by NikRimington** [KevinJump/uSync8#623]
**Describe the bug**
Doing a full export on a "child" site with roots unlocked creates a large number of files for document types that still match the root definition. I don't think it should create these files.

**To Reproduce**
1. Create a v13 site with a root set of uSync files and a child set of usync files
2. Ensure that the document types/data types match the expected final outcome and that some document types/data types differ from the root definition but not all
3. Goto the uSync dashboard
4. Run an Export on Settings
5. Review the files generated

**Expected behavior**
The Child directory should only contain files where the defintion needs to differ from the root.

**Screenshots**
All the files with an A indicator (examples circled in green) are basically placeholder files
Files with an M indicator are legitimate changes.
![image](https://github.com/KevinJump/uSync/assets/13313745/6f57bfbf-b823-40cd-b199-221d37e40d20)

Example of placeholder file:
![image](https://github.com/KevinJump/uSync/assets/13313745/2071de34-31e0-4d6c-ac6c-dcd2739f95fe)

**Additional context**
Not a major bug in practical terms, but is a large number of files in large sites it creates alot of file noise.

**Comment by KevinJump** [comment]
thanks, 

yes - i think on the things where we merge the properties there can (and does by the looks of it) end up with a empty 'stub' when its merged, 

we should just not save these if they have no children in the node.
