### ISSUE TITLE
 Item key [GUID] already exists for [File]

### ISSUE THREAD

**Issue by patrickdemooij9** [KevinJump/uSync8#634]
**Describe the bug**
Recently updated to the latest Umbraco version (13.3.0) and also updated uSync with it (along with a full export), but when I try to import them later on, it fails with the error: "Duplicate: Item Key [Guid] already exists for [File]. Check the uSync healthcheck for more info". But running the healthcheck shows that everything is correct.

**To Reproduce**
Not quite sure how to reproduce, but I was hoping that you had a general idea of what could be causing this. It seems like it is trying to add the datatype with given Guid even though it already exists?

**Expected behavior**
No errors

**About your Site (please complete the following information):**
 - Umbraco Version: 13.3.0
 - uSync Version: 13.2.1
 - Browser [e.g. chrome, safari]: Chrome
 - 
**Additional context**

**Comment by patrickdemooij9** [comment]
Oke, I think it must have still had an old file somewhere, I deleted the whole uSync folder and replaced it all with the new files and it worked. Not quite sure what happened, but it works now!

**Comment by KevinJump** [comment]
Hi, 
13.2.1 does fix an issue with a false error when there is a delete and a file on disk (so someone either detected or renamed a doctype or something).

but if you where are the latest this should have been fixed 🤔  - so if it does happen again, let me know.

**Comment by KevinJump** [comment]
hi see #635 i think we do have an issue with 'renamed' files which is why your clean export will have worked. 

just testing it now, and then 13.2.2 should fix it all again.
