### ISSUE TITLE
Unable to backup 'Restore Points' to Azure blob storage

### ISSUE THREAD

**Issue by brentheimer** [KevinJump/uSync8#636]
**Describe the bug**
Unable to find package `uSync.Complete.Restore.Azure`.

[Documentation](https://docs.jumoo.co.uk/usync/complete/guides/ResPoint/) and [blog](https://blog.jumoo.co.uk/2023/v12-restore-points/) indicates that `uSync.Complete`'s newer `Restore Points` feature can have data backed up to Azure blob storage via a package named `uSync.Complete.Restore.Azure`.
I can't find any indication of where this is, and don't see the example settings path `uSync:Restore:..` without that package in current version `13.1.3`.

**To Reproduce**
Look on github for package `uSync.Complete.Restore.Azure`

**Expected behavior**
Package is found.

**Comment by KevinJump** [comment]
Closing. as per other issue, we have now published the package at https://www.nuget.org/packages/uSync.Complete.Restore.Azure
