### ISSUE TITLE
Member composition not added to Member type on synching

### ISSUE THREAD

**Issue by ewuski** [KevinJump/uSync8#649]
**Describe the bug**
Member type composition is not being added to the member type on sync.

**To Reproduce**
1. Go to Settings > Member types and add a member type composition.
2. Go to a Member type and assign the newly added composition to the Member type.
3. Deploy the solution and sync the deployed solution (staging/production)
4. The member composition type is added under Member types. However, the Member type does not inherit the composition.
5. 5. The composition entry exists in the `member.config` with the correct composition key but the composition is not inherited in the Member type in the BO.

**Expected behaviour**
Member type should show the inherited properties of the member composition in the BO after synching.

**Screenshots**
<img width="904" alt="usync-13 2 3" src="https://github.com/KevinJump/uSync/assets/104149844/4e73c1c5-be81-4e63-bdf9-e4597cff737b">

**About your Site (please complete the following information):**
 - Umbraco Version: 13.2.1
 - uSync Version: 13.2.3
 - Browser [e.g. chrome, safari] Chrome, windows 10

**Comment by KevinJump** [comment]
fixed : will be in next release.

**Comment by KevinJump** [comment]
Fixed in uSync 13.2.4 : https://github.com/KevinJump/uSync/releases
