### ISSUE TITLE
Can't export dictionary items to sync pack

### ISSUE THREAD

**Issue by jrunestone** [KevinJump/uSync8#650]
Getting a null ref exception when trying to create a sync-pack of one or more dictionary items from the context menu in the tree. It works as expected when going through the main uSync settings section and exporting from there.

Not seeing anything in the logs unfortunately.

![image](https://github.com/KevinJump/uSync/assets/2293001/e3e890c5-8480-4e25-84a9-5d5a99a0150d)

**About your Site (please complete the following information):**
 - Umbraco Version: 13.3.2 
 - uSync Version: v13.2.3 + Exporter (v13.1.4), Snapshots (v13.1.4), PeopleEdition (v13.1.4), Publisher (v13.1.4), Complete (v13.1.4)
 - Browser all of them :)

**Comment by KevinJump** [comment]
Hi, 

Yes, this will be fixed for the next v13.x release.

**Comment by KevinJump** [comment]
Hi,
sorry slow to update this issue - but this was fixed in 13.1.5 release of uSync.Complete

**Comment by jrunestone** [comment]
Thanks!
