### ISSUE TITLE
v14: Include/exclude paths in appsettings seems to be ignored

### ISSUE THREAD

**Issue by RBerntsen** [KevinJump/uSync8#671]
Hi Kevin. Thanks for a great product! 

I'm trying out the include/exclude features for import and export of content and seem to have a few problems getting these to work properly.

**Describe the bug**
When having paths to content and media to include/exclude uSync seems to just ignore the paths and just export/import everything.

Testing on a clean installation of Umbraco 14.2.0 and uSync 14.0.0.

**To Reproduce**
Install Umbraco v14.2.0
Install uSync v14.0.0
Create a document type called Content Page. Allow at root and allow to create the same page as a child.

**Update appsettings** with the following configuration:
```
  "uSync": {
    "Settings": {
      "ExportOnSave": "All",
      "UIEnabledGroups": "All",
      "ImportAtStartup": "All"

    },
    "Sets": {
      "Default": {
        "DisabledHandlers": [ "MacroHandler", "LanguageHandler", "MemberTypeHandler", "TemplateHandler", "ContentTemplateHandler", "DomainHandler" ],
        "HandlerDefaults": {
          "Content": {
            "Include": "/Include/",
            "Exclude": "/Exclude/",
            "CreateOnly": false,
            "IgnoreAliases": "",
            "RulesOnExport": true,
            "ImportTrashed": false,
            "ExportTrashed": false
          },
          "Media": {
            "Include": "/Include/",
            "Exclude": "/Exclude/",
            "CreateOnly": false,
            "IgnoreAliases": "",
            "RulesOnExport": true,
            "ImportTrashed": false,
            "ExportTrashed": false
          },
          "Dictionary": {
            "CreateOnly": true
          }
        }
      }
    }
  }
```

Now try and create a content page called "Include" and a child below that called "IncludeChild". Do the same once again for "Exclude" and "ExcludeChild".

Create the same structure in Media using the "Folder" type.

Result will be 8 new config files, for both include and exclude files.

These are the files created that should not be created:

**Content**

```
<?xml version="1.0" encoding="utf-8"?>
<Content Key="125c0a1b-8da5-448c-a307-7c11df7b3d0c" Alias="Exclude" Level="1">
  <Info>
    <Parent Key="00000000-0000-0000-0000-000000000000"></Parent>
    <Path>/Exclude</Path>
    <Trashed>false</Trashed>
    <ContentType>contentPage</ContentType>
    <CreateDate>2024-09-11T15:59:10</CreateDate>
    <NodeName Default="Exclude" />
    <SortOrder>0</SortOrder>
    <Published Default="true" />
    <Schedule />
    <Template />
  </Info>
  <Properties />
</Content>
```

```
<?xml version="1.0" encoding="utf-8"?>
<Content Key="f46c3cb3-c52f-486d-be03-4359c36ba1c9" Alias="ExcludeChild" Level="2">
  <Info>
    <Parent Key="125c0a1b-8da5-448c-a307-7c11df7b3d0c">Exclude</Parent>
    <Path>/Exclude/ExcludeChild</Path>
    <Trashed>false</Trashed>
    <ContentType>contentPage</ContentType>
    <CreateDate>2024-09-11T16:07:48</CreateDate>
    <NodeName Default="ExcludeChild" />
    <SortOrder>0</SortOrder>
    <Published Default="false" />
    <Schedule />
    <Template />
  </Info>
  <Properties />
</Content>
```

**Media**
```
<?xml version="1.0" encoding="utf-8"?>
<Media Key="ada134c1-a1b8-4b00-a598-81aff5971290" Alias="Exclude" Level="1">
  <Info>
    <Parent Key="00000000-0000-0000-0000-000000000000"></Parent>
    <Path>/Exclude</Path>
    <Trashed>false</Trashed>
    <ContentType>Folder</ContentType>
    <CreateDate>2024-09-11T16:11:10</CreateDate>
    <NodeName Default="Exclude" />
    <SortOrder>1</SortOrder>
  </Info>
  <Properties />
</Media>
```

```
<?xml version="1.0" encoding="utf-8"?>
<Media Key="261379d2-9147-42e8-860b-3365df2375e6" Alias="ExcludeChild" Level="2">
  <Info>
    <Parent Key="ada134c1-a1b8-4b00-a598-81aff5971290">Exclude</Parent>
    <Path>/Exclude/ExcludeChild</Path>
    <Trashed>false</Trashed>
    <ContentType>Folder</ContentType>
    <CreateDate>2024-09-11T16:11:22</CreateDate>
    <NodeName Default="ExcludeChild" />
    <SortOrder>0</SortOrder>
  </Info>
  <Properties />
</Media>
```

**Expected behavior**
When I have configured that it should _only_ include from a specific path and furthermore also said that another path should specifically be ignored, then I would expect that to happen and no files created from "/exclude/".

I am not sure if this comes down to being configured incorrectly as I have some difficulties understanding exactly how to use this (especially now that it doesn't work).

**Comment by KevinJump** [comment]
Hi, 

Lets say setup of this is fiddly 😉  - we could certainly do better. 

I think a couple of settings are in the wrong place, so I've just checked this* and the following does work. 

```json
  "uSync": {
    "Sets": {
      "Default": {
        "Handlers": {
          "ContentHandler": {
            "Settings": {
              "Include": "/Include",
              "Exclude": "/Exclude",
              "RulesOnExport": "True"
            }
          }
        }
      }
    }
  }
```

docs: https://docs.jumoo.co.uk/usync/uSync/reference/handlers#handler-specific-settings

*worth noting i've just checked this on the just-about-to-release v14.2 version of uSync, but we haven't changed this bit between versions so i think it will be ok on the "current" release

**Comment by RBerntsen** [comment]
Hi @KevinJump - thanks for the quick follow up. This seems to be working for me now! 
I think the documentation for this part is a little difficult to understand, so maybe some more examples would be great here. :)

I just noticed the docs are in github, so I might look into creating a PR with some examples, if that's of any interest?

Thanks again!
