### ISSUE TITLE
Saving a Document Type or a Data Type once erase the <Folder> configuration

### ISSUE THREAD

**Issue by mdeslauriers-sigmund** [KevinJump/uSync8#673]
**Describe the bug**
When you save a document type, a media type or a data type, the exported xml config file contains no `<Folder></Folder>` tag.

**To Reproduce**
1. In the bcakoffice, create a folder "my-folder" under `Settings > Document Types`
2. Create a **Test doc type** in the folder
3. Take a look at de xml file exported in `\uSync\v14\ContentTypes\testdoctype.config`
4. See that the there is no information about the folder in the file.
5. Save the document type AGAIN
6. Take a look at de xml file exported in `\uSync\v14\ContentTypes\testdoctype.config`
7. See that the there is now a `<Folder>my-folder</Folder>` tag in ht file

**Expected behavior**
The first save should not erase the `<Folder></Folder>` tag.

**About your Site (please complete the following information):**
 - Umbraco Version: `14.2.0`
 - uSync Version: `14.2.1` 
 - Chrome/Firefox

**Comment by KevinJump** [comment]
Yep - found it, caused when we tidied up some caching stuff (its always caching)🤦  

fix is in v14.2.2 (https://www.nuget.org/packages/uSync/14.2.2)

**Comment by mdeslauriers-sigmund** [comment]
Thank you very much!
