### ISSUE TITLE
Can't export to file in uSync v14

### ISSUE THREAD

**Issue by chce** [KevinJump/uSync8#675]
**Describe the bug**
I'm trying to export uSync files to a file, but the button has disappeared after upgrading to v14

**To Reproduce**
1. Go to Settings -> uSync
2. Click on Arrow next to Export
3. No option to export to file

**Expected behavior**
I expect to be able to find the button Export to file in the uSync interface

**Screenshots**

**About your Site (please complete the following information):**
 - Umbraco Version: V14
 - uSync Version: V14
 - Browser [e.g. chrome, safari] Chrome

**Additional context**
[Add any other context about the problem here.]
It looks like the button created in uSyncManagementService.cs is missing the export to file action: (https://github.com/KevinJump/uSync/blob/05609186cd23409f889057e70cbfd0ca8ebf1dca/uSync.Backoffice.Management.Api/Services/uSyncManagementService.cs#L47)

**Comment by chce** [comment]
@KevinJump Are you open to a PR fixing this? Or do you have something coming that fixes it?

**Comment by KevinJump** [comment]
HI, 

yeah, its not something we've looked at just now, but we do have a lot of code in uSync.Complete and translation manager we can now lift back in to do it. So, i will take a quick look. 

_not that we are against a PR, but its actually the download code in the typescript that is the big bit, when we did the first v14 release we didn't have time to work it out, but we have it so could save you a lot of time_

**Comment by KevinJump** [comment]
Hi, 

this has made it into the v15 release (but not the v14 one sadly). that's out today, (requires Umbraco v15 too)
