### ISSUE TITLE
Typo in Settings section: Syncronisation

### ISSUE THREAD

**Issue by PerplexDaniel** [KevinJump/uSync8#681]
- uSync `14.2.3`
- Umbraco `14.3.1`

`Syncronisation` misses an `h`, it should be `Synchronisation`. 

It might even have to become `Synchronization` since Umbraco uses US spelling as far as I know (e.g. Color and not Colour)

![image](https://github.com/user-attachments/assets/de3069ad-4b32-445d-ae60-bbe94946dbd1)

**Comment by KevinJump** [comment]
Thanks, fixed in v15, (and will also be in v14 when i push the final update)
