### ISSUE TITLE
MediaTypes are exported incorrectly

### ISSUE THREAD

**Issue by matthewcare** [KevinJump/uSync8#684]
**Describe the bug**
MediaTypes are exported incorrectly.
Properties are written as `System.Threading.Tasks.Task`1[System.Xml.Linq.XElement]`

This is also preventing imports of media types as a result.

**To Reproduce**
Steps to reproduce the behaviour:
Perform an export and observe a file like `image.config` or `file.config` in the uSync folder.

**Expected behavior**
MediaTypes should export correctly

**Screenshots**
![image](https://github.com/user-attachments/assets/da6085ad-e9d5-4c26-b443-432b617ceda1)

**About your Site (please complete the following information):**
 - Umbraco Version: 15
 - uSync Version: 15
 - Browser: Chrome

**Comment by KevinJump** [comment]
thanks 👍 - will look at getting that out asap.

**Comment by KevinJump** [comment]
Fixed in 15.0.1. https://www.nuget.org/packages/uSync/15.0.1
