### ISSUE TITLE
When importing content containing Dropdown fields within a Block list, the original values assigned to these Dropdowns are lost.

### ISSUE THREAD

**Issue by a-t-k** [KevinJump/uSync8#691]
**Describe the bug**
When importing content containing Dropdown fields within a Block list, the original values assigned to these Dropdowns are lost.

**To Reproduce**

In Settings, create a Document Type with a field of type 'Dropdown' that has 3 options: Blue, White, Black. Then, this Dropdown will also be an Element Type.

Next, create another Document Type that includes a field of type 'Block List Property'. This Block List Property contains a Block of the same type as the previously created Dropdown and can be set as the Root element.

Save and publish all changes.

In the Content section, create a new Content item based on this Block. In the Block List, add 2 Dropdowm fields with values 'Blue' and 'Black'. Save and publish again.

Now, use uSync to export everything as a file and import it into a new Umbraco instance.

Upon checking the Content item in the Block section, you should see 2 Dropdowns. However, each of these Dropdowns will have no value assigned, i.e., they will not display 'Blue' or 'Black'.

**Expected behavior**
The original values are available during import.

**About your Site (please complete the following information):**
 - Umbraco Version: 15
 - uSync Version: 15,0,1
 - Browser [e.g. chrome, safari] Chrome

**Comment by KevinJump** [comment]
Hi, 

looks like we have fixed this, efde47e - we just need to push a release, we will check a few things and do that today. 

Kevin

**Comment by KevinJump** [comment]
Fixed and released in uSync v15.0.2
