### ISSUE TITLE
BUG: Import and Export values are not used on Content Handler Events

### ISSUE THREAD

**Issue by KevinJump** [KevinJump/uSync8#87]
The Export/Import settings (see https://docs.jumoo.co.uk/uSync/v8/ContentEdition/contentHandler/) are not being used when set in the config. 

see - https://our.umbraco.com/packages/developer-tools/usync/usync/97809-usync-content-manager-v8-ignore-settings-not-working

this is because while they are read in the method to then get them out of the dictionary isn't doing it right!.

**Comment by KevinJump** [comment]
silly error 😢 -  fixed in ed723b7eb3ae73a3e0e90f388d9e6a73d5e20201

**Comment by lordscarlet** [comment]
I am running `v8.9.7` and the include/exclude values don't seem to be working for me. 

```
<Handler Alias="contentHandler" Enabled="true" Actions="All" >		
			<Add Key="Include" Value="/[rootnodename]/Support" />
			<Add Key="Exclude" Value="/[rootnodename]" />
			<Add Key="RulesOnExport" Value="true" />
		</Handler>
```

It looks like this specific method doesn't even exist anymore in `v8.10`

**Comment by lordscarlet** [comment]
Disregard. I'm not sure what I had wrong (may have needed an `iisreset`?), but this is in fact working as documented.
