### ISSUE TITLE
Known Issue: File Format Change

### ISSUE THREAD

**Issue by KevinJump** [KevinJump/uSync8#9]
uSync 8 has a different file format to usync 4 - as such you cannot just upgrade and have the files still work.

There are a many internal changes (espeically around content items) within Umbraco, and we have used this oppertunity to make the usync format consistant across all items.

Most if not all of the same information is stored in the files and as they are xml there should be some form of transformations that could be built to migrate the information from the old format to the new one, but that hasn't been built (yet)

**Comment by drummerboy46** [comment]
Hi Kevin

I appreciate it's not necessarily been the purpose of uSync to provide compatibility between major versions of Umbraco. But it would be a **MAJOR** plus point to provide such a feature in version 8, especially in the absence of such a migration from the core team (currently).

Do you intention to write a set of XSLT transformations for the XML output and maybe provide a UI for this in uSync itself?

**Comment by KevinJump** [comment]
Yeah - but equally it would be good if the core team provided something ;) 

At the moment (time permitting) there might be a command line tool to take old xml files to the new format.

**Comment by drummerboy46** [comment]
Yes, indeed, I agree. But I do wonder a) how long this likely to take and b) how successful it would be. Past experience of going from 4 - 6 and 6 -7 have left jarring memories lol!

I (i'm sure many) find uSync so valuable that a migration tool (even if its a simple set of transforms) could be more successful than a core migration tool.

**Comment by robertjf** [comment]
it's worth noting that there is mention of a 7 -> 8 migration tool in their Umbraco 8 FAQ, and it was also alluded to at the uDuf conference last Friday - as for how far away it is, hopefully not much farther away than a couple of months... here's hoping, anyway :)

The bigger issue of course is package compatibility...  how long will it take for package maintainers to update to support v8?

**Comment by JoseMarcenaro** [comment]
IMHO, and considering the significant changes in Umbraco v8 data types (i.e. Variants), migrating data types and document types from v7 to v8 should be left to the Umbraco HQ migration tool - rather than attempting to put that burden on uSync8.
 
In my case, knowing that there is a working version of uSync8 will be the defining factor for migrating - even if it requires redefining every type in Umbraco v8 manually. Because doing that is a one time task, while a working version of uSync is a must in the daily workflow of a team.

Kevin, is there anything we can do to help?

**Comment by KevinJump** [comment]
Hi Jose, 

at the moment testing and feedback is good - there are a few rough edges (around reporting mainly) but the main imports should work, so any feedback on errors, or things not syncing is welcome while we work out what works and what needs more attention.

**Comment by KevinJump** [comment]
closing this issue (but i might re-open it if the core migration tool doesn't arrive at some point!)
