### ISSUE TITLE
There is a newer version of uSync avalible [v]

### ISSUE THREAD

**Issue by JoseMarcenaro** [KevinJump/uSync8#95]
Hi Kevin,
just upgraded my uSync v8.4.3 to the latest (v8.6.1) and I get this:
![image](https://user-images.githubusercontent.com/923289/80020659-c657af80-84af-11ea-9c22-19d65e913dd9.png)

Wouldn't mind the inaccurate notification, but the uSync UI is missing..
I completely removed the previous version, removed the DLLs and emptied the /App_Plugins/uSync8 folder, then repeated the install of the new version, but I always get the same page.
I'm running Umbraco v8.6.1 as well.

Any suggestions on what to do?

**Comment by KevinJump** [comment]
Hi, Have you incremented the version number in ClientDependency.Config ? - It might be that an old version of the javascript is being cached,

**Comment by JoseMarcenaro** [comment]
Oops no I didn't.  Rookie mistake.
I'm running in debug mode - so just forcing a reload of the page made the trick (javascript was cached by Chrome)
That fixed it, thanks a lot!

**Comment by KevinJump** [comment]
No worries, its a real pain, I am trying think of reliable ways to flush it when you upgrade (changing script names or something) but haven't really worked anything out just yet.

**Comment by JoseMarcenaro** [comment]
I see.  Shouldn't a version number in the package manifest do the trick? `...........?v=861`
Or the manifest is not even read when the content is cached?

**Comment by KevinJump** [comment]
you would think so and i have done that in the past, but if you do that then the script with the version number on isn't included in the dependency cache at all (which may be a good thing, but means the scripts are no longer minified :( - so if you where to minify them yourself this would be a way. ....

**Comment by JoseMarcenaro** [comment]
You are right.  I guess I prefer to remember to force the update (via clientDependency or forced refresh, depending on the environment) and keep the scripts minified.
Thanks again.

**Comment by KevinJump** [comment]
for now we've added a js and css file with the version number in the name 12f9f528aebd7a1473c69637fab3436be3f9d778 this should at least break the cache (because the list of file names is used to make the hash value in client dependency. Just need to build this into the release process so we don't forget to increment it.
